#!/usr/bin/env python3
"""Exercise clone, submodule, and flattened-archive Skill installation modes."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

SOURCE_ROOT = Path(__file__).resolve().parents[2]
VALIDATOR = SOURCE_ROOT / "template/.github/scripts/validate_skill_repository.py"
EXPECTED_FILES = ["SKILL.md", "scripts/normalize.py"]
FAILURES: list[str] = []

SKILL_DOCUMENT = """---
name: portable-line-normalizer
description: Normalize a supplied UTF-8 text file deterministically through one private helper without network access or dependency installation.
---

# Portable line normalizer

## Purpose

Normalize line endings and trailing horizontal whitespace without changing the source file.

## Use this skill when

Use this skill when deterministic UTF-8 text normalization is required before comparison or review.

## Do not use this skill when

Do not use this skill for binary input, network resources, package installation, or a public CLI compatibility contract.

## Required inputs and prerequisites

A readable UTF-8 input path, a distinct writable output path, and CPython 3.12 or newer must be available.

## Helper scripts

Script: scripts/normalize.py
Run when: the supplied UTF-8 file must be normalized before comparison or delivery
Exact invocation: python scripts/normalize.py INPUT OUTPUT
Working directory: skill root
Inputs and arguments: INPUT is a readable UTF-8 file and OUTPUT is a distinct destination path
Stdout/result: prints OUTPUT after a successful atomic write
Stderr/diagnostics: reports invalid arguments, aliased paths, unreadable input, invalid UTF-8, or write failure
Exit status: zero on success, 2 for invalid invocation or aliases, 3 for invalid UTF-8, and 1 for file-system failure
Files or external state modified: writes or replaces only OUTPUT and never changes INPUT
Network access: NONE
Required permissions: read INPUT and write the OUTPUT directory
Automatic execution allowed: YES
Human confirmation required: NO
Idempotency and retry behavior: identical input produces identical output; retry only after correcting the failure

## Workflow

1. Confirm INPUT and OUTPUT are distinct.
2. Run `python scripts/normalize.py INPUT OUTPUT` from the skill root.
3. Stop on nonzero status and report stderr.
4. Verify the generated bytes and report OUTPUT.

## Output requirements

Return the output path and whether normalization changed the text.

## Validation

Confirm OUTPUT is UTF-8 with LF endings, no trailing horizontal whitespace, one final newline, and unchanged INPUT.

## Safety and approval

Do not access the network, install dependencies, execute subprocesses, or write any path other than OUTPUT.

## Edge cases and failure handling

Reject missing arguments, aliased paths, invalid UTF-8, and inaccessible paths without partial output.

Selected profiles: script-assisted
"""

HELPER_SOURCE = r'''#!/usr/bin/env python3
from __future__ import annotations
import os
import re
import sys
from pathlib import Path


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: python scripts/normalize.py INPUT OUTPUT", file=sys.stderr)
        return 2
    input_text, output_text = argv
    input_path = Path(input_text)
    output_path = Path(output_text)
    temporary: Path | None = None
    try:
        if os.path.abspath(input_path) == os.path.abspath(output_path) or (
            output_path.exists() and os.path.samefile(input_path, output_path)
        ):
            print("input and output must refer to different files", file=sys.stderr)
            return 2
        raw = input_path.read_bytes()
        try:
            text = raw.decode("utf-8")
        except UnicodeDecodeError:
            print("invalid UTF-8 input", file=sys.stderr)
            return 3
        normalized = text.replace("\r\n", "\n").replace("\r", "\n")
        normalized = re.sub(r"[\t ]+(?=\n|$)", "", normalized)
        normalized = normalized.rstrip("\n") + "\n"
        temporary = Path(f"{output_text}.tmp-{os.getpid()}")
        temporary.write_bytes(normalized.encode("utf-8"))
        os.replace(temporary, output_path)
        temporary = None
        print(output_text)
        return 0
    except OSError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    finally:
        if temporary is not None:
            try:
                temporary.unlink()
            except FileNotFoundError:
                pass


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
'''
FORBIDDEN_HELPER_TOKENS = (
    "socket",
    "urllib",
    "requests",
    "pip install",
    "subprocess",
    "os.system",
    "os.spawn",
    "os.exec",
)


def capture(
    *command: str, cwd: Path, extra_env: dict[str, str] | None = None
) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    for key in ("PYTHONPATH", "GIT_DIR", "GIT_INDEX_FILE", "GIT_WORK_TREE"):
        env.pop(key, None)
    if extra_env:
        env.update(extra_env)
    return subprocess.run(
        list(command),
        cwd=cwd,
        env=env,
        text=True,
        encoding="utf-8",
        capture_output=True,
        check=False,
    )


def run_or_raise(
    *command: str, cwd: Path, extra_env: dict[str, str] | None = None
) -> str:
    result = capture(*command, cwd=cwd, extra_env=extra_env)
    if result.returncode != 0:
        raise RuntimeError(
            f"command failed: {command!r}; status={result.returncode!r}; "
            f"stdout={result.stdout!r}; stderr={result.stderr!r}"
        )
    return result.stdout


def copy_canonical_root(target: Path) -> None:
    target.mkdir(parents=True, exist_ok=True)
    for source in sorted(SOURCE_ROOT.iterdir(), key=lambda path: path.name):
        if source.name == ".git":
            continue
        destination = target / source.name
        if source.is_dir() and not source.is_symlink():
            shutil.copytree(source, destination, symlinks=True)
        else:
            shutil.copy2(source, destination, follow_symlinks=False)
    skill_path = target / "SKILL.md"
    valid_source = (
        skill_path.is_file()
        and "Selected profiles: template-scaffold"
        in skill_path.read_text(encoding="utf-8")
        and (target / "README.md").is_file()
    )
    if not valid_source:
        raise RuntimeError("copy did not originate from the canonical repository root")


def prune_to(root: Path, retained: set[str]) -> None:
    for path in sorted(root.rglob("*"), key=lambda item: len(item.parts), reverse=True):
        relative = path.relative_to(root).as_posix()
        keep = relative in retained or any(
            candidate.startswith(relative + "/") for candidate in retained
        )
        if keep:
            continue
        if path.is_dir() and not path.is_symlink():
            try:
                path.rmdir()
            except OSError:
                pass
        else:
            path.unlink(missing_ok=True)


def materialize_source(target: Path) -> None:
    copy_canonical_root(target)
    (target / "SKILL.md").write_text(SKILL_DOCUMENT, encoding="utf-8")
    prune_to(target, {"SKILL.md"})
    (target / "scripts").mkdir(parents=True)
    (target / "scripts/normalize.py").write_text(HELPER_SOURCE, encoding="utf-8")
    run_or_raise("git", "init", "--quiet", cwd=target)
    run_or_raise("git", "config", "user.name", "Installation Mode Fixture", cwd=target)
    run_or_raise(
        "git", "config", "user.email", "fixture@example.invalid", cwd=target
    )
    run_or_raise("git", "add", ".", cwd=target)
    run_or_raise("git", "commit", "--quiet", "-m", "Create concrete skill", cwd=target)


def inventory(root: Path) -> list[str]:
    return sorted(
        path.relative_to(root).as_posix()
        for path in root.rglob("*")
        if not path.is_dir()
        and path.relative_to(root).parts[0] != ".git"
    )


def content_map(root: Path) -> dict[str, bytes]:
    return {relative: (root / relative).read_bytes() for relative in EXPECTED_FILES}


def git_mode_map(root: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    for relative in EXPECTED_FILES:
        executable_bits = (root / relative).stat().st_mode & 0o111
        result[relative] = "100644" if executable_bits == 0 else "100755"
    return result


def validate(
    target: Path, outside: Path, extra_env: dict[str, str] | None = None
) -> subprocess.CompletedProcess[str]:
    return capture(
        sys.executable,
        str(VALIDATOR),
        str(target),
        cwd=outside,
        extra_env=extra_env,
    )


def expect_validation_success(
    label: str,
    target: Path,
    outside: Path,
    extra_env: dict[str, str] | None = None,
) -> None:
    result = validate(target, outside, extra_env)
    if not (
        result.returncode == 0
        and result.stderr == ""
        and "Agent Skill repository structure and profile contracts are valid."
        in result.stdout
    ):
        FAILURES.append(
            f"{label}: expected validation success; status={result.returncode!r}, "
            f"stdout={result.stdout!r}, stderr={result.stderr!r}"
        )


def expect_validation_failure(
    label: str, target: Path, outside: Path, diagnostic: str
) -> None:
    result = validate(target, outside)
    if result.returncode == 0:
        FAILURES.append(f"{label}: expected validation failure")
    elif diagnostic not in result.stderr:
        FAILURES.append(
            f"{label}: expected diagnostic {diagnostic!r}; stderr={result.stderr!r}"
        )


def exercise_helper(label: str, target: Path) -> None:
    input_path = target / "input.txt"
    output_path = target / "output.txt"
    input_path.write_bytes(b"alpha  \r\nbeta\t\r\n")
    before = input_path.read_bytes()
    result = capture(
        sys.executable,
        "scripts/normalize.py",
        "input.txt",
        "output.txt",
        cwd=target,
    )
    output = output_path.read_bytes() if output_path.is_file() else None
    if not (
        result.returncode == 0
        and result.stdout == "output.txt\n"
        and result.stderr == ""
        and output == b"alpha\nbeta\n"
        and input_path.read_bytes() == before
    ):
        FAILURES.append(
            f"{label} helper: status={result.returncode!r}, stdout={result.stdout!r}, "
            f"stderr={result.stderr!r}, output={output!r}, "
            f"input_unchanged={input_path.read_bytes() == before}"
        )


def main() -> int:
    with tempfile.TemporaryDirectory(prefix="installation-mode-smoke") as temporary:
        workspace = Path(temporary)
        outside = workspace / "outside"
        source = workspace / "concrete-skill-source"
        outside.mkdir(parents=True)
        materialize_source(source)

        clone_target = workspace / "user-home/.agents/skills/clone-skill"
        clone_target.parent.mkdir(parents=True)
        run_or_raise("git", "clone", "--quiet", str(source), str(clone_target), cwd=workspace)

        submodule_project = workspace / "submodule-project"
        submodule_project.mkdir()
        run_or_raise("git", "init", "--quiet", cwd=submodule_project)
        run_or_raise(
            "git", "config", "user.name", "Installation Mode Fixture", cwd=submodule_project
        )
        run_or_raise(
            "git", "config", "user.email", "fixture@example.invalid", cwd=submodule_project
        )
        submodule_target = submodule_project / ".agents/skills/submodule-skill"
        run_or_raise(
            "git",
            "-c",
            "protocol.file.allow=always",
            "submodule",
            "add",
            "--quiet",
            str(source),
            ".agents/skills/submodule-skill",
            cwd=submodule_project,
        )
        run_or_raise(
            "git",
            "add",
            ".gitmodules",
            ".agents/skills/submodule-skill",
            cwd=submodule_project,
        )

        archive_path = workspace / "concrete-skill.tar"
        run_or_raise(
            "git",
            "archive",
            "--format=tar",
            "--prefix=concrete-skill/",
            f"--output={archive_path}",
            "HEAD",
            cwd=source,
        )
        extracted = workspace / "archive-extracted"
        extracted.mkdir()
        run_or_raise("tar", "-xf", str(archive_path), "-C", str(extracted), cwd=workspace)
        archive_target = workspace / "archive-project/.agents/skills/archive-skill"
        archive_target.mkdir(parents=True)
        shutil.copytree(
            extracted / "concrete-skill",
            archive_target,
            dirs_exist_ok=True,
            symlinks=True,
        )

        targets = {
            "clone installation": clone_target,
            "submodule installation": submodule_target,
            "archive installation": archive_target,
        }
        expected_content = content_map(source)
        expected_git_modes = git_mode_map(source)
        for label, target in targets.items():
            actual_inventory = inventory(target)
            if actual_inventory != sorted(EXPECTED_FILES):
                FAILURES.append(
                    f"{label}: expected inventory {sorted(EXPECTED_FILES)!r}, got {actual_inventory!r}"
                )
            if content_map(target) != expected_content:
                FAILURES.append(f"{label}: content differs from committed source")
            if git_mode_map(target) != expected_git_modes:
                FAILURES.append(
                    f"{label}: Git-significant executable modes differ from committed source"
                )
            if (target / "concrete-skill").is_dir():
                FAILURES.append(f"{label}: unexpected archive wrapper")
            expect_validation_success(label, target, outside)
            exercise_helper(label, target)

        if not (clone_target / ".git").is_dir():
            FAILURES.append("clone installation: expected a .git directory")
        submodule_git = submodule_target / ".git"
        if not (
            submodule_git.is_file()
            and submodule_git.read_text(encoding="utf-8").startswith("gitdir:")
        ):
            FAILURES.append("submodule installation: expected a .git indirection file")
        submodule_index = run_or_raise(
            "git",
            "ls-files",
            "--stage",
            "--",
            ".agents/skills/submodule-skill",
            cwd=submodule_project,
        )
        if not submodule_index.startswith("160000 "):
            FAILURES.append(
                "submodule installation: parent index must retain mode 160000"
            )

        archive_git = capture(
            "git", "rev-parse", "--is-inside-work-tree", cwd=archive_target
        )
        if archive_git.returncode == 0 or archive_git.stdout or not archive_git.stderr:
            FAILURES.append(
                "archive installation: expected a target independent of Git metadata"
            )
        if (archive_target / ".git").exists():
            FAILURES.append("archive installation: unexpected .git metadata")

        alternate_index = workspace / "caller-owned.index"
        run_or_raise(
            "git",
            "read-tree",
            "HEAD",
            cwd=source,
            extra_env={"GIT_INDEX_FILE": str(alternate_index)},
        )
        caller_index_before = alternate_index.read_bytes()
        expect_validation_success(
            "archive installation with caller-owned alternate index",
            archive_target,
            outside,
            {"GIT_INDEX_FILE": str(alternate_index)},
        )
        if alternate_index.read_bytes() != caller_index_before:
            FAILURES.append(
                "archive installation: validation modified the caller-owned alternate Git index"
            )

        wrapped_target = workspace / "wrapped-project/.agents/skills/wrapped-skill"
        wrapped_target.mkdir(parents=True)
        shutil.copytree(
            extracted / "concrete-skill",
            wrapped_target / "concrete-skill",
            symlinks=True,
        )
        expect_validation_failure(
            "archive wrapper rejection",
            wrapped_target,
            outside,
            "Missing universally required file: SKILL.md",
        )

        for label, target in targets.items():
            undeclared = target / "scripts/undeclared.py"
            undeclared.write_text("print('undeclared')\n", encoding="utf-8")
            expect_validation_failure(
                f"{label} undeclared resource rejection",
                target,
                outside,
                "SKILL.md must declare the exact retained resource path as 'Script: scripts/undeclared.py'.",
            )
            undeclared.unlink()

        for token in FORBIDDEN_HELPER_TOKENS:
            if token in HELPER_SOURCE:
                FAILURES.append(f"committed helper contains forbidden token {token!r}")

    if FAILURES:
        for failure in FAILURES:
            print(failure, file=sys.stderr)
        return 1
    print("Installation mode smoke tests passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
