#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require "find"
require "open3"
require "rbconfig"
require "tmpdir"

SOURCE_ROOT = File.expand_path("../..", __dir__)
VALIDATOR = File.join(SOURCE_ROOT, ".github/scripts/validate-skill-repository.rb")

INSTRUCTION_SKILL = <<~MARKDOWN.freeze
  ---
  name: evidence-summary
  description: Summarize supplied evidence into a bounded factual result without modifying files or external systems.
  ---

  # Evidence summary

  ## Purpose

  Produce a concise summary that separates observed facts, implications, and unresolved uncertainty.

  ## Use this skill when

  Use this skill when the user supplies a bounded evidence set and requests a factual summary.

  ## Do not use this skill when

  Do not use this skill when the task requires external research, file mutation, or an implementation helper.

  ## Required inputs and prerequisites

  The complete evidence set and requested output scope must be available in the conversation.

  ## Workflow

  1. Read the supplied evidence completely.
  2. Group related facts without inventing intent or missing details.
  3. Distinguish observations, supported implications, and unresolved uncertainty.
  4. Check every statement against the supplied evidence.

  ## Output requirements

  Return a concise prose summary with explicit uncertainty where the evidence is incomplete.

  ## Validation

  Confirm every reported fact is supported and no external state was accessed or modified.

  ## Safety and approval

  Remain read-only and do not infer permission, hidden motivation, or absent facts.

  ## Edge cases and failure handling

  Stop and report missing evidence when the supplied material is incomplete or inconsistent.

  Selected profiles: instruction-only
MARKDOWN

SCRIPT_SKILL = <<~MARKDOWN.freeze
  ---
  name: bounded-line-normalizer
  description: Normalize a supplied UTF-8 text file deterministically with one private helper and report the generated output path.
  ---

  # Bounded line normalizer

  ## Purpose

  Normalize line endings and trailing horizontal whitespace without changing the source file.

  ## Use this skill when

  Use this skill when deterministic text normalization is required before comparison or review.

  ## Do not use this skill when

  Do not use this skill for binary input, network resources, dependency installation, or a public CLI contract.

  ## Required inputs and prerequisites

  A readable UTF-8 input path, a distinct writable output path, and CRuby 3.1 or newer must be available.

  ## Helper scripts

  Script: scripts/normalize.rb
  Run when: the supplied UTF-8 file must be normalized before comparison or delivery
  Exact invocation: ruby scripts/normalize.rb INPUT OUTPUT
  Working directory: skill root
  Inputs and arguments: INPUT is a readable UTF-8 file and OUTPUT is a distinct destination path
  Stdout/result: prints OUTPUT after a successful atomic write
  Stderr/diagnostics: reports invalid arguments, aliased paths, unreadable input, invalid UTF-8, or write failure
  Exit status: zero on success, 2 for invalid invocation or aliases, 3 for invalid UTF-8, and 1 for file-system failure
  Files or external state modified: writes or replaces only OUTPUT and never changes INPUT
  Network access: NONE
  Required permissions: read INPUT and write the OUTPUT directory
  Automatic execution allowed: YES
  Human confirmation required: NO
  Idempotency and retry behavior: identical input produces identical output; retry only after correcting the failure

  ## Workflow

  1. Confirm INPUT and OUTPUT are distinct.
  2. Run `ruby scripts/normalize.rb INPUT OUTPUT` from the skill root.
  3. Stop on nonzero status and report stderr.
  4. Verify the generated bytes and report OUTPUT.

  ## Output requirements

  Return the output path and whether normalization changed the text.

  ## Validation

  Confirm OUTPUT is UTF-8 with LF endings, no trailing horizontal whitespace, one final newline, and unchanged INPUT.

  ## Safety and approval

  Do not access the network, install dependencies, execute subprocesses, or write any path other than OUTPUT.

  ## Edge cases and failure handling

  Reject missing arguments, aliased paths, invalid UTF-8, and inaccessible paths without partial output.

  Selected profiles: script-assisted
MARKDOWN

SCRIPT_SOURCE = <<~'RUBY'.freeze
  #!/usr/bin/env ruby
  # frozen_string_literal: true

  begin
    unless ARGV.length == 2
      warn "usage: ruby scripts/normalize.rb INPUT OUTPUT"
      exit 2
    end

    input_path, output_path = ARGV
    if File.expand_path(input_path) == File.expand_path(output_path) ||
       (File.exist?(output_path) && File.identical?(input_path, output_path))
      warn "input and output must refer to different files"
      exit 2
    end

    text = File.binread(input_path).force_encoding(Encoding::UTF_8)
    unless text.valid_encoding?
      warn "invalid UTF-8 input"
      exit 3
    end

    normalized = text.gsub("\r\n", "\n").gsub("\r", "\n")
    normalized = normalized.lines.map { |line| line.sub(/[\t ]+(?=\n?\z)/, "") }.join
    normalized = "#{normalized.sub(/\n*\z/, "")}\n"
    temporary = "#{output_path}.tmp-#{Process.pid}"
    File.binwrite(temporary, normalized)
    File.rename(temporary, output_path)
    puts output_path
  rescue SystemCallError => e
    warn e.message
    exit 1
  ensure
    File.delete(temporary) if defined?(temporary) && temporary && File.exist?(temporary)
  end
RUBY

failures = []

copy_root = lambda do |target|
  FileUtils.mkdir_p(target)
  Dir.children(SOURCE_ROOT).sort.each do |entry|
    next if entry == ".git"

    FileUtils.cp_r(File.join(SOURCE_ROOT, entry), File.join(target, entry), preserve: true)
  end
  raise "source git metadata was copied" if File.exist?(File.join(target, ".git"))

  skill = File.join(target, "SKILL.md")
  unless File.file?(skill) && File.read(skill, encoding: "UTF-8").include?("Selected profiles: template-scaffold") &&
         File.file?(File.join(target, "README.md"))
    raise "copy did not originate from the canonical repository root"
  end
end

customize = lambda do |target, content|
  path = File.join(target, "SKILL.md")
  raise ArgumentError, "canonical SKILL.md is missing" unless File.file?(path)
  raise ArgumentError, "canonical profile marker is missing" unless File.read(path).include?("Selected profiles: template-scaffold")

  File.write(path, content, encoding: "UTF-8")
end

prune_to = lambda do |root, retained|
  Find.find(root).to_a.sort_by { |path| -path.count(File::SEPARATOR) }.each do |path|
    next if path == root

    relative = path.delete_prefix("#{root}/")
    keep = retained.include?(relative) || retained.any? { |candidate| candidate.start_with?("#{relative}/") }
    next if keep

    if File.directory?(path) && !File.symlink?(path)
      Dir.rmdir(path) if Dir.empty?(path)
    else
      FileUtils.rm_f(path)
    end
  end
end

inventory = lambda do |root|
  Find.find(root).filter_map do |path|
    next if path == root || File.directory?(path)

    relative = path.delete_prefix("#{root}/")
    next if relative == ".git" || relative.start_with?(".git/")

    relative
  end.sort
end

initialize_repository = lambda do |target|
  [["git", "init", "--quiet"], ["git", "add", "."]].each do |command|
    _stdout, stderr, status = Open3.capture3(*command, chdir: target)
    raise "#{command.join(' ')} failed: #{stderr}" unless status.success?
  end
end

run_validator = lambda do |target, cwd:, explicit_root:|
  command = [RbConfig.ruby, VALIDATOR]
  command << target if explicit_root
  Open3.capture3({ "RUBYOPT" => nil }, *command, chdir: cwd)
end

expect_success = lambda do |label, target, outside|
  [[outside, true, "external cwd"], [target, false, "skill cwd"]].each do |cwd, explicit_root, mode|
    stdout, stderr, status = run_validator.call(target, cwd: cwd, explicit_root: explicit_root)
    unless status.success? && stderr.empty? && stdout.include?("Agent Skill repository structure and profile contracts are valid.")
      failures << "#{label} #{mode}: status=#{status.exitstatus.inspect}, stdout=#{stdout.inspect}, stderr=#{stderr.inspect}"
    end
  end
end

expect_failure = lambda do |label, target, outside|
  Open3.capture3("git", "add", "-A", chdir: target)
  _stdout, stderr, status = run_validator.call(target, cwd: outside, explicit_root: true)
  failures << "#{label}: expected validation failure" if status.success?
  failures << "#{label}: expected actionable diagnostics" if !status.success? && stderr.strip.empty?
end

Dir.mktmpdir("template-adoption-smoke") do |workspace|
  project = File.join(workspace, "project")
  outside = File.join(workspace, "outside")
  FileUtils.mkdir_p(outside)

  renamed = File.join(workspace, "renamed-source")
  copy_root.call(renamed)
  FileUtils.mv(File.join(renamed, "SKILL.md"), File.join(renamed, "RENAMED.md"))
  begin
    customize.call(renamed, INSTRUCTION_SKILL)
    failures << "canonical SKILL.md rename: expected an actionable failure"
  rescue ArgumentError => e
    failures << "canonical SKILL.md rename: wrong diagnostic #{e.message.inspect}" unless e.message == "canonical SKILL.md is missing"
  end

  instruction = File.join(project, ".agents", "skills", "example-instruction-skill")
  copy_root.call(instruction)
  customize.call(instruction, INSTRUCTION_SKILL)
  prune_to.call(instruction, ["SKILL.md"])
  actual = inventory.call(instruction)
  failures << "instruction-only inventory: expected [\"SKILL.md\"], got #{actual.inspect}" unless actual == ["SKILL.md"]
  failures << "instruction-only wrapper: unexpected skill/ directory" if Dir.exist?(File.join(instruction, "skill"))
  initialize_repository.call(instruction)
  expect_success.call("instruction-only adoption", instruction, outside)

  skill_path = File.join(instruction, "SKILL.md")
  valid_skill = File.read(skill_path, encoding: "UTF-8")
  File.write(skill_path, valid_skill.sub(/description: .+/, "description: TODO"), encoding: "UTF-8")
  expect_failure.call("instruction-only unresolved placeholder", instruction, outside)
  File.write(skill_path, valid_skill, encoding: "UTF-8")
  File.write(File.join(instruction, "RUNTIME.md"), "# Unnecessary runtime contract\n", encoding: "UTF-8")
  expect_failure.call("instruction-only unnecessary runtime", instruction, outside)
  File.delete(File.join(instruction, "RUNTIME.md"))

  script = File.join(project, ".agents", "skills", "example-script-skill")
  copy_root.call(script)
  customize.call(script, SCRIPT_SKILL)
  prune_to.call(script, ["SKILL.md"])
  FileUtils.mkdir_p(File.join(script, "scripts"))
  File.write(File.join(script, "scripts", "normalize.rb"), SCRIPT_SOURCE, encoding: "UTF-8")
  expected = ["SKILL.md", "scripts/normalize.rb"]
  actual = inventory.call(script)
  failures << "script-assisted inventory: expected #{expected.inspect}, got #{actual.inspect}" unless actual == expected
  failures << "script-assisted runtime: RUNTIME.md must be pruned" if File.exist?(File.join(script, "RUNTIME.md"))
  initialize_repository.call(script)
  expect_success.call("script-assisted adoption", script, outside)

  File.binwrite(File.join(script, "input.txt"), "alpha  \r\nbeta\t\r\n")
  before = File.binread(File.join(script, "input.txt"))
  stdout, stderr, status = Open3.capture3(RbConfig.ruby, "scripts/normalize.rb", "input.txt", "output.txt", chdir: script)
  output = File.binread(File.join(script, "output.txt")) if File.file?(File.join(script, "output.txt"))
  unless status.success? && stdout == "output.txt\n" && stderr.empty? && output == "alpha\nbeta\n" &&
         File.binread(File.join(script, "input.txt")) == before
    failures << "script helper success: status=#{status.exitstatus.inspect}, stdout=#{stdout.inspect}, stderr=#{stderr.inspect}, output=#{output.inspect}"
  end

  File.binwrite(File.join(script, "invalid.txt"), [0xFF].pack("C"))
  stdout, stderr, status = Open3.capture3(RbConfig.ruby, "scripts/normalize.rb", "invalid.txt", "invalid-output.txt", chdir: script)
  unless status.exitstatus == 3 && stdout.empty? && stderr == "invalid UTF-8 input\n" && !File.exist?(File.join(script, "invalid-output.txt"))
    failures << "script helper failure: status=#{status.exitstatus.inspect}, stdout=#{stdout.inspect}, stderr=#{stderr.inspect}"
  end

  %w[Net:: TCPSocket UDPSocket open-uri gem\ install bundle\ install Kernel.system Process.spawn Kernel.exec].each do |token|
    failures << "script helper contains forbidden token #{token.inspect}" if SCRIPT_SOURCE.include?(token.tr("\\", ""))
  end

  File.write(File.join(script, "scripts", "undeclared.rb"), "puts 'undeclared'\n", encoding: "UTF-8")
  expect_failure.call("script-assisted undeclared helper", script, outside)
end

unless failures.empty?
  failures.each { |failure| warn failure }
  exit 1
end

puts "Template adoption smoke tests passed."
