#!/usr/bin/env python3
"""Smoke-test specializing a copied canonical Skill template."""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

SOURCE_ROOT = Path(__file__).resolve().parents[2]
VALIDATOR = SOURCE_ROOT / "template/.github/scripts/validate_skill_repository.py"

INSTRUCTION_SKILL = """---
name: evidence-summary
description: Summarize supplied evidence into a bounded factual result without modifying files or external systems.
---

# Evidence summary

## Purpose

Produce a concise summary that separates observed facts, implications, and unresolved uncertainty.

## Use this skill when

Use this skill when the user supplies a bounded evidence set and requests a factual summary.

## Do not use this skill when

Do not use this skill when the task requires external research, file mutation, or an implementation helper.

## Required inputs and prerequisites

The complete evidence set and requested output scope must be available in the conversation.

## Workflow

1. Read the supplied evidence completely.
2. Group related facts without inventing intent or missing details.
3. Distinguish observations, supported implications, and unresolved uncertainty.
4. Check every statement against the supplied evidence.

## Output requirements

Return a concise prose summary with explicit uncertainty where the evidence is incomplete.

## Validation

Confirm every reported fact is supported and no external state was accessed or modified.

## Safety and approval

Remain read-only and do not infer permission, hidden motivation, or absent facts.

## Edge cases and failure handling

Stop and report missing evidence when the supplied material is incomplete or inconsistent.

Selected profiles: instruction-only
"""

SCRIPT_SKILL = """---
name: bounded-line-normalizer
description: Normalize a supplied UTF-8 text file deterministically with one private helper and report the generated output path.
---

# Bounded line normalizer

## Purpose

Normalize line endings and trailing horizontal whitespace without changing the source file.

## Use this skill when

Use this skill when deterministic text normalization is required before comparison or review.

## Do not use this skill when

Do not use this skill for binary input, network resources, dependency installation, or a public CLI contract.

## Required inputs and prerequisites

A readable UTF-8 input path, a distinct writable output path, and CPython 3.12 or newer must be available.

## Helper scripts

Script: scripts/normalize.py
Run when: the supplied UTF-8 file must be normalized before comparison or delivery
Exact invocation: python scripts/normalize.py INPUT OUTPUT
Working directory: skill root
Inputs and arguments: INPUT is a readable UTF-8 file and OUTPUT is a distinct destination path
Stdout/result: prints OUTPUT after a successful atomic write
Stderr/diagnostics: reports invalid arguments, aliased paths, unreadable input, invalid UTF-8, or write failure
Exit status: zero on success, 2 for invalid invocation or aliases, 3 for invalid UTF-8, and 1 for file-system failure
Files or external state modified: writes or replaces only OUTPUT and never changes INPUT
Network access: NONE
Required permissions: read INPUT and write the OUTPUT directory
Automatic execution allowed: YES
Human confirmation required: NO
Idempotency and retry behavior: identical input produces identical output; retry only after correcting the failure

## Workflow

1. Confirm INPUT and OUTPUT are distinct.
2. Run `python scripts/normalize.py INPUT OUTPUT` from the skill root.
3. Stop on nonzero status and report stderr.
4. Verify the generated bytes and report OUTPUT.

## Output requirements

Return the output path and whether normalization changed the text.

## Validation

Confirm OUTPUT is UTF-8 with LF endings, no trailing horizontal whitespace, one final newline, and unchanged INPUT.

## Safety and approval

Do not access the network, install dependencies, execute subprocesses, or write any path other than OUTPUT.

## Edge cases and failure handling

Reject missing arguments, aliased paths, invalid UTF-8, and inaccessible paths without partial output.

Selected profiles: script-assisted
"""

SCRIPT_SOURCE = r'''#!/usr/bin/env python3
from __future__ import annotations
import os
import re
import sys
from pathlib import Path


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: python scripts/normalize.py INPUT OUTPUT", file=sys.stderr)
        return 2
    input_text, output_text = argv
    input_path = Path(input_text)
    output_path = Path(output_text)
    temporary: Path | None = None
    try:
        if os.path.abspath(input_path) == os.path.abspath(output_path) or (
            output_path.exists() and os.path.samefile(input_path, output_path)
        ):
            print("input and output must refer to different files", file=sys.stderr)
            return 2
        raw = input_path.read_bytes()
        try:
            text = raw.decode("utf-8")
        except UnicodeDecodeError:
            print("invalid UTF-8 input", file=sys.stderr)
            return 3
        normalized = text.replace("\r\n", "\n").replace("\r", "\n")
        normalized = re.sub(r"[\t ]+(?=\n|$)", "", normalized)
        normalized = normalized.rstrip("\n") + "\n"
        temporary = Path(f"{output_text}.tmp-{os.getpid()}")
        temporary.write_bytes(normalized.encode("utf-8"))
        os.replace(temporary, output_path)
        temporary = None
        print(output_text)
        return 0
    except OSError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    finally:
        if temporary is not None:
            try:
                temporary.unlink()
            except FileNotFoundError:
                pass


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
'''


def run(command: list[str], *, cwd: Path) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    for key in ("PYTHONPATH", "GIT_DIR", "GIT_INDEX_FILE", "GIT_WORK_TREE"):
        env.pop(key, None)
    return subprocess.run(
        command,
        cwd=cwd,
        env=env,
        text=True,
        encoding="utf-8",
        capture_output=True,
        check=False,
    )


def copy_root(target: Path) -> None:
    target.mkdir(parents=True, exist_ok=True)
    for source in sorted(SOURCE_ROOT.iterdir(), key=lambda path: path.name):
        if source.name == ".git":
            continue
        destination = target / source.name
        if source.is_dir() and not source.is_symlink():
            shutil.copytree(source, destination, symlinks=True)
        else:
            shutil.copy2(source, destination, follow_symlinks=False)
    if (target / ".git").exists():
        raise RuntimeError("source git metadata was copied")
    skill = target / "SKILL.md"
    if not (
        skill.is_file()
        and "Selected profiles: template-scaffold" in skill.read_text(encoding="utf-8")
        and (target / "README.md").is_file()
    ):
        raise RuntimeError("copy did not originate from the canonical repository root")


def customize(target: Path, content: str) -> None:
    path = target / "SKILL.md"
    if not path.is_file():
        raise ValueError("canonical SKILL.md is missing")
    if "Selected profiles: template-scaffold" not in path.read_text(encoding="utf-8"):
        raise ValueError("canonical profile marker is missing")
    path.write_text(content, encoding="utf-8")


def prune_to(root: Path, retained: set[str]) -> None:
    paths = sorted(root.rglob("*"), key=lambda path: len(path.parts), reverse=True)
    for path in paths:
        relative = path.relative_to(root).as_posix()
        keep = relative in retained or any(
            candidate.startswith(relative + "/") for candidate in retained
        )
        if keep:
            continue
        if path.is_dir() and not path.is_symlink():
            try:
                path.rmdir()
            except OSError:
                pass
        else:
            path.unlink(missing_ok=True)


def inventory(root: Path) -> list[str]:
    return sorted(
        path.relative_to(root).as_posix()
        for path in root.rglob("*")
        if not path.is_dir()
        and path.relative_to(root).parts[0] != ".git"
    )


def initialize_repository(target: Path) -> None:
    for command in (["git", "init", "--quiet"], ["git", "add", "."]):
        result = run(command, cwd=target)
        if result.returncode != 0:
            raise RuntimeError(f"{' '.join(command)} failed: {result.stderr}")


def validate(target: Path, *, cwd: Path, explicit_root: bool) -> subprocess.CompletedProcess[str]:
    command = [sys.executable, str(VALIDATOR)]
    if explicit_root:
        command.append(str(target))
    return run(command, cwd=cwd)


def main() -> int:
    failures: list[str] = []
    with tempfile.TemporaryDirectory(prefix="template-adoption-smoke") as temporary:
        workspace = Path(temporary)
        project = workspace / "project"
        outside = workspace / "outside"
        outside.mkdir(parents=True)

        renamed = workspace / "renamed-source"
        copy_root(renamed)
        (renamed / "SKILL.md").rename(renamed / "RENAMED.md")
        try:
            customize(renamed, INSTRUCTION_SKILL)
            failures.append("canonical SKILL.md rename: expected an actionable failure")
        except ValueError as exc:
            if str(exc) != "canonical SKILL.md is missing":
                failures.append(
                    f"canonical SKILL.md rename: wrong diagnostic {str(exc)!r}"
                )

        instruction = project / ".agents/skills/example-instruction-skill"
        copy_root(instruction)
        customize(instruction, INSTRUCTION_SKILL)
        prune_to(instruction, {"SKILL.md"})
        actual = inventory(instruction)
        if actual != ["SKILL.md"]:
            failures.append(
                f"instruction-only inventory: expected ['SKILL.md'], got {actual!r}"
            )
        if (instruction / "skill").is_dir():
            failures.append("instruction-only wrapper: unexpected skill/ directory")
        initialize_repository(instruction)
        for cwd, explicit_root, mode in (
            (outside, True, "external cwd"),
            (instruction, False, "skill cwd"),
        ):
            result = validate(instruction, cwd=cwd, explicit_root=explicit_root)
            if not (
                result.returncode == 0
                and result.stderr == ""
                and "Agent Skill repository structure and profile contracts are valid."
                in result.stdout
            ):
                failures.append(
                    f"instruction-only adoption {mode}: status={result.returncode!r}, "
                    f"stdout={result.stdout!r}, stderr={result.stderr!r}"
                )

        skill_path = instruction / "SKILL.md"
        valid_skill = skill_path.read_text(encoding="utf-8")
        skill_path.write_text(
            re.sub(r"description: .+", "description: TODO", valid_skill, count=1),
            encoding="utf-8",
        )
        run(["git", "add", "-A"], cwd=instruction)
        result = validate(instruction, cwd=outside, explicit_root=True)
        if result.returncode == 0 or not result.stderr.strip():
            failures.append("instruction-only unresolved placeholder: expected validation failure")
        skill_path.write_text(valid_skill, encoding="utf-8")
        (instruction / "RUNTIME.md").write_text(
            "# Unnecessary runtime contract\n", encoding="utf-8"
        )
        run(["git", "add", "-A"], cwd=instruction)
        result = validate(instruction, cwd=outside, explicit_root=True)
        if result.returncode == 0 or not result.stderr.strip():
            failures.append("instruction-only unnecessary runtime: expected validation failure")
        (instruction / "RUNTIME.md").unlink()

        script = project / ".agents/skills/example-script-skill"
        copy_root(script)
        customize(script, SCRIPT_SKILL)
        prune_to(script, {"SKILL.md"})
        (script / "scripts").mkdir(parents=True)
        (script / "scripts/normalize.py").write_text(SCRIPT_SOURCE, encoding="utf-8")
        expected = ["SKILL.md", "scripts/normalize.py"]
        actual = inventory(script)
        if actual != expected:
            failures.append(
                f"script-assisted inventory: expected {expected!r}, got {actual!r}"
            )
        if (script / "RUNTIME.md").exists():
            failures.append("script-assisted runtime: RUNTIME.md must be pruned")
        initialize_repository(script)
        for cwd, explicit_root, mode in (
            (outside, True, "external cwd"),
            (script, False, "skill cwd"),
        ):
            result = validate(script, cwd=cwd, explicit_root=explicit_root)
            if not (
                result.returncode == 0
                and result.stderr == ""
                and "Agent Skill repository structure and profile contracts are valid."
                in result.stdout
            ):
                failures.append(
                    f"script-assisted adoption {mode}: status={result.returncode!r}, "
                    f"stdout={result.stdout!r}, stderr={result.stderr!r}"
                )

        (script / "input.txt").write_bytes(b"alpha  \r\nbeta\t\r\n")
        before = (script / "input.txt").read_bytes()
        result = run(
            [sys.executable, "scripts/normalize.py", "input.txt", "output.txt"],
            cwd=script,
        )
        output = (script / "output.txt").read_bytes() if (script / "output.txt").is_file() else None
        if not (
            result.returncode == 0
            and result.stdout == "output.txt\n"
            and result.stderr == ""
            and output == b"alpha\nbeta\n"
            and (script / "input.txt").read_bytes() == before
        ):
            failures.append(
                f"script helper success: status={result.returncode!r}, stdout={result.stdout!r}, "
                f"stderr={result.stderr!r}, output={output!r}"
            )

        (script / "invalid.txt").write_bytes(b"\xff")
        result = run(
            [
                sys.executable,
                "scripts/normalize.py",
                "invalid.txt",
                "invalid-output.txt",
            ],
            cwd=script,
        )
        if not (
            result.returncode == 3
            and result.stdout == ""
            and result.stderr == "invalid UTF-8 input\n"
            and not (script / "invalid-output.txt").exists()
        ):
            failures.append(
                f"script helper failure: status={result.returncode!r}, "
                f"stdout={result.stdout!r}, stderr={result.stderr!r}"
            )

        for token in (
            "socket",
            "urllib",
            "requests",
            "pip install",
            "subprocess",
            "os.system",
            "os.exec",
        ):
            if token in SCRIPT_SOURCE:
                failures.append(f"script helper contains forbidden token {token!r}")

        (script / "scripts/undeclared.py").write_text(
            "print('undeclared')\n", encoding="utf-8"
        )
        run(["git", "add", "-A"], cwd=script)
        result = validate(script, cwd=outside, explicit_root=True)
        if result.returncode == 0 or not result.stderr.strip():
            failures.append("script-assisted undeclared helper: expected validation failure")

    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        return 1
    print("Template adoption smoke tests passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
