#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require "find"
require "open3"
require "rbconfig"
require "tmpdir"

SOURCE_ROOT = File.expand_path("../..", __dir__)
VALIDATOR = File.join(SOURCE_ROOT, ".github/scripts/validate-skill-repository.rb")

SKILL_DOCUMENT = <<~MARKDOWN.freeze
  ---
  name: portable-line-normalizer
  description: Normalize a supplied UTF-8 text file deterministically through one private helper without network access or dependency installation.
  ---

  # Portable line normalizer

  ## Purpose

  Normalize line endings and trailing horizontal whitespace without changing the source file.

  ## Use this skill when

  Use this skill when deterministic UTF-8 text normalization is required before comparison or review.

  ## Do not use this skill when

  Do not use this skill for binary input, network resources, package installation, or a public CLI compatibility contract.

  ## Required inputs and prerequisites

  A readable UTF-8 input path, a distinct writable output path, and CRuby 3.1 or newer must be available.

  ## Helper scripts

  Script: scripts/normalize.rb
  Run when: the supplied UTF-8 file must be normalized before comparison or delivery
  Exact invocation: ruby scripts/normalize.rb INPUT OUTPUT
  Working directory: skill root
  Inputs and arguments: INPUT is a readable UTF-8 file and OUTPUT is a distinct destination path
  Stdout/result: prints OUTPUT after a successful atomic write
  Stderr/diagnostics: reports invalid arguments, aliased paths, unreadable input, invalid UTF-8, or write failure
  Exit status: zero on success, 2 for invalid invocation or aliases, 3 for invalid UTF-8, and 1 for file-system failure
  Files or external state modified: writes or replaces only OUTPUT and never changes INPUT
  Network access: NONE
  Required permissions: read INPUT and write the OUTPUT directory
  Automatic execution allowed: YES
  Human confirmation required: NO
  Idempotency and retry behavior: identical input produces identical output; retry only after correcting the failure

  ## Workflow

  1. Confirm INPUT and OUTPUT are distinct.
  2. Run `ruby scripts/normalize.rb INPUT OUTPUT` from the skill root.
  3. Stop on nonzero status and report stderr.
  4. Verify the generated bytes and report OUTPUT.

  ## Output requirements

  Return the output path and whether normalization changed the text.

  ## Validation

  Confirm OUTPUT is UTF-8 with LF endings, no trailing horizontal whitespace, one final newline, and unchanged INPUT.

  ## Safety and approval

  Do not access the network, install dependencies, execute subprocesses, or write any path other than OUTPUT.

  ## Edge cases and failure handling

  Reject missing arguments, aliased paths, invalid UTF-8, and inaccessible paths without partial output.

  Selected profiles: script-assisted
MARKDOWN

HELPER_SOURCE = <<~'RUBY'.freeze
  #!/usr/bin/env ruby
  # frozen_string_literal: true

  begin
    unless ARGV.length == 2
      warn "usage: ruby scripts/normalize.rb INPUT OUTPUT"
      exit 2
    end

    input_path, output_path = ARGV
    if File.expand_path(input_path) == File.expand_path(output_path) ||
       (File.exist?(output_path) && File.identical?(input_path, output_path))
      warn "input and output must refer to different files"
      exit 2
    end

    text = File.binread(input_path).force_encoding(Encoding::UTF_8)
    unless text.valid_encoding?
      warn "invalid UTF-8 input"
      exit 3
    end

    normalized = text.gsub("\r\n", "\n").gsub("\r", "\n")
    normalized = normalized.lines.map { |line| line.sub(/[\t ]+(?=\n?\z)/, "") }.join
    normalized = "#{normalized.sub(/\n*\z/, "")}\n"
    temporary = "#{output_path}.tmp-#{Process.pid}"
    File.binwrite(temporary, normalized)
    File.rename(temporary, output_path)
    puts output_path
  rescue SystemCallError => e
    warn e.message
    exit 1
  ensure
    File.delete(temporary) if defined?(temporary) && temporary && File.exist?(temporary)
  end
RUBY

EXPECTED_FILES = %w[SKILL.md scripts/normalize.rb].freeze
FORBIDDEN_HELPER_TOKENS = [
  "Net::",
  "TCPSocket",
  "UDPSocket",
  "open-uri",
  "gem install",
  "bundle install",
  "Kernel.system",
  "Process.spawn",
  "Kernel.exec"
].freeze

failures = []

capture = lambda do |*command, chdir: nil, env: {}|
  Open3.capture3(env, *command, chdir: chdir)
end

run! = lambda do |*command, chdir: nil, env: {}|
  stdout, stderr, status = capture.call(*command, chdir: chdir, env: env)
  unless status.success?
    raise "command failed: #{command.inspect}; status=#{status.exitstatus.inspect}; stdout=#{stdout.inspect}; stderr=#{stderr.inspect}"
  end

  stdout
end

copy_canonical_root = lambda do |target|
  FileUtils.mkdir_p(target)
  Dir.children(SOURCE_ROOT).sort.each do |entry|
    next if entry == ".git"

    FileUtils.cp_r(File.join(SOURCE_ROOT, entry), File.join(target, entry), preserve: true)
  end

  skill_path = File.join(target, "SKILL.md")
  unless File.file?(skill_path) &&
         File.read(skill_path, encoding: "UTF-8").include?("Selected profiles: template-scaffold") &&
         File.file?(File.join(target, "README.md"))
    raise "copy did not originate from the canonical repository root"
  end
end

prune_to = lambda do |root, retained|
  Find.find(root).to_a.sort_by { |path| -path.count(File::SEPARATOR) }.each do |path|
    next if path == root

    relative = path.delete_prefix("#{root}/")
    keep = retained.include?(relative) || retained.any? { |candidate| candidate.start_with?("#{relative}/") }
    next if keep

    if File.directory?(path) && !File.symlink?(path)
      Dir.rmdir(path) if Dir.empty?(path)
    else
      FileUtils.rm_f(path)
    end
  end
end

materialize_source = lambda do |target|
  copy_canonical_root.call(target)
  File.write(File.join(target, "SKILL.md"), SKILL_DOCUMENT, encoding: "UTF-8")
  prune_to.call(target, ["SKILL.md"])
  FileUtils.mkdir_p(File.join(target, "scripts"))
  File.write(File.join(target, "scripts", "normalize.rb"), HELPER_SOURCE, encoding: "UTF-8")

  run!.call("git", "init", "--quiet", chdir: target)
  run!.call("git", "config", "user.name", "Installation Mode Fixture", chdir: target)
  run!.call("git", "config", "user.email", "fixture@example.invalid", chdir: target)
  run!.call("git", "add", ".", chdir: target)
  run!.call("git", "commit", "--quiet", "-m", "Create concrete skill", chdir: target)
end

inventory = lambda do |root|
  Find.find(root).filter_map do |path|
    next if path == root || File.directory?(path)

    relative = path.delete_prefix("#{root}/")
    next if relative == ".git" || relative.start_with?(".git/")

    relative
  end.sort
end

content_map = lambda do |root|
  EXPECTED_FILES.to_h do |relative|
    [relative, File.binread(File.join(root, relative))]
  end
end

mode_map = lambda do |root|
  EXPECTED_FILES.to_h do |relative|
    [relative, File.stat(File.join(root, relative)).mode & 0o777]
  end
end

validate = lambda do |target, outside|
  capture.call(
    RbConfig.ruby,
    VALIDATOR,
    target,
    chdir: outside,
    env: { "RUBYOPT" => nil }
  )
end

expect_validation_success = lambda do |label, target, outside|
  stdout, stderr, status = validate.call(target, outside)
  unless status.success? && stderr.empty? &&
         stdout.include?("Agent Skill repository structure and profile contracts are valid.")
    failures << "#{label}: expected validation success; status=#{status.exitstatus.inspect}, " \
                "stdout=#{stdout.inspect}, stderr=#{stderr.inspect}"
  end
end

expect_validation_failure = lambda do |label, target, outside, diagnostic|
  _stdout, stderr, status = validate.call(target, outside)
  if status.success?
    failures << "#{label}: expected validation failure"
  elsif !stderr.include?(diagnostic)
    failures << "#{label}: expected diagnostic #{diagnostic.inspect}; stderr=#{stderr.inspect}"
  end
end

exercise_helper = lambda do |label, target|
  input_path = File.join(target, "input.txt")
  output_path = File.join(target, "output.txt")
  File.binwrite(input_path, "alpha  \r\nbeta\t\r\n")
  before = File.binread(input_path)

  stdout, stderr, status = capture.call(
    RbConfig.ruby,
    "scripts/normalize.rb",
    "input.txt",
    "output.txt",
    chdir: target
  )
  output = File.binread(output_path) if File.file?(output_path)
  unless status.success? && stdout == "output.txt\n" && stderr.empty? &&
         output == "alpha\nbeta\n" && File.binread(input_path) == before
    failures << "#{label} helper: status=#{status.exitstatus.inspect}, stdout=#{stdout.inspect}, " \
                "stderr=#{stderr.inspect}, output=#{output.inspect}, input_unchanged=#{File.binread(input_path) == before}"
  end
end

Dir.mktmpdir("installation-mode-smoke") do |workspace|
  outside = File.join(workspace, "outside")
  source = File.join(workspace, "concrete-skill-source")
  FileUtils.mkdir_p(outside)
  materialize_source.call(source)

  clone_target = File.join(workspace, "user-home", ".agents", "skills", "clone-skill")
  FileUtils.mkdir_p(File.dirname(clone_target))
  run!.call("git", "clone", "--quiet", source, clone_target)

  submodule_project = File.join(workspace, "submodule-project")
  FileUtils.mkdir_p(submodule_project)
  run!.call("git", "init", "--quiet", chdir: submodule_project)
  run!.call("git", "config", "user.name", "Installation Mode Fixture", chdir: submodule_project)
  run!.call("git", "config", "user.email", "fixture@example.invalid", chdir: submodule_project)
  submodule_target = File.join(submodule_project, ".agents", "skills", "submodule-skill")
  run!.call(
    "git",
    "-c",
    "protocol.file.allow=always",
    "submodule",
    "add",
    "--quiet",
    source,
    ".agents/skills/submodule-skill",
    chdir: submodule_project
  )
  run!.call("git", "add", ".gitmodules", ".agents/skills/submodule-skill", chdir: submodule_project)

  archive_path = File.join(workspace, "concrete-skill.tar")
  run!.call(
    "git",
    "archive",
    "--format=tar",
    "--prefix=concrete-skill/",
    "--output=#{archive_path}",
    "HEAD",
    chdir: source
  )
  extracted = File.join(workspace, "archive-extracted")
  FileUtils.mkdir_p(extracted)
  run!.call("tar", "-xf", archive_path, "-C", extracted)
  archive_target = File.join(workspace, "archive-project", ".agents", "skills", "archive-skill")
  FileUtils.mkdir_p(archive_target)
  FileUtils.cp_r("#{File.join(extracted, 'concrete-skill')}/.", archive_target, preserve: true)

  targets = {
    "clone installation" => clone_target,
    "submodule installation" => submodule_target,
    "archive installation" => archive_target
  }

  expected_content = content_map.call(source)
  expected_modes = mode_map.call(source)
  targets.each do |label, target|
    actual_inventory = inventory.call(target)
    unless actual_inventory == EXPECTED_FILES.sort
      failures << "#{label}: expected inventory #{EXPECTED_FILES.sort.inspect}, got #{actual_inventory.inspect}"
    end
    failures << "#{label}: content differs from committed source" unless content_map.call(target) == expected_content
    failures << "#{label}: file modes differ from committed source" unless mode_map.call(target) == expected_modes
    failures << "#{label}: unexpected archive wrapper" if Dir.exist?(File.join(target, "concrete-skill"))
    expect_validation_success.call(label, target, outside)
    exercise_helper.call(label, target)
  end

  failures << "clone installation: expected a .git directory" unless File.directory?(File.join(clone_target, ".git"))
  unless File.file?(File.join(submodule_target, ".git")) &&
         File.read(File.join(submodule_target, ".git"), encoding: "UTF-8").start_with?("gitdir:")
    failures << "submodule installation: expected a .git indirection file"
  end
  submodule_index = run!.call(
    "git",
    "ls-files",
    "--stage",
    "--",
    ".agents/skills/submodule-skill",
    chdir: submodule_project
  )
  failures << "submodule installation: parent index must retain mode 160000" unless submodule_index.start_with?("160000 ")

  archive_git_stdout, archive_git_stderr, archive_git_status = capture.call(
    "git",
    "rev-parse",
    "--is-inside-work-tree",
    chdir: archive_target
  )
  if archive_git_status.success? || !archive_git_stdout.empty? || archive_git_stderr.empty?
    failures << "archive installation: expected validation target to be independent of Git metadata"
  end
  failures << "archive installation: unexpected .git metadata" if File.exist?(File.join(archive_target, ".git"))

  wrapped_target = File.join(workspace, "wrapped-project", ".agents", "skills", "wrapped-skill")
  FileUtils.mkdir_p(wrapped_target)
  FileUtils.cp_r(File.join(extracted, "concrete-skill"), wrapped_target, preserve: true)
  expect_validation_failure.call(
    "archive wrapper rejection",
    wrapped_target,
    outside,
    "Missing universally required file: SKILL.md"
  )

  targets.each do |label, target|
    undeclared = File.join(target, "scripts", "undeclared.rb")
    File.write(undeclared, "puts 'undeclared'\n", encoding: "UTF-8")
    expect_validation_failure.call(
      "#{label} undeclared resource rejection",
      target,
      outside,
      "SKILL.md must declare the exact retained resource path as 'Script: scripts/undeclared.rb'."
    )
    File.delete(undeclared)
  end

  FORBIDDEN_HELPER_TOKENS.each do |token|
    failures << "committed helper contains forbidden token #{token.inspect}" if HELPER_SOURCE.include?(token)
  end
end

unless failures.empty?
  failures.each { |failure| warn failure }
  exit 1
end

puts "Installation mode smoke tests passed."
