#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require "find"
require "open3"
require "rbconfig"
require "tmpdir"

SOURCE_ROOT = File.expand_path("../..", __dir__)
VALIDATOR = File.join(SOURCE_ROOT, ".github/scripts/validate-skill-repository.rb")

INSTRUCTION_SKILL = <<~MARKDOWN.freeze
  ---
  name: evidence-summary
  description: Summarize supplied evidence into a bounded factual result without modifying files or external systems.
  ---

  # Evidence summary

  ## Purpose

  Produce a concise summary that separates observed facts, implications, and unresolved uncertainty.

  ## Use this skill when

  Use this skill when the user supplies a bounded evidence set and requests a factual summary.

  ## Do not use this skill when

  Do not use this skill when the task requires external research, file mutation, or execution of an implementation helper.

  ## Required inputs and prerequisites

  The complete evidence set and the requested output scope must be available in the conversation.

  ## Workflow

  1. Read the supplied evidence completely.
  2. Group related facts without inventing intent or missing details.
  3. Distinguish observations, supported implications, and unresolved uncertainty.
  4. Check every statement against the supplied evidence.

  ## Output requirements

  Return a concise prose summary with explicit uncertainty where the evidence is incomplete.

  ## Validation

  Confirm that every reported fact is supported by the supplied evidence and no external state was accessed or modified.

  ## Safety and approval

  Remain read-only. Do not infer permission, hidden motivation, or facts absent from the supplied material.

  ## Edge cases and failure handling

  Stop and report the missing evidence when the supplied material is incomplete or internally inconsistent.

  Selected profiles: instruction-only
MARKDOWN

SCRIPT_SKILL = <<~MARKDOWN.freeze
  ---
  name: bounded-line-normalizer
  description: Normalize a supplied UTF-8 text file deterministically with one private helper and report the generated output path.
  ---

  # Bounded line normalizer

  ## Purpose

  Normalize line endings and trailing horizontal whitespace without changing the source file.

  ## Use this skill when

  Use this skill when a caller requests deterministic text normalization before comparison or review.

  ## Do not use this skill when

  Do not use this skill for binary input, network resources, package installation, or a public command-line compatibility contract.

  ## Required inputs and prerequisites

  A readable UTF-8 input path, a distinct writable output path, and CRuby 3.1 or newer must be available.

  ## Helper scripts

  Script: scripts/normalize.rb
  Run when: the supplied UTF-8 file must be normalized before comparison or delivery
  Exact invocation: ruby scripts/normalize.rb INPUT OUTPUT
  Working directory: skill root
  Inputs and arguments: INPUT is a readable UTF-8 file and OUTPUT is a distinct destination path
  Stdout/result: prints the caller-supplied OUTPUT path after a successful atomic write
  Stderr/diagnostics: reports invalid arguments, aliased paths, unreadable input, invalid UTF-8, or write failure
  Exit status: zero on success, 2 for invalid invocation or aliased paths, 3 for invalid UTF-8, and 1 for file-system failure
  Files or external state modified: writes or replaces only OUTPUT and never changes INPUT
  Network access: NONE
  Required permissions: read access to INPUT and write access to the OUTPUT directory
  Automatic execution allowed: YES
  Human confirmation required: NO
  Idempotency and retry behavior: identical input produces identical output; retry only after correcting the reported failure

  ## Workflow

  1. Confirm that INPUT and OUTPUT are distinct paths.
  2. Run `ruby scripts/normalize.rb INPUT OUTPUT` from the skill root.
  3. Stop on a nonzero status and report stderr without guessing.
  4. Verify the generated bytes and report OUTPUT.

  ## Output requirements

  Return the output path and whether normalization changed the text.

  ## Validation

  Confirm that OUTPUT is UTF-8, uses LF line endings, has no trailing horizontal whitespace, ends with one newline, and INPUT is unchanged.

  ## Safety and approval

  Do not access the network, install dependencies, execute subprocesses, or write any path other than OUTPUT.

  ## Edge cases and failure handling

  Reject missing arguments, identical or aliased input/output files, invalid UTF-8, and inaccessible paths without partial output.

  Selected profiles: script-assisted
MARKDOWN

SCRIPT_SOURCE = <<~RUBY.freeze
  #!/usr/bin/env ruby
  # frozen_string_literal: true

  begin
    unless ARGV.length == 2
      warn "usage: ruby scripts/normalize.rb INPUT OUTPUT"
      exit 2
    end

    input_path, output_path = ARGV
    if File.expand_path(input_path) == File.expand_path(output_path) ||
       (File.exist?(output_path) && File.identical?(input_path, output_path))
      warn "input and output must refer to different files"
      exit 2
    end

    text = File.binread(input_path).force_encoding(Encoding::UTF_8)
    unless text.valid_encoding?
      warn "invalid UTF-8 input"
      exit 3
    end

    normalized = text.gsub("\r\n", "\n").gsub("\r", "\n")
    normalized = normalized.lines.map { |line| line.sub(/[\t ]+(?=\n?\z)/, "") }.join
    normalized = "#{normalized.sub(/\n*\z/, "")}\n"

    temporary = "#{output_path}.tmp-#{Process.pid}"
    File.binwrite(temporary, normalized)
    File.rename(temporary, output_path)
    puts output_path
  rescue SystemCallError => e
    warn e.message
    exit 1
  ensure
    File.delete(temporary) if defined?(temporary) && temporary && File.exist?(temporary)
  end
RUBY

failures = []

inventory = lambda do |root|
  Find.find(root).filter_map do |path|
    next if path == root || File.directory?(path)

    relative = path.delete_prefix("#{root}/")
    next if relative == ".git" || relative.start_with?(".git/")

    relative
  end.sort
end

copy_canonical_root = lambda do |target|
  FileUtils.mkdir_p(target)
  Dir.children(SOURCE_ROOT).sort.each do |entry|
    next if entry == ".git"

    FileUtils.cp_r(File.join(SOURCE_ROOT, entry), File.join(target, entry), preserve: true)
  end

  raise "source git metadata was copied" if File.exist?(File.join(target, ".git"))
  copied_skill = File.read(File.join(target, "SKILL.md"), encoding: "UTF-8")
  unless copied_skill.include?("Selected profiles: template-scaffold") && File.file?(File.join(target, "README.md"))
    raise "copy did not originate from the canonical template root"
  end
end

prune_to = lambda do |root, retained|
  paths = Find.find(root).to_a.sort_by { |path| -path.count(File::SEPARATOR) }
  paths.each do |path|
    next if path == root

    relative = path.delete_prefix("#{root}/")
    keep = retained.include?(relative) || retained.any? { |candidate| candidate.start_with?("#{relative}/") }
    next if keep

    if File.directory?(path) && !File.symlink?(path)
      Dir.rmdir(path) if Dir.empty?(path)
    else
      FileUtils.rm_f(path)
    end
  end
end

initialize_repository = lambda do |target|
  _stdout, stderr, status = Open3.capture3("git", "init", "--quiet", chdir: target)
  raise "git init failed: #{stderr}" unless status.success?

  _stdout, stderr, status = Open3.capture3("git", "add", ".", chdir: target)
  raise "git add failed: #{stderr}" unless status.success?
end

stage_repository = lambda do |target|
  Open3.capture3("git", "add", "-A", chdir: target)
end

run_validator = lambda do |target, cwd:, explicit_root:|
  arguments = [RbConfig.ruby, VALIDATOR]
  arguments << target if explicit_root
  Open3.capture3({ "RUBYOPT" => nil }, *arguments, chdir: cwd)
end

expect_validation_success = lambda do |label, target, outside|
  [
    ["explicit target from external cwd", outside, true],
    ["legacy invocation from skill root", target, false]
  ].each do |mode, cwd, explicit_root|
    stdout, stderr, status = run_validator.call(target, cwd: cwd, explicit_root: explicit_root)
    unless status.success? && stderr.empty? && stdout.include?("Agent Skill repository structure and profile contracts are valid.")
      failures << "#{label} #{mode}: expected complete validation success; " \
                  "status=#{status.exitstatus.inspect}, stdout=#{stdout.inspect}, stderr=#{stderr.inspect}"
    end
  end
end

expect_validation_failure = lambda do |label, target, outside|
  stage_repository.call(target)
  _stdout, stderr, status = run_validator.call(target, cwd: outside, explicit_root: true)
  if status.success?
    failures << "#{label}: expected complete validation failure"
  elsif stderr.strip.empty?
    failures << "#{label}: expected an actionable diagnostic"
  end
end

Dir.mktmpdir("template-adoption-smoke") do |workspace|
  project = File.join(workspace, "project")
  outside = File.join(workspace, "external-cwd")
  FileUtils.mkdir_p(outside)

  instruction_target = File.join(project, ".agents", "skills", "example-instruction-skill")
  copy_canonical_root.call(instruction_target)
  File.write(File.join(instruction_target, "SKILL.md"), INSTRUCTION_SKILL, encoding: "UTF-8")
  prune_to.call(instruction_target, ["SKILL.md"])

  actual = inventory.call(instruction_target)
  failures << "instruction-only adoption: expected [\"SKILL.md\"], got #{actual.inspect}" unless actual == ["SKILL.md"]
  failures << "instruction-only adoption: unexpected wrapper directory" if Dir.exist?(File.join(instruction_target, "skill"))

  initialize_repository.call(instruction_target)
  expect_validation_success.call("instruction-only adoption", instruction_target, outside)

  skill_path = File.join(instruction_target, "SKILL.md")
  valid_skill = File.read(skill_path, encoding: "UTF-8")
  File.write(skill_path, valid_skill.sub("Return a concise prose summary", "TODO: Return a concise prose summary"), encoding: "UTF-8")
  expect_validation_failure.call("instruction-only adoption rejects unresolved placeholders", instruction_target, outside)
  File.write(skill_path, valid_skill, encoding: "UTF-8")

  File.write(File.join(instruction_target, "RUNTIME.md"), "# Unnecessary runtime contract\n", encoding: "UTF-8")
  expect_validation_failure.call("instruction-only adoption rejects unnecessary runtime contracts", instruction_target, outside)
  File.delete(File.join(instruction_target, "RUNTIME.md"))

  script_target = File.join(project, ".agents", "skills", "example-script-skill")
  copy_canonical_root.call(script_target)
  File.write(File.join(script_target, "SKILL.md"), SCRIPT_SKILL, encoding: "UTF-8")
  prune_to.call(script_target, ["SKILL.md"])
  FileUtils.mkdir_p(File.join(script_target, "scripts"))
  helper_path = File.join(script_target, "scripts", "normalize.rb")
  File.write(helper_path, SCRIPT_SOURCE, encoding: "UTF-8")
  FileUtils.chmod(0o755, helper_path)

  actual = inventory.call(script_target)
  expected = ["SKILL.md", "scripts/normalize.rb"]
  failures << "script-assisted adoption: expected #{expected.inspect}, got #{actual.inspect}" unless actual == expected
  failures << "script-assisted adoption: retained RUNTIME.md without a selected need" if File.exist?(File.join(script_target, "RUNTIME.md"))

  initialize_repository.call(script_target)
  expect_validation_success.call("script-assisted adoption", script_target, outside)

  input_path = File.join(script_target, "input.txt")
  output_path = File.join(script_target, "output.txt")
  File.binwrite(input_path, "alpha  \r\nbeta\t\r\n")
  before = File.binread(input_path)
  stdout, stderr, status = Open3.capture3(
    RbConfig.ruby,
    "scripts/normalize.rb",
    "input.txt",
    "output.txt",
    chdir: script_target
  )
  output = File.binread(output_path) if File.file?(output_path)
  unless status.success? && stdout == "output.txt\n" && stderr.empty? && output == "alpha\nbeta\n" && File.binread(input_path) == before
    failures << "script-assisted helper success: status=#{status.exitstatus.inspect}, stdout=#{stdout.inspect}, " \
                "stderr=#{stderr.inspect}, output=#{output.inspect}, input_unchanged=#{File.binread(input_path) == before}"
  end

  File.binwrite(File.join(script_target, "invalid.txt"), [0xFF].pack("C"))
  stdout, stderr, status = Open3.capture3(
    RbConfig.ruby,
    "scripts/normalize.rb",
    "invalid.txt",
    "invalid-output.txt",
    chdir: script_target
  )
  unless status.exitstatus == 3 && stdout.empty? && stderr == "invalid UTF-8 input\n" &&
         !File.exist?(File.join(script_target, "invalid-output.txt"))
    failures << "script-assisted helper failure: status=#{status.exitstatus.inspect}, stdout=#{stdout.inspect}, stderr=#{stderr.inspect}"
  end

  forbidden_helper_tokens = ["Net::", "TCPSocket", "UDPSocket", "open-uri", "gem install", "bundle install", "Kernel.system", "Process.spawn", "Kernel.exec"]
  forbidden_helper_tokens.each do |token|
    failures << "script-assisted helper contains forbidden network/install/process token #{token.inspect}" if SCRIPT_SOURCE.include?(token)
  end

  File.write(File.join(script_target, "scripts", "undeclared.rb"), "puts 'undeclared'\n", encoding: "UTF-8")
  expect_validation_failure.call("script-assisted adoption rejects undeclared helpers", script_target, outside)
end

unless failures.empty?
  failures.each { |failure| warn failure }
  exit 1
end

puts "Template adoption smoke tests passed."
