#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require "open3"
require "rbconfig"
require "tmpdir"

SOURCE_ROOT = File.expand_path("../..", __dir__)
VALIDATOR = File.join(SOURCE_ROOT, ".github/scripts/validate-skill-repository.rb")
SKILL_FILES = %w[SKILL.md scripts/normalize.rb].freeze
FAILURES = []

SKILL_DOCUMENT = <<~MARKDOWN.freeze
  ---
  name: parent-owned-line-normalizer
  description: Normalize a supplied UTF-8 text file deterministically through one private helper without network access or dependency installation.
  ---

  # Parent-owned line normalizer

  ## Purpose

  Normalize line endings and trailing horizontal whitespace without changing the source file.

  ## Use this skill when

  Use this skill when deterministic UTF-8 text normalization is required before comparison or review.

  ## Do not use this skill when

  Do not use this skill for binary input, network resources, package installation, or a public CLI compatibility contract.

  ## Required inputs and prerequisites

  A readable UTF-8 input path, a distinct writable output path, and CRuby 3.1 or newer must be available.

  ## Helper scripts

  Script: scripts/normalize.rb
  Run when: the supplied UTF-8 file must be normalized before comparison or delivery
  Exact invocation: ruby scripts/normalize.rb INPUT OUTPUT
  Working directory: skill root
  Inputs and arguments: INPUT is a readable UTF-8 file and OUTPUT is a distinct destination path
  Stdout/result: prints OUTPUT after a successful atomic write
  Stderr/diagnostics: reports invalid arguments, aliased paths, unreadable input, invalid UTF-8, or write failure
  Exit status: zero on success, 2 for invalid invocation or aliases, 3 for invalid UTF-8, and 1 for file-system failure
  Files or external state modified: writes or replaces only OUTPUT and never changes INPUT
  Network access: NONE
  Required permissions: read INPUT and write the OUTPUT directory
  Automatic execution allowed: YES
  Human confirmation required: NO
  Idempotency and retry behavior: identical input produces identical output; retry only after correcting the failure

  ## Workflow

  1. Confirm INPUT and OUTPUT are distinct.
  2. Run `ruby scripts/normalize.rb INPUT OUTPUT` from the skill root.
  3. Stop on nonzero status and report stderr.
  4. Verify the generated bytes and report OUTPUT.

  ## Output requirements

  Return the output path and whether normalization changed the text.

  ## Validation

  Confirm OUTPUT is UTF-8 with LF endings, no trailing horizontal whitespace, one final newline, and unchanged INPUT.

  ## Safety and approval

  Do not access the network, install dependencies, execute subprocesses, or write any path other than OUTPUT.

  ## Edge cases and failure handling

  Reject missing arguments, aliased paths, invalid UTF-8, and inaccessible paths without partial output.

  Selected profiles: script-assisted
MARKDOWN

HELPER_SOURCE = <<~'RUBY'.freeze
  #!/usr/bin/env ruby
  # frozen_string_literal: true

  begin
    unless ARGV.length == 2
      warn "usage: ruby scripts/normalize.rb INPUT OUTPUT"
      exit 2
    end

    input_path, output_path = ARGV
    if File.expand_path(input_path) == File.expand_path(output_path) ||
       (File.exist?(output_path) && File.identical?(input_path, output_path))
      warn "input and output must refer to different files"
      exit 2
    end

    text = File.binread(input_path).force_encoding(Encoding::UTF_8)
    unless text.valid_encoding?
      warn "invalid UTF-8 input"
      exit 3
    end

    normalized = text.gsub("\r\n", "\n").gsub("\r", "\n")
    normalized = normalized.lines.map { |line| line.sub(/[\t ]+(?=\n?\z)/, "") }.join
    normalized = "#{normalized.sub(/\n*\z/, "")}\n"
    temporary = "#{output_path}.tmp-#{Process.pid}"
    File.binwrite(temporary, normalized)
    File.rename(temporary, output_path)
    puts output_path
  rescue SystemCallError => e
    warn e.message
    exit 1
  ensure
    File.delete(temporary) if defined?(temporary) && temporary && File.exist?(temporary)
  end
RUBY

def capture(*command, chdir:, env: {})
  Open3.capture3(env, *command, chdir: chdir)
end

def run!(*command, chdir:, env: {})
  stdout, stderr, status = capture(*command, chdir: chdir, env: env)
  return stdout if status.success?

  raise "command failed: #{command.inspect}; status=#{status.exitstatus.inspect}; " \
        "stdout=#{stdout.inspect}; stderr=#{stderr.inspect}"
end

def validate(target, outside)
  capture(
    RbConfig.ruby,
    VALIDATOR,
    target,
    chdir: outside,
    env: { "RUBYOPT" => nil }
  )
end

def expect_validation_success(target, outside)
  stdout, stderr, status = validate(target, outside)
  return if status.success? && stderr.empty? &&
            stdout.include?("Agent Skill repository structure and profile contracts are valid.")

  FAILURES << "expected parent-owned vendored skill validation success; " \
              "status=#{status.exitstatus.inspect}, stdout=#{stdout.inspect}, stderr=#{stderr.inspect}"
end

def expect_gitlink_rejection(target, outside)
  _stdout, stderr, status = validate(target, outside)
  diagnostic = "Operational resource gitlinks are not allowed: scripts/index-only-link"
  if status.success?
    FAILURES << "expected parent-index gitlink rejection"
  elsif !stderr.include?(diagnostic)
    FAILURES << "expected diagnostic #{diagnostic.inspect}; stderr=#{stderr.inspect}"
  end
end

def git_index_bytes(repository)
  index_path = run!("git", "rev-parse", "--git-path", "index", chdir: repository).strip
  index_path = File.expand_path(index_path, repository) unless index_path.start_with?(File::SEPARATOR)
  File.binread(index_path)
end

def tracked_skill_entries(repository, prefix)
  output = run!("git", "ls-files", "--stage", "--", prefix, chdir: repository)
  output.lines.to_h do |line|
    match = line.match(/\A(\d+)\s+[0-9a-f]+\s+\d+\t(.+)\n?\z/)
    raise "unexpected git ls-files record: #{line.inspect}" unless match

    [match[2], match[1]]
  end
end

def content_map(root)
  SKILL_FILES.to_h { |relative| [relative, File.binread(File.join(root, relative))] }
end

def exercise_helper(target)
  input_path = File.join(target, "input.txt")
  output_path = File.join(target, "output.txt")
  File.binwrite(input_path, "alpha  \r\nbeta\t\r\n")
  before = File.binread(input_path)

  stdout, stderr, status = capture(
    RbConfig.ruby,
    "scripts/normalize.rb",
    "input.txt",
    "output.txt",
    chdir: target
  )
  output = File.binread(output_path) if File.file?(output_path)
  return if status.success? && stdout == "output.txt\n" && stderr.empty? &&
            output == "alpha\nbeta\n" && File.binread(input_path) == before

  FAILURES << "helper execution failed; status=#{status.exitstatus.inspect}, " \
              "stdout=#{stdout.inspect}, stderr=#{stderr.inspect}, output=#{output.inspect}"
end

Dir.mktmpdir("parent-owned-vendoring") do |workspace|
  outside = File.join(workspace, "outside")
  source = File.join(workspace, "concrete-skill-source")
  archive = File.join(workspace, "concrete-skill.tar")
  extracted = File.join(workspace, "archive-extracted")
  parent = File.join(workspace, "parent-project")
  skill_prefix = ".agents/skills/parent-owned-line-normalizer"
  target = File.join(parent, skill_prefix)

  FileUtils.mkdir_p([outside, File.join(source, "scripts"), extracted, parent])
  File.write(File.join(source, "SKILL.md"), SKILL_DOCUMENT, encoding: "UTF-8")
  File.write(File.join(source, "scripts", "normalize.rb"), HELPER_SOURCE, encoding: "UTF-8")

  run!("git", "init", "--quiet", chdir: source)
  run!("git", "config", "user.name", "Parent-owned Vendoring Fixture", chdir: source)
  run!("git", "config", "user.email", "fixture@example.invalid", chdir: source)
  run!("git", "add", ".", chdir: source)
  run!("git", "commit", "--quiet", "-m", "Create concrete skill", chdir: source)
  run!(
    "git", "archive", "--format=tar", "--prefix=parent-owned-line-normalizer/",
    "--output=#{archive}", "HEAD",
    chdir: source
  )
  run!("tar", "-xf", archive, "-C", extracted, chdir: workspace)

  run!("git", "init", "--quiet", chdir: parent)
  run!("git", "config", "user.name", "Parent Project Fixture", chdir: parent)
  run!("git", "config", "user.email", "parent@example.invalid", chdir: parent)
  File.write(File.join(parent, "README.md"), "# Parent project\n", encoding: "UTF-8")
  run!("git", "add", "README.md", chdir: parent)
  run!("git", "commit", "--quiet", "-m", "Create parent project", chdir: parent)

  FileUtils.mkdir_p(target)
  FileUtils.cp_r(
    "#{File.join(extracted, 'parent-owned-line-normalizer')}/.",
    target,
    preserve: true
  )
  run!("git", "add", "--", skill_prefix, chdir: parent)
  run!("git", "commit", "--quiet", "-m", "Vendor concrete skill", chdir: parent)

  expected_paths = SKILL_FILES.to_h do |relative|
    [File.join(skill_prefix, relative), "100644"]
  end
  actual_entries = tracked_skill_entries(parent, skill_prefix)
  FAILURES << "parent index does not own the expected regular files: #{actual_entries.inspect}" \
    unless actual_entries == expected_paths

  FAILURES << "vendored bytes differ from the committed source" \
    unless content_map(target) == content_map(source)
  FAILURES << "vendored target unexpectedly contains Git metadata" \
    if File.exist?(File.join(target, ".git"))
  FAILURES << "vendored target retained an archive wrapper" \
    if Dir.exist?(File.join(target, "parent-owned-line-normalizer"))

  discovered_root = run!("git", "rev-parse", "--show-toplevel", chdir: target).strip
  FAILURES << "validator target did not discover the parent worktree" \
    unless File.expand_path(discovered_root) == File.expand_path(parent)

  index_before = git_index_bytes(parent)
  expect_validation_success(target, outside)
  index_after = git_index_bytes(parent)
  FAILURES << "successful validation modified the parent index" unless index_after == index_before
  exercise_helper(target)

  parent_head = run!("git", "rev-parse", "HEAD", chdir: parent).strip
  gitlink_path = File.join(skill_prefix, "scripts", "index-only-link")
  run!(
    "git", "update-index", "--add", "--cacheinfo",
    "160000,#{parent_head},#{gitlink_path}",
    chdir: parent
  )
  FAILURES << "index-only gitlink unexpectedly exists on the filesystem" \
    if File.exist?(File.join(parent, gitlink_path))

  gitlink_index_before = git_index_bytes(parent)
  expect_gitlink_rejection(target, outside)
  gitlink_index_after = git_index_bytes(parent)
  FAILURES << "failed validation modified the parent index" \
    unless gitlink_index_after == gitlink_index_before
end

unless FAILURES.empty?
  FAILURES.each { |failure| warn failure }
  exit 1
end

puts "Parent-owned vendoring smoke tests passed."
