#!/usr/bin/env python3
# agent-policy-generated: true
# source-skill: maintain-progressive-discovery
# DO NOT EDIT DIRECTLY
"""Safely plan and validate semantic ``index.md`` discovery boundaries."""

from __future__ import annotations

import argparse
import ctypes
import hashlib
import json
import os
import posixpath
import re
import secrets
import stat
import string
import subprocess
from collections.abc import Callable, Iterable
from contextlib import ExitStack
from html.parser import HTMLParser
from pathlib import Path
from typing import Any
from urllib.parse import quote, unquote, urlsplit

INDEX_NAME = "index.md"
ADAPTER_NAME = ".progressive-discovery.json"
POLICY_NAME = ".agent-policy.yml"
POLICY_SCHEMA_JSON = "{{ canonical_policy_schema_json }}"
GENERATED_MARKER = "<!-- generated by maintain-progressive-discovery -->"
IGNORED_DIRECTORIES = {
    ".git",
    ".hg",
    ".svn",
    ".venv",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    "node_modules",
}
PATH_KEYS = {
    "path",
    "source",
    "destination",
    "target",
    "file",
    "filename",
    "document",
    "document_path",
    "source_path",
    "destination_path",
    "url_path",
}
PATH_SUFFIXES = (
    ".md",
    ".markdown",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
    ".py",
    ".schema",
)
LINK_RE = re.compile(r"(?<!!)\[([^\]]+)\]\(([^)]+)\)")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$")


def _relative(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def _safe_relative(value: str) -> str | None:
    value = value.strip().replace("\\", "/")
    if not value or value.startswith(("/", "\\")):
        return None
    try:
        parsed = urlsplit(value)
    except ValueError:
        return None
    if parsed.scheme or parsed.netloc:
        return None
    path = unquote(parsed.path)
    normalized = posixpath.normpath(path)
    if normalized in ("", ".") or normalized == ".." or normalized.startswith("../"):
        return None
    return normalized


def _ignored(path: Path, root: Path) -> bool:
    try:
        parts = path.relative_to(root).parts
    except ValueError:
        return True
    return any(
        part in IGNORED_DIRECTORIES or part.startswith(".") and part != ".well-known"
        for part in parts
    )


def _walk_files(root: Path) -> Iterable[Path]:
    for directory, dirnames, filenames in os.walk(root, followlinks=False):
        current = Path(directory)
        dirnames[:] = sorted(
            name
            for name in dirnames
            if name not in IGNORED_DIRECTORIES
            and not name.startswith(".")
            and not (current / name).is_symlink()
        )
        for name in sorted(filenames):
            path = current / name
            if path.is_symlink() or _ignored(path, root):
                continue
            yield path


def _read_json(path: Path) -> Any:
    def unique_members(pairs):
        result = {}
        for key, value in pairs:
            if key in result:
                raise ValueError(f"duplicate JSON member: {key}")
            result[key] = value
        return result
    return json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=unique_members)


def _read_yaml(path: Path) -> Any:
    import yaml

    class UniqueLoader(yaml.SafeLoader):
        def construct_mapping(self, node, deep=False):
            self.flatten_mapping(node)
            seen = set()
            for key_node, _ in node.value:
                key = self.construct_object(key_node, deep=deep)
                if key in seen:
                    raise ValueError(f"duplicate YAML member: {key}")
                seen.add(key)
            return super().construct_mapping(node, deep=deep)

    return yaml.load(path.read_text(encoding="utf-8"), Loader=UniqueLoader)


def _read_inventory(path: Path) -> tuple[Any, list[str]]:
    try:
        if path.suffix.lower() == ".json":
            return _read_json(path), []
        if path.suffix.lower() in {".yaml", ".yml"}:
            try:
                import yaml  # type: ignore  # noqa: F401
            except ImportError:
                return {}, [f"inventory {path}: PyYAML unavailable; YAML inventory was not read"]
            return _read_yaml(path) or {}, []
    except (OSError, UnicodeError, ValueError) as exc:
        return {}, [f"inventory {path}: {exc}"]
    except Exception as exc:  # pragma: no cover - parser-specific defensive path
        return {}, [f"inventory {path}: {exc}"]
    return {}, [f"inventory {path}: unsupported inventory format"]


def _has_generated_marker(content: str | bytes) -> bool:
    data = content.encode("utf-8") if isinstance(content, str) else content
    return data.partition(b"\n")[0] == GENERATED_MARKER.encode("utf-8")


def _repository_path_error(root: Path, relative: str) -> str | None:
    if (_safe_relative(relative) != relative or "\x00" in relative
            or ".git" in Path(relative).parts):
        return f"unsafe repository-relative target: {relative}"
    current = root
    for part in Path(relative).parts:
        current = current / part
        if current.is_symlink():
            return f"symlink in repository target: {relative}"
    return None


def _git_revision(root: Path) -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unresolved"


def _git_dirty(root: Path) -> bool | None:
    try:
        return bool(
            subprocess.check_output(
                ["git", "-C", str(root), "status", "--porcelain=v1"],
                text=True,
                stderr=subprocess.DEVNULL,
            ).strip()
        )
    except (OSError, subprocess.CalledProcessError):
        return None


def _load_adapter(root: Path, relative: str) -> tuple[dict[str, Any], list[str]]:
    if problem := _repository_path_error(root, relative):
        return {}, [f"adapter: {problem}"]
    path = root / relative
    if not path.exists() and not path.is_symlink():
        return {}, []
    if not path.is_file() or path.is_symlink():
        return {}, ["adapter: must be a regular file"]
    try:
        value = _read_json(path)
    except (OSError, UnicodeError, ValueError) as exc:
        return {}, [f"adapter: {exc}"]
    if not isinstance(value, dict):
        return {}, ["adapter: root must be an object"]
    errors: list[str] = []
    for key in ("expected_documents", "authoritative_inventories", "authored_boundaries",
                "explicit_exclusions", "closed_inventories", "curated_shortcuts",
                "intentional_no_indexes", "remove_generated_indexes"):
        if key in value:
            paths = value[key]
            if not isinstance(paths, (list, dict)) or any(
                not isinstance(item, str) or not item.strip() for item in paths
            ):
                errors.append(f"adapter: {key} must declare nonempty path strings")
    for key in ("authored_boundaries", "explicit_exclusions", "closed_inventories",
                "curated_shortcuts", "intentional_no_indexes"):
        declarations = value.get(key, [])
        if isinstance(declarations, (list, dict)):
            for path in declarations:
                if (not isinstance(path, str)
                        or _repository_path_error(root, path.removesuffix("/"))):
                    errors.append(f"adapter: {key} requires canonical repository paths: {path}")
    if "generated_indexes" in value:
        specs = value["generated_indexes"]
        valid = isinstance(specs, dict) and all(
            isinstance(spec, dict) for spec in specs.values()
        ) or isinstance(specs, list) and all(
            isinstance(spec, str) or isinstance(spec, dict) and isinstance(spec.get("path"), str)
            for spec in specs
        )
        if not valid:
            errors.append("adapter: generated_indexes must declare paths and specification objects")
    if "expected_documents" in value and not isinstance(value["expected_documents"], list):
        errors.append("adapter: expected_documents must be an array")
    root_index = value.get("root_index", INDEX_NAME)
    if (not isinstance(root_index, str) or _repository_path_error(root, root_index)
            or Path(root_index).name != INDEX_NAME):
        errors.append("adapter: root_index must be a canonical index.md path")
    generated = _generated_specs(value)
    if "publication_system" in value and type(value["publication_system"]) is not bool:
        errors.append("adapter: publication_system must be a JSON boolean")
    surfaces = value.get("surface_boundaries", {})
    if not isinstance(surfaces, dict):
        errors.append("adapter: surface_boundaries must be a mapping")
    else:
        for name, declaration in surfaces.items():
            if not isinstance(name, str) or not name.strip():
                errors.append("adapter: surface boundary names must be nonempty text")
            if isinstance(declaration, dict):
                # Authority-owned descriptive relations may reference another
                # authority or deployed output; they do not assert local paths.
                if (set(declaration) != {"source", "consumer"}
                        or any(not isinstance(text, str) or not text.strip()
                               for text in declaration.values())):
                    errors.append(f"adapter: invalid descriptive surface relation: {name}")
            elif isinstance(declaration, list):
                for entry in declaration:
                    if not isinstance(entry, str):
                        errors.append(f"adapter: surface paths must be strings: {name}")
                        continue
                    relative = entry.removesuffix("/")
                    if problem := _repository_path_error(root, relative):
                        errors.append(f"adapter: surface {name}: {problem}")
                        continue
                    path = root / relative
                    planned = relative in generated or any(
                        target.startswith(relative + "/") for target in generated
                    )
                    if relative in generated and entry.endswith("/"):
                        errors.append(f"adapter: generated file is declared as a directory: {entry}")
                    elif not path.exists() and not planned:
                        errors.append(f"adapter: missing local surface path: {relative}")
                    elif path.exists() and (not path.is_file() and not path.is_dir()
                                            or entry.endswith("/") and not path.is_dir()):
                        errors.append(f"adapter: invalid local surface path kind: {relative}")
            else:
                errors.append(f"adapter: surface must declare local paths or a relation: {name}")
    for target, spec in generated.items():
        allowed = {"title", "section", "inventory"}
        if isinstance(value.get("generated_indexes"), list):
            allowed.add("path")
        if unknown := set(spec) - allowed:
            errors.append(f"adapter: unsupported generated specification fields: {target}: "
                          + ", ".join(sorted(unknown)))
        for heading in ("title", "section"):
            if heading in spec and (
                not isinstance(spec[heading], str) or not spec[heading].strip()
            ):
                errors.append(f"adapter: generated {heading} must be nonempty text: {target}")
        if "inventory" in spec:
            scopes = spec["inventory"]
            if not isinstance(scopes, list) or any(
                not isinstance(scope, str) or not scope
                or _repository_path_error(root, scope.removesuffix("/"))
                for scope in scopes
            ):
                errors.append(
                    f"adapter: generated inventory requires canonical path array: {target}"
                )
    retired = _configured_paths(value, "remove_generated_indexes")
    if isinstance(root_index, str) and root_index in retired:
        errors.append("adapter: active root_index cannot be retired")
    retired_declarations = value.get("remove_generated_indexes", [])
    if not isinstance(retired_declarations, (list, dict)):
        retired_declarations = []
    for target in retired_declarations:
        if isinstance(target, str) and _repository_path_error(root, target):
            errors.append(f"adapter: retired target is not canonical: {target}")
    excluded_boundaries = _configured_paths(value, "explicit_exclusions") | _configured_paths(
        value, "closed_inventories"
    )
    active_indexes = set(generated) | ({root_index} if isinstance(root_index, str) else set())
    no_indexes = _configured_paths(value, "intentional_no_indexes")
    for target in active_indexes:
        if any(other.startswith(target + "/") for other in active_indexes):
            errors.append(f"adapter: active index file cannot contain another index: {target}")
        # These directories are excluded by the canonical discovery walk.
        if (_ignored(root / target, root)
                or any(part.startswith(".") for part in Path(target).parent.parts)
                or (posixpath.dirname(target) or ".") in no_indexes):
            errors.append(f"adapter: active index is inside a no-index boundary: {target}")
    for target in active_indexes | retired:
        if any(target == boundary or target.startswith(boundary + "/")
               for boundary in excluded_boundaries):
            errors.append(
                f"adapter: active root/generated/retired target overlaps excluded boundary: {target}"
            )
        if _repository_path_error(root, target) or Path(target).name != INDEX_NAME:
            errors.append(
                f"adapter: generated/retired target must be a safe index.md path: {target}"
            )
    for target in set(generated) & retired:
        errors.append(f"adapter: target is both active and retired: {target}")
    if isinstance(value.get("generated_indexes"), list):
        paths = [item if isinstance(item, str) else item.get("path")
                 for item in value["generated_indexes"]
                 if isinstance(item, str) or isinstance(item, dict)
                 and isinstance(item.get("path"), str)]
        if len(paths) != len(set(paths)):
            errors.append("adapter: duplicate generated target declarations")
    exclusions = value.get("authored_index_exclusions", {})
    if not isinstance(exclusions, dict):
        errors.append("adapter: authored_index_exclusions must be an object")
        value["authored_index_exclusions"] = {}
    else:
        for index, documents in exclusions.items():
            if (_repository_path_error(root, index) or Path(index).name != INDEX_NAME
                    or index == root_index or index in generated or not (root / index).is_file()):
                errors.append(
                    f"adapter: scoped exclusion requires an existing authored index: {index}"
                )
            if not isinstance(documents, dict):
                errors.append(
                    f"adapter: scoped exclusions require document/reason mappings: {index}"
                )
                exclusions[index] = {}
                continue
            for document, reason in documents.items():
                if (_repository_path_error(root, document)
                        or not isinstance(reason, str) or not reason.strip()):
                    errors.append(f"adapter: invalid scoped exclusion for {index}: {document}")
    return ({} if errors else value), errors


def _policy_schema() -> dict[str, Any]:
    # Policy render embeds its canonical schema; source execution reads that
    # same source file. Installed consumers do not provide a schema override.
    if POLICY_SCHEMA_JSON.startswith("{{"):
        return _read_json(Path(__file__).resolve().parents[3] / "schemas/agent-policy.schema.json")
    return json.loads(POLICY_SCHEMA_JSON)


def _yaml_policy(root: Path, relative: str) -> tuple[Any, list[str]]:
    if problem := _repository_path_error(root, relative):
        return {}, [f"policy: {problem}"]
    path = root / relative
    if not path.is_file():
        return {}, []
    try:
        import yaml  # type: ignore  # noqa: F401

        from jsonschema import Draft202012Validator

        value = _read_yaml(path)
        Draft202012Validator(_policy_schema()).validate(value)
        return value, []
    except ImportError as exc:
        return {}, [f"policy: required validator unavailable: {exc}"]
    except Exception as exc:  # pragma: no cover - parser-specific defensive path
        return {}, [f"policy: {exc}"]


def _find_values(value: Any, key: str | None = None) -> Iterable[str]:
    if key in {"destination", "destination_path", "url_path"}:
        return
    if isinstance(value, str):
        candidate = _safe_relative(value)
        if (key in PATH_KEYS or value.strip().lower().endswith(PATH_SUFFIXES)
                or candidate is not None and candidate.lower().endswith(PATH_SUFFIXES)):
            yield value
        return
    if isinstance(value, list):
        for item in value:
            yield from _find_values(item, key)
        return
    if isinstance(value, dict):
        for child_key, child in value.items():
            yield from _find_values(child, str(child_key).lower())


def _path_candidate(root: Path, raw: str) -> str | None:
    candidate = _safe_relative(raw)
    if candidate is None or candidate == INDEX_NAME:
        return None
    if candidate.startswith("http:") or candidate.startswith("https:"):
        return None
    if not candidate.lower().endswith(PATH_SUFFIXES):
        return None
    path = root / candidate
    if _ignored(path, root):
        return None
    return candidate


def _explicit_inventory_paths(root: Path, adapter: dict[str, Any]) -> list[str]:
    raw = adapter.get("authoritative_inventories", [])
    if not isinstance(raw, list):
        return []
    result: list[str] = []
    for item in raw:
        if isinstance(item, str):
            path = _safe_relative(item)
            if path:
                result.append(path)
    return sorted(set(result))


def _discover_inventory_paths(root: Path, adapter: dict[str, Any]) -> list[str]:
    explicit = _explicit_inventory_paths(root, adapter)
    if "authoritative_inventories" in adapter:
        return explicit
    pattern = re.compile(
        r"(?:catalog|manifest|inventory|registry|publication|documentation|site-discovery|feature-registry)",
        re.IGNORECASE,
    )
    paths: list[str] = []
    for path in _walk_files(root):
        if path.suffix.lower() not in {".json", ".yaml", ".yml"}:
            continue
        if pattern.search(path.name):
            paths.append(_relative(path, root))
    return sorted(paths)


def _expected_documents(
    root: Path, adapter: dict[str, Any], inventories: list[str]
) -> tuple[list[str], list[str]]:
    expected: set[str] = set()
    errors: list[str] = []
    if "authoritative_inventories" in adapter:
        declarations = adapter["authoritative_inventories"]
        if not isinstance(declarations, list) or any(
            not isinstance(item, str) or _safe_relative(item) != item
            for item in declarations
        ):
            errors.append("authoritative_inventories: require canonical repository-relative paths")
    namespaces = adapter.get("inventory_path_namespaces", {})
    if not isinstance(namespaces, dict) or any(
        key not in inventories or value not in ("repository", "external", "deployment")
        for key, value in namespaces.items()
    ):
        errors.append("inventory_path_namespaces: require declared inventory and known namespace")
        namespaces = {}
    for relative in inventories:
        path = root / relative
        problem = _repository_path_error(root, relative)
        if problem:
            errors.append(problem)
            continue
        value, notes = _read_inventory(path)
        errors.extend(notes)
        if notes:
            continue
        if namespaces.get(relative, "repository") != "repository":
            continue
        for raw in _find_values(value):
            # Absolute network references are not repository documents. Local
            # declarations must be canonical before any suffix/filter decision.
            if raw.startswith(("https://", "http://", "mailto:")):
                continue
            if problem := _repository_path_error(root, raw):
                errors.append(f"inventory {relative}: {problem}")
                continue
            candidate = _path_candidate(root, raw)
            if candidate:
                expected.add(candidate)
    raw_expected = adapter.get("expected_documents", [])
    if isinstance(raw_expected, list):
        for item in raw_expected:
            if isinstance(item, str):
                if problem := _repository_path_error(root, item):
                    errors.append(f"expected_documents: {problem}")
                else:
                    expected.add(item)
    excluded = _configured_paths(adapter, "explicit_exclusions") | _configured_paths(
        adapter, "closed_inventories"
    )
    expected = {
        item
        for item in expected
        if not any(item == prefix or item.startswith(prefix + "/") for prefix in excluded)
    }
    for item in expected:
        if problem := _repository_path_error(root, item):
            errors.append(problem)
    return sorted(expected), errors


def _configured_paths(adapter: dict[str, Any], key: str) -> set[str]:
    raw = adapter.get(key, [])
    if isinstance(raw, dict):
        raw = list(raw)
    if not isinstance(raw, list):
        return set()
    return {value.rstrip("/") for value in raw if isinstance(value, str) and value.strip()}


def _generated_specs(adapter: dict[str, Any]) -> dict[str, dict[str, Any]]:
    raw = adapter.get("generated_indexes", {})
    result: dict[str, dict[str, Any]] = {}
    if isinstance(raw, dict):
        for path, value in raw.items():
            if isinstance(path, str):
                result[path] = value if isinstance(value, dict) else {}
    elif isinstance(raw, list):
        for value in raw:
            if isinstance(value, str):
                result[value] = {}
            elif isinstance(value, dict) and isinstance(value.get("path"), str):
                result[value["path"]] = value
    return result


def _policy_state(policy: Any) -> dict[str, Any]:
    profiles: list[str] = []
    selected_skills: list[str] = []

    # Keep the normal path explicit so a context's profiles and skills.enabled
    # are not confused with unrelated strings in the configuration.
    if isinstance(policy, dict):
        contexts = policy.get("contexts")
        if isinstance(contexts, dict):
            for context in contexts.values():
                if isinstance(context, dict) and isinstance(context.get("profiles"), list):
                    profiles.extend(item for item in context["profiles"] if isinstance(item, str))
        skills = policy.get("skills")
        if isinstance(skills, dict) and isinstance(skills.get("enabled"), list):
            selected_skills.extend(item for item in skills["enabled"] if isinstance(item, str))
    return {
        "profile_selected": "progressive-discovery" in profiles,
        "skill_selected": "maintain-progressive-discovery" in selected_skills,
        "profiles": sorted(set(profiles)),
        "skills": sorted(set(selected_skills)),
    }


def _index_paths(root: Path, adapter: dict[str, Any]) -> list[str]:
    excluded = _configured_paths(adapter, "explicit_exclusions") | _configured_paths(
        adapter, "closed_inventories"
    )
    return sorted(
        _relative(path, root)
        for path in _walk_files(root)
        if path.name == INDEX_NAME
        and not any(
            _relative(path, root) == prefix or _relative(path, root).startswith(prefix + "/")
            for prefix in excluded
        )
    )


def _rendered_blocks(text: str) -> str:
    """Exclude comments and code blocks from the supported Markdown surfaces."""
    text = re.sub(r"<!--.*?(?:-->|$)", lambda match: "\n" * match.group().count("\n"),
                  text, flags=re.DOTALL)
    visible: list[str] = []
    fence = ""
    for line in text.splitlines():
        marker = re.match(r"^ {0,3}(`{3,}|~{3,})(.*)$", line)
        if fence:
            if (marker and marker.group(1)[0] == fence[0]
                    and len(marker.group(1)) >= len(fence)
                    and not marker.group(2).strip()):
                fence = ""
            visible.append("")
            continue
        if marker:
            fence = marker.group(1)
            visible.append("")
            continue
        if line.expandtabs(4).startswith("    "):
            visible.append("")
            continue
        visible.append(line)
    return "\n".join(visible)


def _without_code_spans(text: str) -> str:
    return re.sub(r"(`+).*?\1", "", text, flags=re.DOTALL)


def _read_index_links(root: Path, relative: str) -> tuple[list[dict[str, str]], list[str]]:
    if problem := _repository_path_error(root, relative):
        return [], [problem]
    path = root / relative
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        return [], [f"{relative}: {exc}"]
    links: list[dict[str, str]] = []
    issues: list[str] = []
    rendered = _rendered_blocks(text)
    lines = rendered.splitlines()
    nonblank = [
        (index, line)
        for index, line in enumerate(lines, 1)
        if line.strip() and line.strip() != GENERATED_MARKER
    ]
    if not nonblank or not nonblank[0][1].startswith("# "):
        issues.append(f"{relative}: first nonblank line must be a level-1 heading")
    if any(line.startswith("# ") for index, line in nonblank[1:]):
        issues.append(f"{relative}: authored grammar permits only one level-1 heading")
    for line_number, line in nonblank:
        if line.startswith("#") and not HEADING_RE.match(line):
            issues.append(f"{relative}:{line_number}: malformed heading")
        if line.startswith(("- ", "* ")) and "[" not in line:
            issues.append(f"{relative}:{line_number}: list item must contain a Markdown link")
        if not line.startswith(("#", "- ", "* ", "  ")) and not LINK_RE.search(line):
            issues.append(f"{relative}:{line_number}: content is outside the small index grammar")
    navigation_text = _without_code_spans(rendered)
    for match in LINK_RE.finditer(navigation_text):
        label, target = match.groups()
        links.append({"label": label.strip(), "target": target.strip()})
    return links, issues


def _heading_slug(value: str) -> str:
    value = re.sub(r"[`*_~]", "", value.lower())
    value = re.sub(r"[^a-z0-9\u0080-\uffff -]", "", value)
    return re.sub(r"\s+", "-", value.strip())


def _headings(path: Path) -> set[str]:
    try:
        lines = _rendered_blocks(path.read_text(encoding="utf-8")).splitlines()
    except (OSError, UnicodeError):
        return set()
    headings: set[str] = set()
    paragraph: list[str] = []
    for line in lines:
        if match := HEADING_RE.match(line):
            headings.add(_heading_slug(match.group(2)))
            paragraph = []
        elif re.fullmatch(r" {0,3}(?:=+|-+)[ \t]*", line) and paragraph:
            headings.add(_heading_slug(" ".join(paragraph)))
            paragraph = []
        elif line.strip() and not line.lstrip().startswith(("<", "- ", "* ", ">")):
            paragraph.append(line.strip())
        else:
            paragraph = []
    return headings


def _anchors(path: Path) -> set[str]:
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return set()
    class AnchorParser(HTMLParser):
        def __init__(self) -> None:
            super().__init__()
            self.anchors: set[str] = set()

        def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
            for key, value in attrs:
                if value and (key == "id" or tag == "a" and key == "name"):
                    self.anchors.add(value)

    parser = AnchorParser()
    parser.feed(_without_code_spans(_rendered_blocks(text)))
    return parser.anchors


def _resolve_link(root: Path, source: str, target: str) -> tuple[str | None, str | None]:
    try:
        parsed = urlsplit(target)
    except ValueError as exc:
        return None, f"{source}: malformed link {target}: {exc}"
    if parsed.scheme in {"http", "https", "mailto"} or parsed.netloc:
        return None, None
    if parsed.scheme or target.startswith("/"):
        return None, f"{source}: unsafe absolute link {target}"
    parent = posixpath.dirname(source)
    joined = posixpath.join(parent, parsed.path) if parsed.path else source
    relative = _safe_relative(joined)
    if relative is None:
        return None, f"{source}: link escapes repository or is invalid: {target}"
    if problem := _repository_path_error(root, relative):
        return None, f"{source}: {problem}"
    base = root / relative
    if not base.exists():
        return relative, f"{source}: missing link target {target}"
    if parsed.fragment and base.is_file():
        fragment = unquote(parsed.fragment)
        if fragment not in _headings(base) and fragment not in _anchors(base):
            return relative, f"{source}: missing fragment {parsed.fragment} in {relative}"
    return relative, None


def _markdown_text(value: str) -> str:
    # Entities cannot introduce link delimiters, HTML, or extra Markdown lines.
    return "".join(f"&#{ord(char)};" if char in string.punctuation and char not in "/.-" else char
                   for char in " ".join(value.split()))


def _render_generated(root: Path, relative: str, spec: dict[str, Any], expected: list[str]) -> str:
    title = (
        spec.get("title")
        if isinstance(spec.get("title"), str)
        else f"Generated discovery for {relative}"
    )
    section = (
        spec.get("section") if isinstance(spec.get("section"), str) else "Discoverable documents"
    )
    parent = posixpath.dirname(relative)
    lines = [GENERATED_MARKER, f"# {_markdown_text(title)}", "",
             f"## {_markdown_text(section)}", ""]
    for item in sorted(expected):
        target = quote(posixpath.relpath(item, parent or "."), safe="/.-_~")
        label = _markdown_text(item)
        lines.append(f"- [{label}]({target}) - Declared by an authoritative inventory.")
        lines.append("")
    return "\n".join(lines)


def _classify(
    root: Path,
    indexes: list[str],
    expected: list[str],
    adapter: dict[str, Any],
    generated: dict[str, dict[str, Any]],
) -> list[dict[str, Any]]:
    exclusions = _configured_paths(adapter, "explicit_exclusions") | _configured_paths(
        adapter, "closed_inventories"
    )
    authored = _configured_paths(adapter, "authored_boundaries")
    curated = _configured_paths(adapter, "curated_shortcuts")
    intentional_no_indexes = _configured_paths(adapter, "intentional_no_indexes")
    root_index = adapter.get("root_index", INDEX_NAME)
    relevant: set[str] = {posixpath.dirname(root_index) or "."}
    for item in expected:
        path = Path(item).parent
        while str(path) not in ("", "."):
            relevant.add(path.as_posix())
            path = path.parent
    for item in indexes:
        relevant.add(posixpath.dirname(item) or ".")
    for item in generated:
        relevant.add(posixpath.dirname(item) or ".")
    relevant.update(authored)
    result: list[dict[str, Any]] = []
    for directory in sorted(relevant):
        excluded = next(
            (
                prefix
                for prefix in sorted(exclusions)
                if directory == prefix or directory.startswith(prefix + "/")
            ),
            None,
        )
        index = posixpath.normpath(posixpath.join(directory, INDEX_NAME))
        expected_here = [
            item for item in expected
            if index == root_index or item == directory or item.startswith(directory + "/")
        ]
        generated_here = index in generated
        generated_projection = next(
            (
                relative
                for relative, spec in sorted(generated.items())
                if isinstance(spec, dict)
                and isinstance(spec.get("inventory"), list)
                and expected_here
                and all(
                    any(
                        item == str(scope) or item.startswith(str(scope).rstrip("/") + "/")
                        for scope in spec["inventory"]
                    )
                    for item in expected_here
                )
            ),
            None,
        )
        existing = index in indexes
        curated_parent = next(
            (prefix for prefix in sorted(curated) if directory.startswith(prefix + "/")),
            None,
        )
        if excluded:
            category = "index-unnecessary"
            reason = f"explicit exclusion or closed inventory: {excluded}"
        elif directory in intentional_no_indexes and existing:
            category = "authority-needed"
            reason = "existing index conflicts with an intentional no-index boundary"
        elif directory in intentional_no_indexes:
            category = "index-unnecessary"
            reason = "adapter declares an intentional no-index discovery boundary"
        elif generated_here:
            category = "generated-index-needed"
            reason = "adapter declares a deterministic generated index"
        elif index == root_index:
            category = "authored-index-needed"
            reason = "configured root provides authority-wide discovery"
        elif generated_projection:
            category = "index-unnecessary"
            reason = (
                f"declared generated index {generated_projection} provides this discovery boundary"
            )
        elif curated_parent and not existing:
            category = "index-unnecessary"
            reason = f"ancestor boundary {curated_parent} provides a curated shortcut"
        elif curated_parent and existing:
            category = "authority-needed"
            reason = (
                f"existing index is under curated boundary {curated_parent}; "
                "removal or retention needs authority judgment"
            )
        elif existing and expected_here:
            category = "authored-index-needed"
            reason = "authoritative inventory identifies a meaningful curated boundary"
        elif existing:
            category = "authority-needed"
            reason = (
                "existing index has no authoritative expected set; "
                "it is not retained by presence alone"
            )
        elif directory in authored or len(expected_here) > 1:
            category = "authored-index-needed"
            reason = "meaningful boundary needs curated next-step navigation"
        elif expected_here:
            category = "index-unnecessary"
            reason = "one destination can be reached directly without a physical mirror"
        else:
            category = "index-unnecessary"
            reason = "no authoritative discoverable destination"
        result.append(
            {
                "directory": directory,
                "index": index,
                "classification": category,
                "reason": reason,
                "expected": expected_here,
            }
        )
    return result


def _reachable_from_index(root: Path, indexes: list[str], start: str) -> tuple[set[str], list[str]]:
    reachable: set[str] = set()
    issues: list[str] = []
    queue = [start]
    while queue:
        current = queue.pop(0)
        if current in reachable:
            continue
        reachable.add(current)
        links, grammar = _read_index_links(root, current)
        issues.extend(grammar)
        for link in links:
            resolved, issue = _resolve_link(root, current, link["target"])
            if issue:
                issues.append(issue)
            if not resolved or not (root / resolved).exists():
                continue
            if resolved in indexes:
                queue.append(resolved)
            else:
                reachable.add(resolved)
    return reachable, issues


def _plan(
    root: Path,
    adapter: dict[str, Any],
    indexes: list[str],
    expected: list[str],
    generated: dict[str, dict[str, Any]],
    policy: dict[str, Any],
) -> list[dict[str, Any]]:
    plan: list[dict[str, Any]] = []
    if not policy["profile_selected"] or not policy["skill_selected"]:
        return plan
    for relative, spec in sorted(generated.items()):
        if problem := _repository_path_error(root, relative):
            plan.append({"action": "authority-needed", "kind": "generated",
                         "path": relative, "reason": problem, "content": None})
            continue
        expected_for_index = expected
        configured_inventory = spec.get("inventory") if isinstance(spec, dict) else None
        if isinstance(configured_inventory, list):
            configured = {str(item) for item in configured_inventory}
            expected_for_index = [
                item
                for item in expected
                if any(item == inv or item.startswith(inv.rstrip("/") + "/") for inv in configured)
            ]
        expected_for_index = [item for item in expected_for_index if item != relative]
        rendered = _render_generated(root, relative, spec, expected_for_index)
        path = root / relative
        state = _target_state(root, relative)
        if state["kind"] == "missing":
            if state.get("tracked") is False and state.get("dirty") is False:
                action = "create"
                reason = "declared generated index is missing"
            else:
                action = "authority-needed"
                reason = "missing target is tracked, dirty, or Git state is unknown"
        elif state["kind"] != "file" or state.get("read_error"):
            action = "authority-needed"
            reason = "declared generated target is not a readable regular file"
        elif not state.get("generated_marker") or not state.get("utf8"):
            action = "authority-needed"
            reason = "refusing authored or non-UTF-8 content at a generated target"
        elif state.get("bytes_sha256") == hashlib.sha256(rendered.encode("utf-8")).hexdigest():
            action = "none"
            reason = "generated output is fresh; no mutation is needed"
        elif not state.get("tracked") or state.get("dirty") is not False:
            action = "authority-needed"
            reason = "generated target is locally modified or ownership is unknown"
        else:
            action = "regenerate"
            reason = "generated output differs from deterministic source projection"
        plan.append(
            {
                "action": action,
                "kind": "generated",
                "path": relative,
                "reason": reason,
                "content": rendered if action in {"create", "regenerate"} else None,
                "snapshot": state,
            }
        )
    remove = _configured_paths(adapter, "remove_generated_indexes")
    for relative in sorted(remove):
        if problem := _repository_path_error(root, relative):
            plan.append({"action": "authority-needed", "kind": "generated",
                         "path": relative, "reason": problem, "content": None})
            continue
        snapshot = _target_state(root, relative)
        if (snapshot["kind"] == "missing" and snapshot.get("tracked") is False
                and snapshot.get("dirty") is False):
            continue
        if (snapshot.get("kind") == "file" and snapshot.get("generated_marker")
                and snapshot.get("tracked") and snapshot.get("dirty") is False
                and snapshot.get("utf8")):
            plan.append(
                {
                    "action": "delete",
                    "kind": "generated",
                    "path": relative,
                    "reason": "adapter explicitly retired this generated index",
                    "content": None,
                    "snapshot": snapshot,
                }
            )
        else:
            plan.append(
                {
                    "action": "authority-needed",
                    "kind": "authored",
                    "path": relative,
                    "reason": "retired target is authored, untracked, dirty, or ownership unknown",
                    "content": None,
                }
            )
    classifications = _classify(root, indexes, expected, adapter, generated)
    for item in classifications:
        if item["classification"] == "authored-index-needed" and item["index"] not in indexes:
            plan.append(
                {
                    "action": "create",
                    "kind": "authored",
                    "path": item["index"],
                    "reason": "curated authored index is missing; authority must supply links",
                    "content": None,
                }
            )
        elif item["classification"] == "authored-index-needed" and item["index"] in indexes:
            reachable, issues = _reachable_from_index(root, indexes, item["index"])
            exclusions = adapter.get("authored_index_exclusions", {}).get(item["index"], {})
            missing = [document for document in item["expected"]
                       if document not in reachable and document not in exclusions]
            if issues or missing:
                detail = []
                if missing:
                    detail.append(f"missing expected destinations: {', '.join(missing)}")
                if issues:
                    detail.append("link or grammar diagnostics require review")
                plan.append(
                    {
                        "action": "update",
                        "kind": "authored",
                        "path": item["index"],
                        "reason": "authored navigation is stale; " + "; ".join(detail),
                        "content": None,
                    }
                )
        elif item["classification"] == "authority-needed" and item["index"] in indexes:
            plan.append(
                {
                    "action": "authority-needed",
                    "kind": "authored",
                    "path": item["index"],
                    "reason": item["reason"],
                    "content": None,
                }
            )
    return plan


def _target_state(root: Path, relative: str) -> dict[str, Any]:
    """Capture the target facts that must still hold at mutation time."""
    path = root / relative
    state: dict[str, Any] = {"exists": path.exists(), "kind": "missing"}
    if path.is_symlink():
        state["kind"] = "symlink"
    elif path.is_file():
        state["kind"] = "file"
        try:
            identity = path.stat()
            data = path.read_bytes()
            state["identity"] = [identity.st_dev, identity.st_ino]
            state["mode"] = stat.S_IMODE(identity.st_mode)
            state.update(bytes_sha256=hashlib.sha256(data).hexdigest(),
                         generated_marker=_has_generated_marker(data), utf8=True)
            try:
                data.decode("utf-8")
            except UnicodeError:
                state["utf8"] = False
        except OSError as exc:
            state["read_error"] = str(exc)
    elif path.exists():
        state["kind"] = "other"
    tracking_query = None
    status = None
    try:
        tracking_query = subprocess.run(
            ["git", "--literal-pathspecs", "-C", str(root),
             "ls-files", "-v", "-z", "--error-unmatch", "--", relative],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            check=False,
        )
    except OSError:
        pass
    try:
        status = subprocess.run(
            ["git", "--literal-pathspecs", "-C", str(root),
             "status", "--porcelain", "--", relative],
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError:
        pass
    tracking_status = tracking_query.returncode if tracking_query is not None else None
    tracked = True if tracking_status == 0 else False if tracking_status == 1 else None
    state["tracked"] = tracked
    state["git_index_tag"] = (tracking_query.stdout[:1].decode("ascii", errors="replace")
                              if tracked else None)
    state["dirty"] = (bool(status.stdout.strip())
                      if status is not None and status.returncode == 0 else None)
    if tracked and state["git_index_tag"] != "H":
        state["dirty"] = None  # Git index flags can suppress worktree changes.
    return state


def _validate(
    root: Path,
    indexes: list[str],
    expected: list[str],
    adapter: dict[str, Any],
    generated: dict[str, dict[str, Any]],
    policy: dict[str, Any],
) -> dict[str, Any]:
    errors: list[str] = []
    warnings: list[str] = []
    links_by_index: dict[str, list[str]] = {}
    for relative in indexes:
        links, grammar = _read_index_links(root, relative)
        errors.extend(grammar)
        links_by_index[relative] = []
        for link in links:
            resolved, issue = _resolve_link(root, relative, link["target"])
            if issue:
                errors.append(issue)
            if resolved:
                links_by_index[relative].append(resolved)
    for relative, spec in generated.items():
        if problem := _repository_path_error(root, relative):
            errors.append(problem)
            continue
        path = root / relative
        configured_inventory = spec.get("inventory") if isinstance(spec, dict) else None
        expected_for_index = expected
        if isinstance(configured_inventory, list):
            configured = {str(item) for item in configured_inventory}
            expected_for_index = [
                item
                for item in expected
                if any(item == inv or item.startswith(inv.rstrip("/") + "/") for inv in configured)
            ]
        expected_for_index = [item for item in expected_for_index if item != relative]
        rendered = _render_generated(root, relative, spec, expected_for_index)
        if not path.is_file():
            errors.append(f"generated freshness: missing {relative}")
        else:
            try:
                if path.read_bytes() != rendered.encode("utf-8"):
                    errors.append(f"generated freshness: stale {relative}")
            except OSError as exc:
                errors.append(f"generated freshness: unreadable {relative}: {exc}")
    root_index = adapter.get("root_index", INDEX_NAME)
    if not isinstance(root_index, str):
        root_index = INDEX_NAME
    reachable: set[str] = set()
    queue = [root_index] if root_index in indexes else []
    if not queue and policy["profile_selected"] and policy["skill_selected"]:
        errors.append(f"nested-index reachability: root index {root_index} is missing")
    while queue:
        current = queue.pop(0)
        if current in reachable:
            continue
        reachable.add(current)
        for target in links_by_index.get(current, []):
            if target in indexes and target not in reachable:
                queue.append(target)
            elif target in expected:
                reachable.add(target)
    if policy["profile_selected"] and policy["skill_selected"]:
        for orphan in sorted(set(indexes) - reachable):
            errors.append(f"nested-index reachability: orphan index {orphan}")
        for item in expected:
            if problem := _repository_path_error(root, item):
                errors.append(problem)
                reachable.discard(item)
                continue
            if not (root / item).is_file():
                errors.append(f"expected-document coverage: declared document is missing: {item}")
            if item not in reachable:
                errors.append(
                    f"expected-document coverage: {item} is not reachable from {root_index}"
                )
    if not adapter.get("authoritative_inventories") and expected:
        warnings.append(
            "expected set used discovered inventory filenames; declare "
            "authoritative_inventories for a stable local adapter"
        )
    if not adapter.get("publication_system", False):
        warnings.append("publication system not declared; publication metadata is not required")
    return {
        "valid": not errors,
        "errors": sorted(set(errors)),
        "warnings": sorted(set(warnings)),
        "reachable": sorted(reachable),
    }


def _apply(
    root: Path, plan: list[dict[str, Any]], policy: dict[str, Any]
) -> tuple[list[str], list[str]]:
    if not policy["profile_selected"] or not policy["skill_selected"]:
        return [], [
            "apply refused: progressive-discovery profile and Skill must both be "
            "explicitly selected"
        ]
    candidates = [
        item
        for item in plan
        if item["action"] in {"create", "regenerate", "delete"} and item["kind"] == "generated"
    ]
    def revalidate(item: dict[str, Any]) -> str | None:
        if problem := _repository_path_error(root, item["path"]):
            return f"authority-needed: {problem}"
        current = _target_state(root, item["path"])
        if item.get("snapshot") != current:
            return f"authority-needed: target changed since plan: {item['path']}"
        if item["action"] == "create":
            safe = (current.get("kind") == "missing"
                    and current.get("tracked") is False and current.get("dirty") is False)
        else:
            safe = (
                current.get("kind") == "file"
                and current.get("tracked")
                and current.get("dirty") is False
                and current.get("generated_marker")
                and current.get("utf8")
            )
        if not safe:
            return (
                "authority-needed: generated target is locally modified or ownership "
                f"is unknown: {item['path']}"
            )
        return None

    blockers = [item["reason"] for item in plan if item["action"] == "authority-needed"]
    blockers.extend(error for item in candidates if (error := revalidate(item)))
    if blockers:
        return [], blockers
    if not candidates:
        return [], []
    changes: list[str] = []
    undo: list[dict[str, Any]] = []

    def read_fd(fd: int) -> bytes:
        os.lseek(fd, 0, os.SEEK_SET)
        chunks = []
        while chunk := os.read(fd, 65536):
            chunks.append(chunk)
        return b"".join(chunks)

    def replace_fd(fd: int, content: bytes) -> None:
        os.lseek(fd, 0, os.SEEK_SET)
        remaining = memoryview(content)
        while remaining:
            count = os.write(fd, remaining)
            if not count:
                raise OSError("short write")
            remaining = remaining[count:]
        os.ftruncate(fd, len(content))

    cleanup_errors: list[str] = []

    def rename_exclusive(source_fd: int, source: str, destination_fd: int,
                         destination: str) -> None:
        # Linux renameat2(RENAME_NOREPLACE) provides the required atomic
        # no-clobber restoration for files, symlinks, and directories alike.
        libc = ctypes.CDLL(None, use_errno=True)
        rename = getattr(libc, "renameat2", None)
        if rename is None:
            raise OSError("atomic no-replace rename is unavailable")
        rename.argtypes = [ctypes.c_int, ctypes.c_char_p, ctypes.c_int,
                           ctypes.c_char_p, ctypes.c_uint]
        rename.restype = ctypes.c_int
        if rename(source_fd, os.fsencode(source), destination_fd,
                  os.fsencode(destination), 1):
            number = ctypes.get_errno()
            raise OSError(number, os.strerror(number))

    def make_holding(parent: int, label: str) -> tuple[str, int, tuple[int, int], str]:
        """Create a private holding directory and bind its descriptor identity."""
        holding = ".progressive-discovery-" + secrets.token_hex(16)
        os.mkdir(holding, 0o700, dir_fd=parent)
        try:
            private = os.open(holding, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW,
                              dir_fd=parent)
        except OSError as exc:
            # We cannot safely unlink an unbound pathname. Leave it for an
            # authority decision instead of risking removal of a replacement.
            raise OSError(f"holding directory could not be identity-bound: {label}: {exc}") from exc
        identity = os.fstat(private)
        location = posixpath.join(posixpath.dirname(label), holding, "target")
        return holding, private, (identity.st_dev, identity.st_ino), location

    def remove_owned(parent: int, name: str, identity: tuple[int, int],
                     content: bytes | None, label: str,
                     *, cleanup_holding: bool = True) -> None:
        # A shared pathname cannot be conditionally unlinked by inode. Atomically
        # detach it into an operation-private namespace, validate what was moved,
        # and delete only that object. A replacement at the public name survives.
        holding, private, holding_identity, location = make_holding(parent, label)
        moved = False
        retained = False
        try:
            rename_exclusive(parent, name, private, "target")
            moved = True
            fd = os.open("target", os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK, dir_fd=private)
            try:
                current = os.fstat(fd)
                if (current.st_dev, current.st_ino) != identity:
                    raise OSError("target identity changed before removal")
                if content is None:
                    if not stat.S_ISDIR(current.st_mode):
                        raise OSError("directory kind changed before removal")
                elif (not stat.S_ISREG(current.st_mode) or current.st_nlink != 1
                      or read_fd(fd) != content):
                    raise OSError("target content or ownership changed before removal")
            finally:
                os.close(fd)
            if content is None:
                os.rmdir("target", dir_fd=private)
            else:
                os.unlink("target", dir_fd=private)
            moved = False
        except OSError as exc:
            if moved:
                try:
                    rename_exclusive(private, "target", parent, name)
                    moved = False
                except OSError as restore_error:
                    retained = True
                    changes.append(f"retain {label} at {location}")
                    raise OSError(f"{exc}; state retained at {location}; "
                                  f"no-clobber restoration failed: {restore_error}") from exc
            raise
        finally:
            if private is not None:
                os.close(private)
            if not retained:
                try:
                    if cleanup_holding:
                        remove_owned(parent, holding, holding_identity,
                                     None, posixpath.dirname(location),
                                     cleanup_holding=False)
                    else:
                        current = os.stat(holding, dir_fd=parent, follow_symlinks=False)
                        if ((current.st_dev, current.st_ino) != holding_identity
                                or not stat.S_ISDIR(current.st_mode)):
                            raise OSError("temporary directory identity changed")
                        os.rmdir(holding, dir_fd=parent)
                except OSError as exc:
                    cleanup_errors.append(
                        f"authority-needed: temporary directory retained: {location}: {exc}")

    def publish_new(parent: int, name: str, label: str, *,
                    content: bytes | None = None, mode: int | None = None,
                    retain_on_failure: bool = True,
                    before_publish: Callable[[], str | None] | None = None) -> tuple[int, Any]:
        # Build and identify the object in a private namespace before exposing
        # its public name. No partially written rollback placeholder is public.
        holding, private, holding_identity, location = make_holding(parent, label)
        fd = None
        published = False
        retained = False
        prepared = False
        try:
            if content is None:
                os.mkdir("target", 0o777 if mode is None else mode, dir_fd=private)
                prepared = True
                fd = os.open("target", os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW,
                             dir_fd=private)
            else:
                fd = os.open("target", os.O_RDWR | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW,
                             0o666 if mode is None else 0o600, dir_fd=private)
                prepared = True
                replace_fd(fd, content)
                # Creation modes are masked by umask; restoring a saved mode is
                # an explicit operation on the private completed object.
                if mode is not None:
                    os.fchmod(fd, mode)
            identity = os.fstat(fd)
            if before_publish and (error := before_publish()):
                raise OSError(error)
            rename_exclusive(private, "target", parent, name)
            published = True
            return fd, identity
        except OSError as exc:
            if prepared:
                if content is None:
                    try:
                        os.rmdir("target", dir_fd=private)
                        prepared = False
                    except OSError:
                        pass
                elif not retain_on_failure:
                    try:
                        os.unlink("target", dir_fd=private)
                        prepared = False
                    except OSError:
                        pass
                if prepared:
                    retained = True
                    changes.append(f"retain {label} at {location}")
                    raise OSError(f"{exc}; unpublished restoration retained at {location}") from exc
            raise
        finally:
            if fd is not None and not published:
                os.close(fd)
            if private is not None:
                os.close(private)
            if not retained:
                try:
                    remove_owned(parent, holding, holding_identity,
                                 None, posixpath.dirname(location),
                                 cleanup_holding=False)
                except OSError as exc:
                    cleanup_errors.append(
                        f"authority-needed: temporary directory retained: {location}: {exc}")

    def rollback(errors: list[str]) -> tuple[list[str], list[str]]:
        for owned in reversed(undo):
            try:
                parent, name = owned["parent"], owned["name"]
                if owned["action"] == "mkdir":
                    current = os.stat(name, dir_fd=parent, follow_symlinks=False)
                    if (not stat.S_ISDIR(current.st_mode)
                            or (current.st_dev, current.st_ino) != owned["identity"]):
                        raise OSError("concurrent directory state retained")
                    # rmdir is atomic with respect to emptiness: another process's
                    # newly created contents are never recursively removed.
                    remove_owned(parent, name, owned["identity"], None, owned["path"])
                elif owned["action"] == "delete":
                    fd, _ = publish_new(parent, name, owned["path"],
                                        content=owned["before"], mode=owned["mode"])
                    os.close(fd)
                else:
                    fd = os.open(name, os.O_RDWR | os.O_NOFOLLOW, dir_fd=parent)
                    try:
                        current = os.fstat(fd)
                        if ((current.st_dev, current.st_ino) != owned["identity"]
                                or read_fd(fd) != owned["after"]):
                            raise OSError("concurrent state retained")
                        if owned["action"] == "create":
                            remove_owned(parent, name, owned["identity"],
                                         owned["after"], owned["path"])
                        else:
                            replace_fd(fd, owned["before"])
                    finally:
                        os.close(fd)
                changes.append(f"rollback {owned['path']}")
            except OSError as exc:
                errors.append(f"authority-needed: rollback incomplete: {owned['path']}: {exc}")
        return changes, errors + cleanup_errors

    # Resolve every directory without following symlinks, then keep the directory
    # descriptors alive through mutation and any owned rollback. A renamed parent
    # cannot redirect an operation to an unrelated directory outside the authority.
    with ExitStack() as descriptors:
        try:
            if (not hasattr(os, "O_NOFOLLOW") or not hasattr(os, "O_DIRECTORY")
                    or any(operation not in os.supports_dir_fd
                           for operation in (os.open, os.mkdir, os.unlink, os.rmdir))):
                raise OSError("safe descriptor-relative mutations are unavailable")
            if getattr(ctypes.CDLL(None), "renameat2", None) is None:
                raise OSError("atomic no-replace rename is unavailable")
            directory_flags = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW
            root_fd = os.open(root.anchor, directory_flags)
            descriptors.callback(os.close, root_fd)
            for component in root.parts[1:]:
                root_fd = os.open(component, directory_flags, dir_fd=root_fd)
                descriptors.callback(os.close, root_fd)
            for item in candidates:
                relative = item["path"]
                parent_fd = root_fd
                parts = Path(relative).parts
                for depth, component in enumerate(parts[:-1]):
                    try:
                        child_fd = os.open(component, directory_flags, dir_fd=parent_fd)
                    except FileNotFoundError:
                        if item["action"] == "delete":
                            raise
                        directory_path = "/".join(parts[:depth + 1])
                        child_fd, created = publish_new(parent_fd, component, directory_path)
                        changes.append(f"mkdir {directory_path}")
                        undo.append({"action": "mkdir", "path": directory_path,
                                     "parent": parent_fd, "name": component,
                                     "identity": (created.st_dev, created.st_ino)})
                    descriptors.callback(os.close, child_fd)
                    parent_fd = child_fd
                if error := revalidate(item):
                    return rollback([error])
                # Detect a swap performed during validation itself. Subsequent
                # operations remain anchored even if the path is swapped later.
                parent_state = (root / relative).parent.stat()
                anchored = os.fstat(parent_fd)
                if (parent_state.st_dev, parent_state.st_ino) != (anchored.st_dev, anchored.st_ino):
                    raise OSError(f"parent directory changed: {relative}")
                action, name = item["action"], parts[-1]
                content = item.get("content")
                if action != "delete" and not isinstance(content, str):
                    raise OSError(f"missing planned content: {relative}")
                if action == "create":
                    after = content.encode("utf-8")
                    fd, identity = publish_new(parent_fd, name, relative,
                                               content=after, retain_on_failure=False,
                                               before_publish=lambda: revalidate(item))
                    try:
                        undo.append({"action": action, "path": relative, "parent": parent_fd,
                                     "name": name, "identity": (identity.st_dev, identity.st_ino),
                                     "mode": stat.S_IMODE(identity.st_mode),
                                     "before": b"", "after": after})
                        changes.append(f"{action} {relative}")
                    finally:
                        os.close(fd)
                    continue
                fd = os.open(name, os.O_RDWR | os.O_NOFOLLOW, dir_fd=parent_fd)
                try:
                    identity = os.fstat(fd)
                    if not stat.S_ISREG(identity.st_mode) or identity.st_nlink != 1:
                        raise OSError(f"target is not an exclusively owned regular file: {relative}")
                    before = read_fd(fd)
                    if action != "create" and (
                        [identity.st_dev, identity.st_ino] != item["snapshot"].get("identity")
                        or stat.S_IMODE(identity.st_mode) != item["snapshot"].get("mode")
                        or hashlib.sha256(before).hexdigest() != item["snapshot"].get("bytes_sha256")
                        or not _has_generated_marker(before)
                    ):
                        raise OSError(f"target changed since plan: {relative}")
                    after = content.encode("utf-8") if action != "delete" else None
                    record = {"action": action, "path": relative, "parent": parent_fd,
                              "name": name, "identity": (identity.st_dev, identity.st_ino),
                              "mode": stat.S_IMODE(identity.st_mode),
                              "before": before, "after": after}
                    if action == "delete":
                        remove_owned(parent_fd, name, record["identity"], before, relative)
                        undo.append(record)
                        changes.append(f"{action} {relative}")
                    else:
                        # Record even a partial I/O failure. Rollback refuses
                        # bytes differing from the completed planned output;
                        # partial writes remain explicit residual changes.
                        undo.append(record)
                        changes.append(f"{action} {relative}")
                        replace_fd(fd, after)
                finally:
                    os.close(fd)
        except OSError as exc:
            return rollback([f"authority-needed: mutation failed: {exc}"])
        if cleanup_errors:
            return rollback([])
    return changes, []


def run(
    root: Path,
    *,
    adapter_path: str = ADAPTER_NAME,
    policy_path: str = POLICY_NAME,
    apply: bool = False,
) -> dict[str, Any]:
    root = root.resolve()
    adapter, adapter_errors = _load_adapter(root, adapter_path)
    policy_raw, policy_notes = _yaml_policy(root, policy_path)
    policy = _policy_state(policy_raw)
    indexes = _index_paths(root, adapter)
    inventories = _discover_inventory_paths(root, adapter)
    expected, inventory_errors = _expected_documents(root, adapter, inventories)
    generated = _generated_specs(adapter)
    for documents in adapter.get("authored_index_exclusions", {}).values():
        for document in documents:
            if document not in expected:
                adapter_errors.append(
                    f"adapter: scoped exclusion is not an expected document: {document}"
                )
    source_errors = adapter_errors + inventory_errors + policy_notes
    plan = [] if source_errors else _plan(root, adapter, indexes, expected, generated, policy)
    requested_plan = plan
    applied: list[str] = []
    apply_errors: list[str] = []
    if apply:
        if source_errors:
            apply_errors = [f"authority-needed: {error}" for error in source_errors]
        else:
            applied, apply_errors = _apply(root, plan, policy)
        if applied:
            indexes = _index_paths(root, adapter)
            plan = _plan(root, adapter, indexes, expected, generated, policy)
    validation = _validate(root, indexes, expected, adapter, generated, policy)
    selected = policy["profile_selected"] and policy["skill_selected"]
    if source_errors:
        validation["errors"] = sorted(set(validation["errors"] + source_errors))
        validation["valid"] = False
    if not selected and not source_errors:
        validation = {**validation, "valid": True, "errors": []}
    authority_needed = sum(1 for item in plan if item["action"] == "authority-needed") + len(
        apply_errors
    ) + (len(source_errors) if not apply else 0)
    applied_actions = set(applied)
    actionable = any(
        item["action"] in {"create", "update", "regenerate", "delete"}
        and f"{item['action']} {item['path']}" not in applied_actions
        for item in plan
    )
    if authority_needed:
        result = "AUTHORITY_NEEDED"
    elif not selected:
        result = "NOT_APPLICABLE"
    elif actionable or not validation["valid"]:
        result = "UPDATE_REQUIRED"
    else:
        result = "NO_UPDATE_REQUIRED"
    root_index = adapter.get("root_index", INDEX_NAME)
    orphan_indexes = sorted(
        item for item in indexes if item != root_index and item not in validation["reachable"]
    )
    errors = validation["errors"]
    return {
        "repository": str(root),
        "revision": _git_revision(root),
        "dirty": _git_dirty(root),
        "policy": policy,
        "policy_selected": selected,
        "adapter": adapter_path if adapter else None,
        "publication_system": bool(adapter.get("publication_system", False)),
        "surface_boundaries": adapter.get("surface_boundaries", {}),
        "source_ownership": {
            "authored_indexes": sorted(set(indexes) - set(generated)),
            "generated_indexes": sorted(generated),
            "authoritative_inventories": inventories,
            "inventory_path_namespaces": adapter.get("inventory_path_namespaces", {}),
            "curated_shortcuts": sorted(_configured_paths(adapter, "curated_shortcuts")),
        },
        "indexes": indexes,
        "inventories": inventories,
        "expected_documents": expected,
        "classification": _classify(root, indexes, expected, adapter, generated),
        "plan": [{key: value for key, value in item.items() if key != "content"} for item in plan],
        "applied": applied,
        "apply_errors": apply_errors,
        "requested_plan": requested_plan if apply else [],
        "exclusions": sorted(
            _configured_paths(adapter, "explicit_exclusions")
            | _configured_paths(adapter, "closed_inventories")
            | _configured_paths(adapter, "intentional_no_indexes")
        ),
        "notes": sorted(adapter_errors + inventory_errors + policy_notes),
        "validation": validation,
        "metrics": {
            "expected": len(expected),
            "reachable": len(validation["reachable"]),
            "broken_links": sum("link" in item for item in errors),
            "orphan_indexes": len(orphan_indexes),
            "stale_generated_indexes": sum("generated freshness: stale" in item for item in errors),
            "authority_needed": authority_needed,
        },
        "result": result,
    }


def _text_report(report: dict[str, Any]) -> str:
    lines = [
        f"repository: {report['repository']}",
        f"revision: {report['revision']}",
        "policy: "
        f"profile={'selected' if report['policy']['profile_selected'] else 'unselected'}, "
        f"skill={'selected' if report['policy']['skill_selected'] else 'unselected'}",
        "inventories: "
        f"{len(report['inventories'])}; "
        f"expected documents: {len(report['expected_documents'])}; "
        f"indexes: {len(report['indexes'])}",
        f"publication system: {'yes' if report['publication_system'] else 'no'}",
        "classifications:",
    ]
    for item in report["classification"]:
        lines.append(f"  {item['classification']}: {item['index']} — {item['reason']}")
    lines.append("plan:")
    for item in report["plan"]:
        lines.append(f"  {item['action']}: {item['path']} — {item['reason']}")
    for item in report["applied"]:
        lines.append(f"applied: {item}")
    for item in report["exclusions"]:
        lines.append(f"excluded: {item}")
    for item in report["notes"]:
        lines.append(f"note: {item}")
    validation = report["validation"]
    lines.append(f"validation: {'pass' if validation['valid'] else 'fail'}")
    lines.append(f"result: {report['result']}")
    for item in validation["errors"]:
        lines.append(f"  error: {item}")
    for item in validation["warnings"]:
        lines.append(f"  warning: {item}")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--adapter", default=ADAPTER_NAME)
    parser.add_argument("--policy", default=POLICY_NAME)
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--format", choices=("text", "json"), default="text")
    args = parser.parse_args(argv)
    report = run(args.root, adapter_path=args.adapter, policy_path=args.policy, apply=args.apply)
    if args.format == "json":
        print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))
    else:
        print(_text_report(report))
    if args.apply and not report["policy_selected"]:
        return 2
    if args.apply and (report["apply_errors"] or report["result"] != "NO_UPDATE_REQUIRED"):
        return 1
    return 0 if report["validation"]["valid"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
