#!/usr/bin/env python3
"""Safely plan and validate semantic ``index.md`` discovery boundaries."""

from __future__ import annotations

import argparse
import json
import os
import posixpath
import re
import subprocess
from collections.abc import Iterable
from pathlib import Path
from typing import Any
from urllib.parse import unquote, urlsplit

INDEX_NAME = "index.md"
ADAPTER_NAME = ".progressive-discovery.json"
POLICY_NAME = ".agent-policy.yml"
GENERATED_MARKER = "<!-- generated by maintain-progressive-discovery -->"
IGNORED_DIRECTORIES = {
    ".git",
    ".hg",
    ".svn",
    ".venv",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    "node_modules",
}
PATH_KEYS = {
    "path",
    "source",
    "destination",
    "target",
    "file",
    "filename",
    "document",
    "document_path",
    "source_path",
    "destination_path",
    "url_path",
}
PATH_SUFFIXES = (
    ".md",
    ".markdown",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
    ".py",
    ".schema",
)
LINK_RE = re.compile(r"(?<!!)\[([^\]]+)\]\(([^)]+)\)")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$")


def _relative(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def _safe_relative(value: str) -> str | None:
    value = value.strip().replace("\\", "/")
    if not value or value.startswith(("/", "\\")):
        return None
    parsed = urlsplit(value)
    if parsed.scheme or parsed.netloc:
        return None
    path = unquote(parsed.path)
    normalized = posixpath.normpath(path)
    if normalized in ("", ".") or normalized == ".." or normalized.startswith("../"):
        return None
    return normalized


def _ignored(path: Path, root: Path) -> bool:
    try:
        parts = path.relative_to(root).parts
    except ValueError:
        return True
    return any(
        part in IGNORED_DIRECTORIES or part.startswith(".") and part != ".well-known"
        for part in parts
    )


def _walk_files(root: Path) -> Iterable[Path]:
    for directory, dirnames, filenames in os.walk(root, followlinks=False):
        current = Path(directory)
        dirnames[:] = sorted(
            name
            for name in dirnames
            if name not in IGNORED_DIRECTORIES
            and not name.startswith(".")
            and not (current / name).is_symlink()
        )
        for name in sorted(filenames):
            path = current / name
            if path.is_symlink() or _ignored(path, root):
                continue
            yield path


def _read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _read_inventory(path: Path) -> tuple[Any, list[str]]:
    try:
        if path.suffix.lower() == ".json":
            return _read_json(path), []
        if path.suffix.lower() in {".yaml", ".yml"}:
            try:
                import yaml  # type: ignore
            except ImportError:
                return {}, [f"inventory {path}: PyYAML unavailable; YAML inventory was not read"]
            return yaml.safe_load(path.read_text(encoding="utf-8")) or {}, []
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        return {}, [f"inventory {path}: {exc}"]
    except Exception as exc:  # pragma: no cover - parser-specific defensive path
        return {}, [f"inventory {path}: {exc}"]
    return {}, [f"inventory {path}: unsupported inventory format"]


def _git_revision(root: Path) -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unresolved"


def _git_dirty(root: Path) -> bool | None:
    try:
        return bool(
            subprocess.check_output(
                ["git", "-C", str(root), "status", "--porcelain=v1"],
                text=True,
                stderr=subprocess.DEVNULL,
            ).strip()
        )
    except (OSError, subprocess.CalledProcessError):
        return None


def _load_adapter(root: Path, relative: str) -> tuple[dict[str, Any], list[str]]:
    path = root / relative
    if not path.is_file():
        return {}, []
    try:
        value = _read_json(path)
    except (OSError, json.JSONDecodeError) as exc:
        return {}, [f"adapter: {exc}"]
    if not isinstance(value, dict):
        return {}, ["adapter: root must be an object"]
    return value, []


def _yaml_policy(root: Path, relative: str) -> tuple[Any, list[str]]:
    path = root / relative
    if not path.is_file():
        return {}, []
    try:
        import yaml  # type: ignore

        return yaml.safe_load(path.read_text(encoding="utf-8")) or {}, []
    except ImportError:
        profiles: list[str] = []
        skills: list[str] = []
        section = ""
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.split("#", 1)[0].rstrip()
            if not line:
                continue
            if re.match(r"^\s*profiles\s*:\s*$", line):
                section = "profiles"
                continue
            if re.match(r"^\s*skills\s*:\s*$", line):
                section = "skills"
                continue
            match = re.match(r"^\s*-\s*([A-Za-z0-9][A-Za-z0-9-]*)\s*$", line)
            if match and section == "profiles":
                profiles.append(match.group(1))
            elif match and section == "skills":
                skills.append(match.group(1))
        return {"profiles": profiles, "skills": {"enabled": skills}}, [
            "policy: PyYAML unavailable; used conservative list fallback"
        ]
    except Exception as exc:  # pragma: no cover - parser-specific defensive path
        return {}, [f"policy: {exc}"]


def _find_values(value: Any, key: str | None = None) -> Iterable[str]:
    if isinstance(value, str):
        if key in PATH_KEYS or value.endswith(PATH_SUFFIXES):
            yield value
        return
    if isinstance(value, list):
        for item in value:
            yield from _find_values(item, key)
        return
    if isinstance(value, dict):
        for child_key, child in value.items():
            yield from _find_values(child, str(child_key).lower())


def _path_candidate(root: Path, raw: str) -> str | None:
    candidate = _safe_relative(raw)
    if candidate is None or candidate == INDEX_NAME:
        return None
    if candidate.startswith("http:") or candidate.startswith("https:"):
        return None
    if not candidate.lower().endswith(PATH_SUFFIXES):
        return None
    path = root / candidate
    if not path.is_file() or _ignored(path, root):
        return None
    return candidate


def _explicit_inventory_paths(root: Path, adapter: dict[str, Any]) -> list[str]:
    raw = adapter.get("authoritative_inventories", [])
    if not isinstance(raw, list):
        return []
    result: list[str] = []
    for item in raw:
        if isinstance(item, str):
            path = _safe_relative(item)
            if path and (root / path).is_file():
                result.append(path)
    return sorted(set(result))


def _discover_inventory_paths(root: Path, adapter: dict[str, Any]) -> list[str]:
    explicit = _explicit_inventory_paths(root, adapter)
    if explicit:
        return explicit
    pattern = re.compile(
        r"(?:catalog|manifest|inventory|registry|publication|documentation|site-discovery|feature-registry)",
        re.IGNORECASE,
    )
    paths: list[str] = []
    for path in _walk_files(root):
        if path.suffix.lower() not in {".json", ".yaml", ".yml"}:
            continue
        if pattern.search(path.name):
            paths.append(_relative(path, root))
    return sorted(paths)


def _expected_documents(
    root: Path, adapter: dict[str, Any], inventories: list[str]
) -> tuple[list[str], list[str]]:
    expected: set[str] = set()
    errors: list[str] = []
    for relative in inventories:
        path = root / relative
        value, notes = _read_inventory(path)
        errors.extend(notes)
        if notes:
            continue
        for raw in _find_values(value):
            candidate = _path_candidate(root, raw)
            if candidate:
                expected.add(candidate)
    raw_expected = adapter.get("expected_documents", [])
    if isinstance(raw_expected, list):
        for item in raw_expected:
            if isinstance(item, str):
                candidate = _path_candidate(root, item)
                if candidate:
                    expected.add(candidate)
    excluded = _configured_paths(adapter, "explicit_exclusions") | _configured_paths(
        adapter, "closed_inventories"
    )
    expected = {
        item
        for item in expected
        if not any(item == prefix or item.startswith(prefix + "/") for prefix in excluded)
    }
    return sorted(expected), errors


def _configured_paths(adapter: dict[str, Any], key: str) -> set[str]:
    raw = adapter.get(key, [])
    if isinstance(raw, dict):
        raw = list(raw)
    if not isinstance(raw, list):
        return set()
    return {value.rstrip("/") for value in raw if isinstance(value, str) and value.strip()}


def _generated_specs(adapter: dict[str, Any]) -> dict[str, dict[str, Any]]:
    raw = adapter.get("generated_indexes", {})
    result: dict[str, dict[str, Any]] = {}
    if isinstance(raw, dict):
        for path, value in raw.items():
            if isinstance(path, str):
                result[path] = value if isinstance(value, dict) else {}
    elif isinstance(raw, list):
        for value in raw:
            if isinstance(value, str):
                result[value] = {}
            elif isinstance(value, dict) and isinstance(value.get("path"), str):
                result[value["path"]] = value
    return result


def _policy_state(policy: Any) -> dict[str, Any]:
    profiles: list[str] = []
    selected_skills: list[str] = []

    def visit(value: Any, key: str | None = None) -> None:
        if isinstance(value, dict):
            for child_key, child in value.items():
                visit(child, str(child_key))
        elif isinstance(value, list):
            if key == "profiles":
                profiles.extend(item for item in value if isinstance(item, str))
            for child in value:
                if isinstance(child, (dict, list)):
                    visit(child, key)

    # Keep the normal path explicit so a context's profiles and skills.enabled
    # are not confused with unrelated strings in the configuration.
    if isinstance(policy, dict):
        contexts = policy.get("contexts")
        if isinstance(contexts, dict):
            for context in contexts.values():
                if isinstance(context, dict) and isinstance(context.get("profiles"), list):
                    profiles.extend(item for item in context["profiles"] if isinstance(item, str))
        top_profiles = policy.get("profiles")
        if isinstance(top_profiles, list):
            profiles.extend(item for item in top_profiles if isinstance(item, str))
        skills = policy.get("skills")
        if isinstance(skills, dict) and isinstance(skills.get("enabled"), list):
            selected_skills.extend(item for item in skills["enabled"] if isinstance(item, str))
    else:
        visit(policy)
    return {
        "profile_selected": "progressive-discovery" in profiles,
        "skill_selected": "maintain-progressive-discovery" in selected_skills,
        "profiles": sorted(set(profiles)),
        "skills": sorted(set(selected_skills)),
    }


def _index_paths(root: Path, adapter: dict[str, Any]) -> list[str]:
    excluded = _configured_paths(adapter, "explicit_exclusions") | _configured_paths(
        adapter, "closed_inventories"
    )
    return sorted(
        _relative(path, root)
        for path in _walk_files(root)
        if path.name == INDEX_NAME
        and not any(
            _relative(path, root) == prefix or _relative(path, root).startswith(prefix + "/")
            for prefix in excluded
        )
    )


def _read_index_links(root: Path, relative: str) -> tuple[list[dict[str, str]], list[str]]:
    path = root / relative
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        return [], [f"{relative}: {exc}"]
    links: list[dict[str, str]] = []
    issues: list[str] = []
    lines = text.splitlines()
    nonblank = [
        (index, line)
        for index, line in enumerate(lines, 1)
        if line.strip() and line.strip() != GENERATED_MARKER
    ]
    if not nonblank or not nonblank[0][1].startswith("# "):
        issues.append(f"{relative}: first nonblank line must be a level-1 heading")
    if any(line.startswith("# ") for index, line in nonblank[1:]):
        issues.append(f"{relative}: authored grammar permits only one level-1 heading")
    for line_number, line in nonblank:
        if line.startswith("#") and not HEADING_RE.match(line):
            issues.append(f"{relative}:{line_number}: malformed heading")
        if line.startswith(("- ", "* ")) and "[" not in line:
            issues.append(f"{relative}:{line_number}: list item must contain a Markdown link")
        if not line.startswith(("#", "- ", "* ", "  ")) and not LINK_RE.search(line):
            issues.append(f"{relative}:{line_number}: content is outside the small index grammar")
    for match in LINK_RE.finditer(text):
        label, target = match.groups()
        links.append({"label": label.strip(), "target": target.strip()})
    return links, issues


def _heading_slug(value: str) -> str:
    value = re.sub(r"[`*_~]", "", value.lower())
    value = re.sub(r"[^a-z0-9\u0080-\uffff -]", "", value)
    return re.sub(r"\s+", "-", value.strip())


def _headings(path: Path) -> set[str]:
    try:
        return {
            _heading_slug(match.group(2))
            for match in (
                HEADING_RE.match(line) for line in path.read_text(encoding="utf-8").splitlines()
            )
            if match
        }
    except OSError:
        return set()


def _anchors(path: Path) -> set[str]:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return set()
    return {unquote(value) for value in re.findall(r"\b(?:id|name)=[\"']([^\"']+)[\"']", text)}


def _resolve_link(root: Path, source: str, target: str) -> tuple[str | None, str | None]:
    parsed = urlsplit(target)
    if parsed.scheme in {"http", "https", "mailto"} or parsed.netloc:
        return None, None
    if parsed.scheme or target.startswith("/"):
        return None, f"{source}: unsafe absolute link {target}"
    parent = posixpath.dirname(source)
    joined = posixpath.join(parent, parsed.path or ".")
    relative = _safe_relative(joined)
    if relative is None:
        return None, f"{source}: link escapes repository or is invalid: {target}"
    base = root / relative
    if not base.exists():
        return relative, f"{source}: missing link target {target}"
    if parsed.fragment and base.is_file():
        fragment = unquote(parsed.fragment)
        if _heading_slug(fragment) not in _headings(base) and fragment not in _anchors(base):
            return relative, f"{source}: missing fragment {parsed.fragment} in {relative}"
    return relative, None


def _render_generated(root: Path, relative: str, spec: dict[str, Any], expected: list[str]) -> str:
    title = (
        spec.get("title")
        if isinstance(spec.get("title"), str)
        else f"Generated discovery for {relative}"
    )
    section = (
        spec.get("section") if isinstance(spec.get("section"), str) else "Discoverable documents"
    )
    parent = posixpath.dirname(relative)
    lines = [GENERATED_MARKER, f"# {title}", "", f"## {section}", ""]
    for item in sorted(expected):
        target = posixpath.relpath(item, parent or ".")
        label = item
        lines.append(f"- [{label}]({target}) - Declared by an authoritative inventory.")
        lines.append("")
    return "\n".join(lines)


def _classify(
    root: Path,
    indexes: list[str],
    expected: list[str],
    adapter: dict[str, Any],
    generated: dict[str, dict[str, Any]],
) -> list[dict[str, Any]]:
    exclusions = _configured_paths(adapter, "explicit_exclusions") | _configured_paths(
        adapter, "closed_inventories"
    )
    authored = _configured_paths(adapter, "authored_boundaries")
    curated = _configured_paths(adapter, "curated_shortcuts")
    relevant: set[str] = set()
    for item in expected:
        path = Path(item).parent
        while str(path) not in ("", "."):
            relevant.add(path.as_posix())
            path = path.parent
    for item in indexes:
        relevant.add(posixpath.dirname(item) or ".")
    for item in generated:
        relevant.add(posixpath.dirname(item) or ".")
    relevant.update(authored)
    result: list[dict[str, Any]] = []
    for directory in sorted(relevant):
        if directory == ".":
            continue
        excluded = next(
            (
                prefix
                for prefix in sorted(exclusions)
                if directory == prefix or directory.startswith(prefix + "/")
            ),
            None,
        )
        index = posixpath.join(directory, INDEX_NAME)
        expected_here = [
            item for item in expected if item == directory or item.startswith(directory + "/")
        ]
        generated_here = index in generated
        existing = index in indexes
        curated_parent = next(
            (prefix for prefix in sorted(curated) if directory.startswith(prefix + "/")),
            None,
        )
        if excluded:
            category = "index-unnecessary"
            reason = f"explicit exclusion or closed inventory: {excluded}"
        elif generated_here:
            category = "generated-index-needed"
            reason = "adapter declares a deterministic generated index"
        elif curated_parent and not existing:
            category = "index-unnecessary"
            reason = f"ancestor boundary {curated_parent} provides a curated shortcut"
        elif curated_parent and existing:
            category = "authority-needed"
            reason = (
                f"existing index is under curated boundary {curated_parent}; "
                "removal or retention needs authority judgment"
            )
        elif existing and expected_here:
            category = "authored-index-needed"
            reason = "authoritative inventory identifies a meaningful curated boundary"
        elif existing:
            category = "authority-needed"
            reason = (
                "existing index has no authoritative expected set; "
                "it is not retained by presence alone"
            )
        elif directory in authored or len(expected_here) > 1:
            category = "authored-index-needed"
            reason = "meaningful boundary needs curated next-step navigation"
        elif expected_here:
            category = "index-unnecessary"
            reason = "one destination can be reached directly without a physical mirror"
        else:
            category = "index-unnecessary"
            reason = "no authoritative discoverable destination"
        result.append(
            {
                "directory": directory,
                "index": index,
                "classification": category,
                "reason": reason,
                "expected": expected_here,
            }
        )
    return result


def _reachable_from_index(root: Path, indexes: list[str], start: str) -> tuple[set[str], list[str]]:
    reachable: set[str] = set()
    issues: list[str] = []
    queue = [start]
    while queue:
        current = queue.pop(0)
        if current in reachable:
            continue
        reachable.add(current)
        links, grammar = _read_index_links(root, current)
        issues.extend(grammar)
        for link in links:
            resolved, issue = _resolve_link(root, current, link["target"])
            if issue:
                issues.append(issue)
            if not resolved or not (root / resolved).exists():
                continue
            if resolved in indexes:
                queue.append(resolved)
            else:
                reachable.add(resolved)
    return reachable, issues


def _plan(
    root: Path,
    adapter: dict[str, Any],
    indexes: list[str],
    expected: list[str],
    generated: dict[str, dict[str, Any]],
    policy: dict[str, Any],
) -> list[dict[str, Any]]:
    plan: list[dict[str, Any]] = []
    if not policy["profile_selected"] or not policy["skill_selected"]:
        return plan
    for relative, spec in sorted(generated.items()):
        expected_for_index = expected
        configured_inventory = spec.get("inventory") if isinstance(spec, dict) else None
        if isinstance(configured_inventory, list):
            configured = {str(item) for item in configured_inventory}
            expected_for_index = [
                item
                for item in expected
                if any(item == inv or item.startswith(inv.rstrip("/") + "/") for inv in configured)
            ]
        expected_for_index = [item for item in expected_for_index if item != relative]
        rendered = _render_generated(root, relative, spec, expected_for_index)
        path = root / relative
        if not path.exists():
            action = "create"
            reason = "declared generated index is missing"
        elif not path.is_file():
            action = "authority-needed"
            reason = "declared generated target is not a regular file"
        elif GENERATED_MARKER not in path.read_text(encoding="utf-8"):
            action = "authority-needed"
            reason = "refusing to overwrite an authored file at a generated target"
        elif path.read_text(encoding="utf-8") != rendered:
            action = "regenerate"
            reason = "generated output differs from deterministic source projection"
        else:
            action = "none"
            reason = "generated output is fresh"
        plan.append(
            {
                "action": action,
                "kind": "generated",
                "path": relative,
                "reason": reason,
                "content": rendered if action in {"create", "regenerate"} else None,
            }
        )
    remove = _configured_paths(adapter, "remove_generated_indexes")
    for relative in sorted(remove):
        path = root / relative
        if not path.exists():
            continue
        if path.is_file() and GENERATED_MARKER in path.read_text(encoding="utf-8"):
            plan.append(
                {
                    "action": "delete",
                    "kind": "generated",
                    "path": relative,
                    "reason": "adapter explicitly retired this generated index",
                    "content": None,
                }
            )
        else:
            plan.append(
                {
                    "action": "authority-needed",
                    "kind": "authored",
                    "path": relative,
                    "reason": "retirement is explicit but the file is not generated",
                    "content": None,
                }
            )
    classifications = _classify(root, indexes, expected, adapter, generated)
    for item in classifications:
        if item["classification"] == "authored-index-needed" and item["index"] not in indexes:
            plan.append(
                {
                    "action": "create",
                    "kind": "authored",
                    "path": item["index"],
                    "reason": "curated authored index is missing; authority must supply links",
                    "content": None,
                }
            )
        elif item["classification"] == "authored-index-needed" and item["index"] in indexes:
            reachable, issues = _reachable_from_index(root, indexes, item["index"])
            missing = [document for document in item["expected"] if document not in reachable]
            if issues or missing:
                detail = []
                if missing:
                    detail.append(f"missing expected destinations: {', '.join(missing)}")
                if issues:
                    detail.append("link or grammar diagnostics require review")
                plan.append(
                    {
                        "action": "update",
                        "kind": "authored",
                        "path": item["index"],
                        "reason": "authored navigation is stale; " + "; ".join(detail),
                        "content": None,
                    }
                )
        elif item["classification"] == "authority-needed" and item["index"] in indexes:
            plan.append(
                {
                    "action": "authority-needed",
                    "kind": "authored",
                    "path": item["index"],
                    "reason": item["reason"],
                    "content": None,
                }
            )
    return plan


def _validate(
    root: Path,
    indexes: list[str],
    expected: list[str],
    adapter: dict[str, Any],
    generated: dict[str, dict[str, Any]],
    policy: dict[str, Any],
) -> dict[str, Any]:
    errors: list[str] = []
    warnings: list[str] = []
    links_by_index: dict[str, list[str]] = {}
    for relative in indexes:
        links, grammar = _read_index_links(root, relative)
        errors.extend(grammar)
        links_by_index[relative] = []
        for link in links:
            resolved, issue = _resolve_link(root, relative, link["target"])
            if issue:
                errors.append(issue)
            if resolved:
                links_by_index[relative].append(resolved)
    for relative, spec in generated.items():
        path = root / relative
        configured_inventory = spec.get("inventory") if isinstance(spec, dict) else None
        expected_for_index = expected
        if isinstance(configured_inventory, list):
            configured = {str(item) for item in configured_inventory}
            expected_for_index = [
                item
                for item in expected
                if any(item == inv or item.startswith(inv.rstrip("/") + "/") for inv in configured)
            ]
        expected_for_index = [item for item in expected_for_index if item != relative]
        rendered = _render_generated(root, relative, spec, expected_for_index)
        if not path.is_file():
            errors.append(f"generated freshness: missing {relative}")
        elif path.read_text(encoding="utf-8") != rendered:
            errors.append(f"generated freshness: stale {relative}")
    root_index = adapter.get("root_index", INDEX_NAME)
    if not isinstance(root_index, str):
        root_index = INDEX_NAME
    reachable: set[str] = set()
    queue = [root_index] if root_index in indexes else []
    if not queue and policy["profile_selected"] and policy["skill_selected"]:
        errors.append(f"nested-index reachability: root index {root_index} is missing")
    while queue:
        current = queue.pop(0)
        if current in reachable:
            continue
        reachable.add(current)
        for target in links_by_index.get(current, []):
            if target in indexes and target not in reachable:
                queue.append(target)
            elif target in expected:
                reachable.add(target)
    if policy["profile_selected"] and policy["skill_selected"]:
        for item in expected:
            if item not in reachable:
                errors.append(
                    f"expected-document coverage: {item} is not reachable from {root_index}"
                )
    if not adapter.get("authoritative_inventories") and expected:
        warnings.append(
            "expected set used discovered inventory filenames; declare "
            "authoritative_inventories for a stable local adapter"
        )
    if not adapter.get("publication_system", False):
        warnings.append("publication system not declared; publication metadata is not required")
    return {
        "valid": not errors,
        "errors": sorted(set(errors)),
        "warnings": sorted(set(warnings)),
        "reachable": sorted(reachable),
    }


def _apply(root: Path, plan: list[dict[str, Any]], policy: dict[str, Any]) -> list[str]:
    if not policy["profile_selected"] or not policy["skill_selected"]:
        return [
            "apply refused: progressive-discovery profile and Skill must "
            "both be explicitly selected"
        ]
    changes: list[str] = []
    for item in plan:
        if item["action"] not in {"create", "regenerate", "delete"}:
            continue
        if item["kind"] != "generated":
            continue
        path = root / item["path"]
        if item["action"] in {"create", "regenerate"}:
            content = item.get("content")
            if not isinstance(content, str):
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            changes.append(f"{item['action']} {item['path']}")
        elif item["action"] == "delete" and path.is_file():
            path.unlink()
            changes.append(f"delete {item['path']}")
    return changes


def run(
    root: Path,
    *,
    adapter_path: str = ADAPTER_NAME,
    policy_path: str = POLICY_NAME,
    apply: bool = False,
) -> dict[str, Any]:
    root = root.resolve()
    adapter, adapter_errors = _load_adapter(root, adapter_path)
    policy_raw, policy_notes = _yaml_policy(root, policy_path)
    policy = _policy_state(policy_raw)
    indexes = _index_paths(root, adapter)
    inventories = _discover_inventory_paths(root, adapter)
    expected, inventory_errors = _expected_documents(root, adapter, inventories)
    generated = _generated_specs(adapter)
    plan = _plan(root, adapter, indexes, expected, generated, policy)
    applied: list[str] = []
    if apply:
        applied = _apply(root, plan, policy)
        if applied:
            indexes = _index_paths(root, adapter)
    validation = _validate(root, indexes, expected, adapter, generated, policy)
    selected = policy["profile_selected"] and policy["skill_selected"]
    if not selected:
        validation = {**validation, "valid": True, "errors": []}
    return {
        "repository": str(root),
        "revision": _git_revision(root),
        "dirty": _git_dirty(root),
        "policy": policy,
        "policy_selected": selected,
        "adapter": adapter_path if adapter else None,
        "publication_system": bool(adapter.get("publication_system", False)),
        "surface_boundaries": adapter.get("surface_boundaries", {}),
        "source_ownership": {
            "authored_indexes": sorted(indexes),
            "generated_indexes": sorted(generated),
            "authoritative_inventories": inventories,
            "curated_shortcuts": sorted(_configured_paths(adapter, "curated_shortcuts")),
        },
        "indexes": indexes,
        "inventories": inventories,
        "expected_documents": expected,
        "classification": _classify(root, indexes, expected, adapter, generated),
        "plan": [{key: value for key, value in item.items() if key != "content"} for item in plan],
        "applied": applied,
        "exclusions": sorted(
            _configured_paths(adapter, "explicit_exclusions")
            | _configured_paths(adapter, "closed_inventories")
        ),
        "notes": sorted(adapter_errors + inventory_errors + policy_notes),
        "validation": validation,
    }


def _text_report(report: dict[str, Any]) -> str:
    lines = [
        f"repository: {report['repository']}",
        f"revision: {report['revision']}",
        "policy: "
        f"profile={'selected' if report['policy']['profile_selected'] else 'unselected'}, "
        f"skill={'selected' if report['policy']['skill_selected'] else 'unselected'}",
        "inventories: "
        f"{len(report['inventories'])}; "
        f"expected documents: {len(report['expected_documents'])}; "
        f"indexes: {len(report['indexes'])}",
        f"publication system: {'yes' if report['publication_system'] else 'no'}",
        "classifications:",
    ]
    for item in report["classification"]:
        lines.append(f"  {item['classification']}: {item['index']} — {item['reason']}")
    lines.append("plan:")
    for item in report["plan"]:
        lines.append(f"  {item['action']}: {item['path']} — {item['reason']}")
    for item in report["applied"]:
        lines.append(f"applied: {item}")
    for item in report["exclusions"]:
        lines.append(f"excluded: {item}")
    for item in report["notes"]:
        lines.append(f"note: {item}")
    validation = report["validation"]
    lines.append(f"validation: {'pass' if validation['valid'] else 'fail'}")
    for item in validation["errors"]:
        lines.append(f"  error: {item}")
    for item in validation["warnings"]:
        lines.append(f"  warning: {item}")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--adapter", default=ADAPTER_NAME)
    parser.add_argument("--policy", default=POLICY_NAME)
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--format", choices=("text", "json"), default="text")
    args = parser.parse_args(argv)
    report = run(args.root, adapter_path=args.adapter, policy_path=args.policy, apply=args.apply)
    if args.format == "json":
        print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))
    else:
        print(_text_report(report))
    if args.apply and not report["policy_selected"]:
        return 2
    return 0 if report["validation"]["valid"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
