from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORPUS = ROOT / "tests/fixtures/progressive-discovery"
SCRIPT = ROOT / "skills/maintain-progressive-discovery/scripts/maintain_progressive_discovery.py"


def _load_skill():
    spec = importlib.util.spec_from_file_location("maintain_progressive_discovery", SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _fixture(name: str) -> Path:
    return CORPUS / name


def test_evaluation_corpus_covers_representative_layouts() -> None:
    expected = {
        "simple-docs",
        "deep-nested",
        "meaningful-skipping",
        "generated-docs",
        "closed-inventory",
        "curated-shortcuts",
        "stale-missing-links",
        "provider-consumer",
        "no-publication-consumer",
        "consumer-unselected",
        "dirty-generated-target",
        "plan-apply-toctou",
        "orphan-nested-index",
        "authored-generated-target",
        "retired-generated-index",
        "expected-document-addition",
    }
    actual = {path.name for path in CORPUS.iterdir() if path.is_dir()}
    assert expected <= actual


def test_distributed_skill_keeps_agent_skill_frontmatter_first() -> None:
    text = (ROOT / "skills/maintain-progressive-discovery/SKILL.md").read_text(
        encoding="utf-8"
    )

    assert text.startswith("---\n")
    assert "agent-policy-generated: true" in text


def test_distributed_skill_uses_the_repository_skill_contract_sections() -> None:
    text = (ROOT / "skills/maintain-progressive-discovery/SKILL.md").read_text(
        encoding="utf-8"
    )
    for heading in (
        "## Purpose",
        "## Use when",
        "## Do not use when",
        "## Canonical authorities",
        "## Inputs",
        "## Stop conditions",
        "## Evidence to report",
    ):
        assert heading in text


def test_unselected_consumer_does_not_receive_progressive_discovery_rules() -> None:
    report = _load_skill().run(_fixture("consumer-unselected"))

    assert report["policy_selected"] is False
    assert report["policy"]["profile_selected"] is False
    assert report["policy"]["skill_selected"] is False
    assert report["plan"] == []
    assert report["validation"]["valid"] is True


def test_selected_consumer_detects_stale_and_missing_discovery() -> None:
    report = _load_skill().run(_fixture("stale-missing-links"))
    errors = "\n".join(report["validation"]["errors"])

    assert report["policy_selected"] is True
    assert "missing link target" in errors
    assert "expected-document coverage" in errors
    assert any(item["action"] == "update" for item in report["plan"])


def test_generated_index_apply_is_deterministic_and_idempotent(tmp_path: Path) -> None:
    source = _fixture("generated-docs")
    target = tmp_path / source.name
    shutil.copytree(source, target)
    skill = _load_skill()

    before = skill.run(target)
    assert any(item["action"] == "create" for item in before["plan"])
    assert not (target / "generated/index.md").exists()

    applied = skill.run(target, apply=True)
    assert "create generated/index.md" in applied["applied"]
    generated = (target / "generated/index.md").read_text(encoding="utf-8")
    assert "generated by maintain-progressive-discovery" in generated
    assert applied["validation"]["valid"] is True
    assert applied["result"] == "NO_UPDATE_REQUIRED"

    _commit_generated_target(target)

    second = skill.run(target, apply=True)
    assert second["applied"] == []
    assert second["validation"]["valid"] is True
    assert second["result"] == "NO_UPDATE_REQUIRED"
    assert (target / "generated/index.md").read_text(encoding="utf-8") == generated


def _commit_generated_target(target: Path) -> None:
    subprocess.run(["git", "init", "-q", str(target)], check=True)
    subprocess.run(["git", "-C", str(target), "config", "user.email", "test@example.invalid"], check=True)
    subprocess.run(["git", "-C", str(target), "config", "user.name", "Test"], check=True)
    subprocess.run(["git", "-C", str(target), "add", "."], check=True)
    subprocess.run(["git", "-C", str(target), "commit", "-qm", "fixture"], check=True)


def test_dirty_generated_target_requires_authority_and_is_not_overwritten(tmp_path: Path) -> None:
    target = tmp_path / "generated-docs"
    shutil.copytree(_fixture("generated-docs"), target)
    skill = _load_skill()
    skill.run(target, apply=True)
    _commit_generated_target(target)
    generated = target / "generated/index.md"
    generated.write_text("<!-- generated by maintain-progressive-discovery -->\n# Human edit\n", encoding="utf-8")

    report = skill.run(target, apply=True)

    assert report["result"] == "AUTHORITY_NEEDED"
    assert report["applied"] == []
    assert "Human edit" in generated.read_text(encoding="utf-8")


def test_apply_refuses_target_changed_after_plan(tmp_path: Path) -> None:
    target = tmp_path / "generated-docs"
    shutil.copytree(_fixture("generated-docs"), target)
    skill = _load_skill()
    skill.run(target, apply=True)
    _commit_generated_target(target)
    catalog = target / "docs/catalog.json"
    (target / "docs/three.md").write_text("# Three\n", encoding="utf-8")
    catalog.write_text(
        json.dumps(
            {"documents": [{"path": "docs/one.md"}, {"path": "docs/two.md"}, {"path": "docs/three.md"}]}
        ),
        encoding="utf-8",
    )
    adapter, _ = skill._load_adapter(target, ".progressive-discovery.json")
    plan = skill._plan(
        target,
        adapter,
        skill._index_paths(target, adapter),
        skill._expected_documents(target, adapter, skill._discover_inventory_paths(target, adapter))[0],
        skill._generated_specs(adapter),
        skill._policy_state(skill._yaml_policy(target, ".agent-policy.yml")[0]),
    )
    generated = target / "generated/index.md"
    generated.write_text("<!-- generated by maintain-progressive-discovery -->\n# Changed after plan\n", encoding="utf-8")

    applied, blockers = skill._apply(target, plan, skill._policy_state(skill._yaml_policy(target, ".agent-policy.yml")[0]))

    assert applied == []
    assert blockers and "changed since plan" in blockers[0]


def test_machine_result_distinguishes_selected_and_unselected_consumers() -> None:
    skill = _load_skill()
    assert skill.run(_fixture("simple-docs"))["result"] == "NO_UPDATE_REQUIRED"
    assert skill.run(_fixture("consumer-unselected"))["result"] == "NOT_APPLICABLE"


def test_closed_inventory_and_curated_shortcuts_are_preserved() -> None:
    skill = _load_skill()
    closed = skill.run(_fixture("closed-inventory"))
    curated = skill.run(_fixture("curated-shortcuts"))

    closed_dirs = {item["directory"]: item for item in closed["classification"]}
    assert "vendor/closed" not in closed_dirs
    assert closed["validation"]["valid"] is True
    shortcut = next(
        item for item in curated["classification"] if item["directory"] == "docs/reference"
    )
    assert shortcut["classification"] == "index-unnecessary"
    assert curated["validation"]["valid"] is True


def test_surface_separation_and_no_publication_are_reported_without_invention() -> None:
    skill = _load_skill()
    provider = skill.run(_fixture("provider-consumer"))
    consumer = skill.run(_fixture("no-publication-consumer"))

    assert provider["surface_boundaries"]["provider-maintenance"] == [
        "docs/provider-maintenance.md"
    ]
    assert provider["surface_boundaries"]["consumer-distributed"] == ["docs/consumer-guide.md"]
    assert provider["publication_system"] is True
    assert consumer["publication_system"] is False
    assert consumer["validation"]["valid"] is True
    assert any(
        "publication system not declared" in item for item in consumer["validation"]["warnings"]
    )


def test_report_is_json_serializable_and_records_revision() -> None:
    report = _load_skill().run(_fixture("simple-docs"))

    json.dumps(report)
    assert report["revision"]
    assert report["inventories"] == ["docs/catalog.json"]
    assert report["expected_documents"] == [
        "docs/getting-started.md",
        "docs/reference.md",
    ]
