from __future__ import annotations

import ast
import ctypes
import os
import textwrap
from pathlib import Path

import pytest

from agent_policy import generated_mutation as mutation
from agent_policy.commands import render

GENERATED = b"<!-- generated by agent-policy -->\ncontent\n"
REPLACEMENT = b"<!-- generated by agent-policy -->\nreplacement\n"
AUTHORED = b"authored bytes must survive\n"


def _supported() -> bool:
    libc = ctypes.CDLL(None, use_errno=True)
    return (
        hasattr(os, "O_NOFOLLOW")
        and hasattr(os, "O_DIRECTORY")
        and all(operation in os.supports_dir_fd for operation in (os.open, os.mkdir, os.unlink))
        and getattr(libc, "renameat2", None) is not None
    )


pytestmark = pytest.mark.skipif(
    not _supported(),
    reason="generated mutation safety requires descriptor-relative renameat2 support",
)


def _owns_generated(content: bytes) -> bool:
    return content.startswith(b"<!-- generated by agent-policy -->")


def _write_spec(content: bytes) -> mutation.WriteSpec:
    return mutation.WriteSpec(content=content, owns_existing=_owns_generated)


def _delete_spec(content: bytes) -> mutation.DeleteSpec:
    return mutation.DeleteSpec(expected=content, owns_existing=_owns_generated)


def _apply(
    root: Path,
    writes: dict[str, mutation.WriteSpec],
    deletes: dict[str, mutation.DeleteSpec] | None = None,
    *,
    lock: bytes = b"lock\n",
    lock_path: str = ".agent-policy.lock",
) -> None:
    mutation.apply_generated_mutations(
        root,
        writes,
        {} if deletes is None else deletes,
        lock_path=lock_path,
        lock=mutation.WriteSpec(lock, lambda _content: True),
    )


def _holding_directories(root: Path) -> list[Path]:
    return sorted(
        path
        for path in root.iterdir()
        if path.is_dir() and path.name.startswith(".agent-policy-mutation-")
    )


_DESTRUCTIVE_METHODS = {
    "unlink",
    "remove",
    "rmdir",
    "rename",
    "replace",
    "move",
    "rmtree",
}
_DESTRUCTIVE_MODULES = {"os", "shutil"}


def _assert_no_unapproved_destructive_calls(source: str) -> None:
    tree = ast.parse(textwrap.dedent(source))
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        function = node.func
        if isinstance(function, ast.Name) and function.id in _DESTRUCTIVE_METHODS:
            raise AssertionError(f"unapproved destructive call: {function.id}")
        if not isinstance(function, ast.Attribute):
            continue
        if function.attr not in _DESTRUCTIVE_METHODS:
            continue
        value = function.value
        if isinstance(value, ast.Name) and value.id in _DESTRUCTIVE_MODULES:
            raise AssertionError(f"unapproved destructive call: {value.id}.{function.attr}")
        if isinstance(value, ast.Call) and isinstance(value.func, ast.Name):
            if value.func.id == "Path":
                raise AssertionError(f"unapproved Path destructive call: {function.attr}")
        if isinstance(value, (ast.Name, ast.Attribute)):
            raise AssertionError(f"unapproved path-method destructive call: {function.attr}")


def test_inventory_and_renderer_boundary_are_structural() -> None:
    expected_operations = {
        ("generated-create", "_native_rename_noreplace"),
        ("generated-replace", "_native_rename_noreplace"),
        ("obsolete-delete", "_delete_private"),
        ("rollback-restore", "_restore_private"),
        ("rollback-remove", "_delete_private"),
        ("rollback-directory-remove", "_remove_created_directory"),
        ("lock-update", "_write"),
        ("operation-private-cleanup", "_close_holding"),
    }
    actual_operations = {
        (item["operation"], item["primitive"])
        for item in mutation.MUTATION_INVENTORY
    }
    assert actual_operations == expected_operations

    _assert_no_unapproved_destructive_calls(
        Path(render.__file__).read_text(encoding="utf-8")
    )


@pytest.mark.parametrize(
    "source",
    [
        "os.replace(source, target)",
        "os.rename(source, target)",
        "os.unlink(target)",
        "os.remove(target)",
        "os.rmdir(target)",
        "shutil.move(source, target)",
        "shutil.rmtree(target)",
        "target.unlink()",
        "target.rename(other)",
        "target.replace(other)",
        "target.rmdir()",
        "Path('x').unlink()",
        "Path('x').rename('y')",
        "Path('x').replace('y')",
    ],
)
def test_structural_gate_rejects_representative_bypasses(source: str) -> None:
    with pytest.raises(AssertionError):
        _assert_no_unapproved_destructive_calls(source)


def _replace_parent(root: Path, relative: str, content: bytes = AUTHORED) -> None:
    parent = root / relative
    old = root / f"{relative}.old"
    parent.rename(old)
    parent.mkdir()
    (parent / "target.md").write_bytes(content)


@pytest.mark.parametrize("operation", ["create", "replace", "delete"])
def test_parent_replacement_at_mutation_boundary_fails_closed(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    operation: str,
) -> None:
    nested = tmp_path / "nested"
    nested.mkdir()
    target = nested / "target.md"
    if operation in {"replace", "delete"}:
        target.write_bytes(GENERATED)
    original = mutation._native_rename_noreplace
    injected = False

    def replace_parent(
        source_fd: int, source: str, destination_fd: int, destination: str
    ) -> None:
        nonlocal injected
        if not injected and (
            destination == "target.md" or source == "target.md"
        ):
            nested.rename(tmp_path / "nested.old")
            nested.mkdir()
            (nested / "target.md").write_bytes(AUTHORED)
            injected = True
        original(source_fd, source, destination_fd, destination)

    monkeypatch.setattr(mutation, "_native_rename_noreplace", replace_parent)
    if operation == "create":
        writes = {"nested/target.md": _write_spec(GENERATED)}
        deletes = {}
    elif operation == "replace":
        writes = {"nested/target.md": _write_spec(REPLACEMENT)}
        deletes = {}
    else:
        writes = {}
        deletes = {"nested/target.md": _delete_spec(GENERATED)}

    with pytest.raises(mutation.MutationSafetyError):
        _apply(tmp_path, writes, deletes)

    assert injected
    assert (nested / "target.md").read_bytes() == AUTHORED


def test_ancestor_replacement_fails_closed_before_lock_claim(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    ancestor = tmp_path / "one"
    nested = ancestor / "two"
    nested.mkdir(parents=True)
    (nested / "target.md").write_bytes(GENERATED)
    original = mutation._native_rename_noreplace
    injected = False

    def replace_ancestor(
        source_fd: int, source: str, destination_fd: int, destination: str
    ) -> None:
        nonlocal injected
        if source == "target.md" and not injected:
            ancestor.rename(tmp_path / "one.old")
            ancestor.mkdir()
            (ancestor / "two").mkdir()
            (ancestor / "two" / "target.md").write_bytes(AUTHORED)
            injected = True
        original(source_fd, source, destination_fd, destination)

    monkeypatch.setattr(mutation, "_native_rename_noreplace", replace_ancestor)
    with pytest.raises(mutation.MutationSafetyError):
        _apply(tmp_path, {"one/two/target.md": _write_spec(REPLACEMENT)})

    assert injected
    assert (ancestor / "two" / "target.md").read_bytes() == AUTHORED
    assert not (tmp_path / ".agent-policy.lock").exists()


def test_lock_parent_replacement_is_not_claimed_as_success(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    lock_parent = tmp_path / "locks"
    lock_parent.mkdir()
    (lock_parent / "policy.lock").write_bytes(b"old-lock\n")
    original = mutation._native_rename_noreplace
    injected = False

    def replace_lock_parent(
        source_fd: int, source: str, destination_fd: int, destination: str
    ) -> None:
        nonlocal injected
        if source == "policy.lock" and not injected:
            lock_parent.rename(tmp_path / "locks.old")
            lock_parent.mkdir()
            (lock_parent / "policy.lock").write_bytes(AUTHORED)
            injected = True
        original(source_fd, source, destination_fd, destination)

    monkeypatch.setattr(mutation, "_native_rename_noreplace", replace_lock_parent)
    with pytest.raises(mutation.MutationSafetyError):
        _apply(
            tmp_path,
            {"target.md": _write_spec(GENERATED)},
            lock_path="locks/policy.lock",
            lock=b"new-lock\n",
        )

    assert injected
    assert (lock_parent / "policy.lock").read_bytes() == AUTHORED
    assert not (tmp_path / "target.md").exists()


def test_created_parent_replacement_during_rollback_is_retained(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    original_rename = mutation._native_rename_noreplace
    failed_second_install = False

    def fail_second_install(
        source_fd: int, source: str, destination_fd: int, destination: str
    ) -> None:
        nonlocal failed_second_install
        if destination == "second.md" and not failed_second_install:
            (tmp_path / destination).write_bytes(AUTHORED)
            failed_second_install = True
        original_rename(source_fd, source, destination_fd, destination)

    monkeypatch.setattr(mutation, "_native_rename_noreplace", fail_second_install)
    original_detach = mutation._Transaction._detach_owned_public
    parent_replaced = False

    def replace_created_parent(
        transaction: mutation._Transaction, record: mutation._Record
    ) -> str:
        nonlocal parent_replaced
        if record.binding.relative == "nested/first.md" and not parent_replaced:
            parent = tmp_path / "nested"
            parent.rename(tmp_path / "nested.old")
            parent.mkdir()
            (parent / "first.md").write_bytes(AUTHORED)
            parent_replaced = True
        return original_detach(transaction, record)

    monkeypatch.setattr(
        mutation._Transaction,
        "_detach_owned_public",
        replace_created_parent,
    )
    with pytest.raises(mutation.MutationSafetyError):
        _apply(
            tmp_path,
            {
                "nested/first.md": _write_spec(GENERATED),
                "second.md": _write_spec(GENERATED),
            },
        )

    assert failed_second_install and parent_replaced
    assert (tmp_path / "nested" / "first.md").read_bytes() == AUTHORED
    assert (tmp_path / "second.md").read_bytes() == AUTHORED


def test_create_refuses_a_concurrent_creator_at_install_boundary(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    original = mutation._native_rename_noreplace
    injected = False

    def create_competitor(
        source_fd: int, source: str, destination_fd: int, destination: str
    ) -> None:
        nonlocal injected
        if destination == "created.md" and not injected:
            (tmp_path / destination).write_bytes(AUTHORED)
            injected = True
        original(source_fd, source, destination_fd, destination)

    monkeypatch.setattr(mutation, "_native_rename_noreplace", create_competitor)

    with pytest.raises(mutation.MutationSafetyError, match="created concurrently"):
        _apply(tmp_path, {"created.md": _write_spec(GENERATED)})

    assert injected
    assert (tmp_path / "created.md").read_bytes() == AUTHORED
    assert not (tmp_path / ".agent-policy.lock").exists()


def test_replace_detaches_and_preserves_a_replacement_after_validation(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _apply(tmp_path, {"target.md": _write_spec(GENERATED)})
    original = mutation._native_rename_noreplace
    injected = False

    def replace_before_detach(
        source_fd: int, source: str, destination_fd: int, destination: str
    ) -> None:
        nonlocal injected
        if source == "target.md" and not injected:
            (tmp_path / source).write_bytes(AUTHORED)
            injected = True
        original(source_fd, source, destination_fd, destination)

    monkeypatch.setattr(mutation, "_native_rename_noreplace", replace_before_detach)

    with pytest.raises(mutation.MutationSafetyError, match="content or ownership"):
        _apply(tmp_path, {"target.md": _write_spec(REPLACEMENT)})

    assert injected
    assert (tmp_path / "target.md").read_bytes() == AUTHORED
    assert (tmp_path / ".agent-policy.lock").exists()


def test_obsolete_delete_detaches_and_preserves_a_replacement(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _apply(tmp_path, {"obsolete.md": _write_spec(GENERATED)})
    original = mutation._native_rename_noreplace
    injected = False

    def replace_before_delete(
        source_fd: int, source: str, destination_fd: int, destination: str
    ) -> None:
        nonlocal injected
        if source == "obsolete.md" and not injected:
            (tmp_path / source).write_bytes(AUTHORED)
            injected = True
        original(source_fd, source, destination_fd, destination)

    monkeypatch.setattr(mutation, "_native_rename_noreplace", replace_before_delete)

    with pytest.raises(mutation.MutationSafetyError, match="content or ownership"):
        _apply(tmp_path, {}, {"obsolete.md": _delete_spec(GENERATED)})

    assert injected
    assert (tmp_path / "obsolete.md").read_bytes() == AUTHORED


def test_obsolete_delete_preserves_remove_then_recreate(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _apply(tmp_path, {"obsolete.md": _write_spec(GENERATED)})
    original = mutation._native_rename_noreplace
    injected = False

    def remove_then_recreate(
        source_fd: int, source: str, destination_fd: int, destination: str
    ) -> None:
        nonlocal injected
        if source == "obsolete.md" and not injected:
            (tmp_path / source).unlink()
            (tmp_path / source).write_bytes(AUTHORED)
            injected = True
        original(source_fd, source, destination_fd, destination)

    monkeypatch.setattr(mutation, "_native_rename_noreplace", remove_then_recreate)

    with pytest.raises(mutation.MutationSafetyError):
        _apply(tmp_path, {}, {"obsolete.md": _delete_spec(GENERATED)})

    assert injected
    assert (tmp_path / "obsolete.md").read_bytes() == AUTHORED


def test_lock_create_refuses_a_concurrent_creator(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    original = mutation._native_rename_noreplace
    injected = False

    def create_lock_competitor(
        source_fd: int, source: str, destination_fd: int, destination: str
    ) -> None:
        nonlocal injected
        if destination == ".agent-policy.lock" and not injected:
            (tmp_path / destination).write_bytes(AUTHORED)
            injected = True
        original(source_fd, source, destination_fd, destination)

    monkeypatch.setattr(mutation, "_native_rename_noreplace", create_lock_competitor)

    with pytest.raises(mutation.MutationSafetyError, match="created concurrently"):
        _apply(tmp_path, {"new.md": _write_spec(GENERATED)})

    assert injected
    assert (tmp_path / ".agent-policy.lock").read_bytes() == AUTHORED
    assert not (tmp_path / "new.md").exists()


@pytest.mark.parametrize("record_action", ["create", "replace"])
@pytest.mark.parametrize("takeover_mode", ["replace", "same-inode"])
def test_rollback_never_clobbers_a_concurrent_takeover(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    record_action: str,
    takeover_mode: str,
) -> None:
    if record_action == "replace":
        _apply(tmp_path, {"first.md": _write_spec(GENERATED)})
        first_before = GENERATED
        first_write = REPLACEMENT
    else:
        first_before = None
        first_write = GENERATED

    original_install = mutation._native_rename_noreplace
    install_failed = False

    def fail_second_install(
        source_fd: int, source: str, destination_fd: int, destination: str
    ) -> None:
        nonlocal install_failed
        if destination == "second.md" and not install_failed:
            (tmp_path / destination).write_bytes(AUTHORED)
            install_failed = True
        original_install(source_fd, source, destination_fd, destination)

    monkeypatch.setattr(mutation, "_native_rename_noreplace", fail_second_install)
    original_detach = mutation._Transaction._detach_owned_public
    takeover_injected = False

    def take_over_before_rollback(self: mutation._Transaction, record: mutation._Record) -> str:
        nonlocal takeover_injected
        if record.binding.relative == "first.md" and not takeover_injected:
            if takeover_mode == "same-inode":
                (tmp_path / "first.md").write_bytes(AUTHORED)
            else:
                replacement = tmp_path / "first.md.replacement"
                replacement.write_bytes(AUTHORED)
                replacement.replace(tmp_path / "first.md")
            takeover_injected = True
        return original_detach(self, record)

    monkeypatch.setattr(mutation._Transaction, "_detach_owned_public", take_over_before_rollback)

    with pytest.raises(mutation.MutationSafetyError):
        _apply(
            tmp_path,
            {"first.md": _write_spec(first_write), "second.md": _write_spec(GENERATED)},
        )

    assert install_failed and takeover_injected
    assert (tmp_path / "first.md").read_bytes() == AUTHORED
    if first_before is None:
        assert (tmp_path / "second.md").read_bytes() == AUTHORED


def test_symlink_target_is_not_accepted_without_an_explicit_alias(
    tmp_path: Path,
) -> None:
    target = tmp_path / "target.md"
    target.write_bytes(GENERATED)
    (tmp_path / "link.md").symlink_to(target)

    with pytest.raises(mutation.MutationSafetyError, match="symlinked"):
        _apply(tmp_path, {"link.md": _write_spec(REPLACEMENT)})


def test_lock_replacement_is_bound_and_rolls_back_prior_output(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _apply(tmp_path, {"target.md": _write_spec(GENERATED)}, lock=b"old-lock\n")
    original = mutation._native_rename_noreplace
    injected = False

    def replace_lock_before_detach(
        source_fd: int, source: str, destination_fd: int, destination: str
    ) -> None:
        nonlocal injected
        if source == ".agent-policy.lock" and not injected:
            (tmp_path / source).write_bytes(AUTHORED)
            injected = True
        original(source_fd, source, destination_fd, destination)

    monkeypatch.setattr(mutation, "_native_rename_noreplace", replace_lock_before_detach)

    with pytest.raises(mutation.MutationSafetyError, match="content or ownership"):
        _apply(tmp_path, {"target.md": _write_spec(REPLACEMENT)}, lock=b"new-lock\n")

    assert injected
    assert (tmp_path / ".agent-policy.lock").read_bytes() == AUTHORED
    assert (tmp_path / "target.md").read_bytes() == GENERATED


def _seed_two_generated_outputs(root: Path) -> None:
    _apply(root, {"first.md": _write_spec(GENERATED), "second.md": _write_spec(GENERATED)})


@pytest.mark.parametrize("failing_cleanup", ["first.md", "second.md"])
def test_post_commit_cleanup_failure_never_rolls_back_discarded_backups(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    failing_cleanup: str,
) -> None:
    _seed_two_generated_outputs(tmp_path)
    original = mutation._Transaction._delete_private

    def fail_during_cleanup(
        transaction: mutation._Transaction,
        name: str,
        expected_identity: tuple[int, int],
        relative: str,
        expected_content: bytes | None = None,
    ) -> None:
        if (
            transaction.phase == mutation.TransactionPhase.POST_COMMIT_CLEANUP
            and relative == failing_cleanup
        ):
            raise OSError("injected post-commit cleanup failure")
        original(transaction, name, expected_identity, relative, expected_content)

    monkeypatch.setattr(mutation._Transaction, "_delete_private", fail_during_cleanup)

    with pytest.raises(mutation.MutationSafetyError) as error:
        _apply(
            tmp_path,
            {"first.md": _write_spec(REPLACEMENT), "second.md": _write_spec(REPLACEMENT)},
        )

    assert error.value.phase == mutation.TransactionPhase.FAILED_POST_COMMIT
    assert error.value.retained
    assert (tmp_path / "first.md").read_bytes() == REPLACEMENT
    assert (tmp_path / "second.md").read_bytes() == REPLACEMENT
    assert _holding_directories(tmp_path)


def test_post_commit_cleanup_does_not_invoke_rollback(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _seed_two_generated_outputs(tmp_path)
    original = mutation._Transaction._delete_private
    rollback_called = False

    def fail_cleanup(
        transaction: mutation._Transaction,
        name: str,
        expected_identity: tuple[int, int],
        relative: str,
        expected_content: bytes | None = None,
    ) -> None:
        if (
            transaction.phase == mutation.TransactionPhase.POST_COMMIT_CLEANUP
            and relative == "second.md"
        ):
            raise OSError("injected cleanup failure")
        original(transaction, name, expected_identity, relative, expected_content)

    def forbidden_rollback(*_args: object, **_kwargs: object) -> None:
        nonlocal rollback_called
        rollback_called = True
        raise AssertionError("post-commit cleanup must not invoke rollback")

    monkeypatch.setattr(mutation._Transaction, "_delete_private", fail_cleanup)
    monkeypatch.setattr(mutation._Transaction, "_rollback_record", forbidden_rollback)

    with pytest.raises(mutation.MutationSafetyError):
        _apply(
            tmp_path,
            {"first.md": _write_spec(REPLACEMENT), "second.md": _write_spec(REPLACEMENT)},
        )

    assert not rollback_called
    assert (tmp_path / "first.md").read_bytes() == REPLACEMENT
    assert (tmp_path / "second.md").read_bytes() == REPLACEMENT


@pytest.mark.parametrize("target", ["first.md", "second.md"])
def test_public_output_change_during_post_commit_cleanup_fails_final_validation(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    target: str,
) -> None:
    _seed_two_generated_outputs(tmp_path)
    original = mutation._Transaction._delete_private
    changed = False

    def change_public_output(
        transaction: mutation._Transaction,
        name: str,
        expected_identity: tuple[int, int],
        relative: str,
        expected_content: bytes | None = None,
    ) -> None:
        nonlocal changed
        if (
            transaction.phase == mutation.TransactionPhase.POST_COMMIT_CLEANUP
            and relative == target
            and not changed
        ):
            (tmp_path / target).write_bytes(AUTHORED)
            changed = True
        original(transaction, name, expected_identity, relative, expected_content)

    monkeypatch.setattr(mutation._Transaction, "_delete_private", change_public_output)

    with pytest.raises(mutation.MutationSafetyError, match="post-commit public state") as error:
        _apply(
            tmp_path,
            {"first.md": _write_spec(REPLACEMENT), "second.md": _write_spec(REPLACEMENT)},
        )

    assert changed
    assert error.value.phase == mutation.TransactionPhase.FAILED_POST_COMMIT
    assert (tmp_path / target).read_bytes() == AUTHORED


def test_public_lock_change_during_post_commit_cleanup_fails_final_validation(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _seed_two_generated_outputs(tmp_path)
    original = mutation._Transaction._delete_private
    changed = False

    def change_lock(
        transaction: mutation._Transaction,
        name: str,
        expected_identity: tuple[int, int],
        relative: str,
        expected_content: bytes | None = None,
    ) -> None:
        nonlocal changed
        if (
            transaction.phase == mutation.TransactionPhase.POST_COMMIT_CLEANUP
            and relative == "first.md"
            and not changed
        ):
            (tmp_path / ".agent-policy.lock").write_bytes(AUTHORED)
            changed = True
        original(transaction, name, expected_identity, relative, expected_content)

    monkeypatch.setattr(mutation._Transaction, "_delete_private", change_lock)

    with pytest.raises(mutation.MutationSafetyError, match="post-commit public state"):
        _apply(
            tmp_path,
            {"first.md": _write_spec(REPLACEMENT), "second.md": _write_spec(REPLACEMENT)},
        )

    assert changed
    assert (tmp_path / ".agent-policy.lock").read_bytes() == AUTHORED


def test_deleted_path_recreated_during_post_commit_cleanup_is_retained(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _apply(tmp_path, {"obsolete.md": _write_spec(GENERATED)})
    original = mutation._Transaction._delete_private
    recreated = False

    def recreate_deleted_path(
        transaction: mutation._Transaction,
        name: str,
        expected_identity: tuple[int, int],
        relative: str,
        expected_content: bytes | None = None,
    ) -> None:
        nonlocal recreated
        if (
            transaction.phase == mutation.TransactionPhase.POST_COMMIT_CLEANUP
            and relative == "obsolete.md"
            and not recreated
        ):
            (tmp_path / relative).write_bytes(AUTHORED)
            recreated = True
        original(transaction, name, expected_identity, relative, expected_content)

    monkeypatch.setattr(mutation._Transaction, "_delete_private", recreate_deleted_path)

    with pytest.raises(mutation.MutationSafetyError, match="post-commit public state"):
        _apply(tmp_path, {}, {"obsolete.md": _delete_spec(GENERATED)})

    assert recreated
    assert (tmp_path / "obsolete.md").read_bytes() == AUTHORED


def test_pre_commit_failure_restores_all_records_and_reports_rollback_phase(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _seed_two_generated_outputs(tmp_path)

    def fail_before_commit(_transaction: mutation._Transaction) -> None:
        raise mutation.MutationSafetyError("injected pre-commit validation failure")

    monkeypatch.setattr(mutation._Transaction, "_check_record_bindings", fail_before_commit)

    with pytest.raises(mutation.MutationSafetyError) as error:
        _apply(
            tmp_path,
            {"first.md": _write_spec(REPLACEMENT), "second.md": _write_spec(REPLACEMENT)},
        )

    assert error.value.phase == mutation.TransactionPhase.FAILED_ROLLED_BACK
    assert not error.value.retained
    assert (tmp_path / "first.md").read_bytes() == GENERATED
    assert (tmp_path / "second.md").read_bytes() == GENERATED
    assert (tmp_path / ".agent-policy.lock").read_bytes() == b"lock\n"
