from __future__ import annotations

import ast
import ctypes
import os
from pathlib import Path

import pytest

from agent_policy import generated_mutation as mutation
from agent_policy.commands import render

GENERATED = b"<!-- generated by agent-policy -->\ncontent\n"
REPLACEMENT = b"<!-- generated by agent-policy -->\nreplacement\n"
AUTHORED = b"authored bytes must survive\n"


def _supported() -> bool:
    libc = ctypes.CDLL(None, use_errno=True)
    return (
        hasattr(os, "O_NOFOLLOW")
        and hasattr(os, "O_DIRECTORY")
        and all(operation in os.supports_dir_fd for operation in (os.open, os.mkdir, os.unlink))
        and getattr(libc, "renameat2", None) is not None
    )


pytestmark = pytest.mark.skipif(
    not _supported(),
    reason="generated mutation safety requires descriptor-relative renameat2 support",
)


def _owns_generated(content: bytes) -> bool:
    return content.startswith(b"<!-- generated by agent-policy -->")


def _write_spec(content: bytes) -> mutation.WriteSpec:
    return mutation.WriteSpec(content=content, owns_existing=_owns_generated)


def _delete_spec(content: bytes) -> mutation.DeleteSpec:
    return mutation.DeleteSpec(expected=content, owns_existing=_owns_generated)


def _apply(
    root: Path,
    writes: dict[str, mutation.WriteSpec],
    deletes: dict[str, mutation.DeleteSpec] | None = None,
    *,
    lock: bytes = b"lock\n",
) -> None:
    mutation.apply_generated_mutations(
        root,
        writes,
        {} if deletes is None else deletes,
        lock_path=".agent-policy.lock",
        lock=mutation.WriteSpec(lock, lambda _content: True),
    )


def test_inventory_and_renderer_boundary_are_structural() -> None:
    expected_operations = {
        ("generated-create", "_native_rename_noreplace"),
        ("generated-replace", "_native_rename_noreplace"),
        ("obsolete-delete", "_delete_private"),
        ("rollback-restore", "_restore_private"),
        ("rollback-remove", "_delete_private"),
        ("rollback-directory-remove", "_remove_created_directory"),
        ("lock-update", "_write"),
        ("operation-private-cleanup", "_close_holding"),
    }
    actual_operations = {
        (item["operation"], item["primitive"])
        for item in mutation.MUTATION_INVENTORY
    }
    assert actual_operations == expected_operations

    tree = ast.parse(Path(render.__file__).read_text(encoding="utf-8"))
    forbidden = {
        ("os", "replace"),
        ("os", "rename"),
        ("os", "unlink"),
        ("os", "remove"),
        ("os", "rmdir"),
    }
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call) or not isinstance(node.func, ast.Attribute):
            continue
        if (
            isinstance(node.func.value, ast.Name)
            and (node.func.value.id, node.func.attr) in forbidden
        ):
            raise AssertionError(
                f"renderer bypasses the approved mutation boundary: {node.func.value.id}."
                f"{node.func.attr}"
            )
        if node.func.attr in {"unlink", "rename"} and isinstance(node.func.value, ast.Attribute):
            if node.func.value.attr == "Path":
                raise AssertionError("renderer uses a path-based destructive mutation")


def test_create_refuses_a_concurrent_creator_at_install_boundary(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    original = mutation._native_rename_noreplace
    injected = False

    def create_competitor(
        source_fd: int, source: str, destination_fd: int, destination: str
    ) -> None:
        nonlocal injected
        if destination == "created.md" and not injected:
            (tmp_path / destination).write_bytes(AUTHORED)
            injected = True
        original(source_fd, source, destination_fd, destination)

    monkeypatch.setattr(mutation, "_native_rename_noreplace", create_competitor)

    with pytest.raises(mutation.MutationSafetyError, match="created concurrently"):
        _apply(tmp_path, {"created.md": _write_spec(GENERATED)})

    assert injected
    assert (tmp_path / "created.md").read_bytes() == AUTHORED
    assert not (tmp_path / ".agent-policy.lock").exists()


def test_replace_detaches_and_preserves_a_replacement_after_validation(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _apply(tmp_path, {"target.md": _write_spec(GENERATED)})
    original = mutation._native_rename_noreplace
    injected = False

    def replace_before_detach(
        source_fd: int, source: str, destination_fd: int, destination: str
    ) -> None:
        nonlocal injected
        if source == "target.md" and not injected:
            (tmp_path / source).write_bytes(AUTHORED)
            injected = True
        original(source_fd, source, destination_fd, destination)

    monkeypatch.setattr(mutation, "_native_rename_noreplace", replace_before_detach)

    with pytest.raises(mutation.MutationSafetyError, match="content or ownership"):
        _apply(tmp_path, {"target.md": _write_spec(REPLACEMENT)})

    assert injected
    assert (tmp_path / "target.md").read_bytes() == AUTHORED
    assert (tmp_path / ".agent-policy.lock").exists()


def test_obsolete_delete_detaches_and_preserves_a_replacement(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _apply(tmp_path, {"obsolete.md": _write_spec(GENERATED)})
    original = mutation._native_rename_noreplace
    injected = False

    def replace_before_delete(
        source_fd: int, source: str, destination_fd: int, destination: str
    ) -> None:
        nonlocal injected
        if source == "obsolete.md" and not injected:
            (tmp_path / source).write_bytes(AUTHORED)
            injected = True
        original(source_fd, source, destination_fd, destination)

    monkeypatch.setattr(mutation, "_native_rename_noreplace", replace_before_delete)

    with pytest.raises(mutation.MutationSafetyError, match="content or ownership"):
        _apply(tmp_path, {}, {"obsolete.md": _delete_spec(GENERATED)})

    assert injected
    assert (tmp_path / "obsolete.md").read_bytes() == AUTHORED


def test_obsolete_delete_preserves_remove_then_recreate(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _apply(tmp_path, {"obsolete.md": _write_spec(GENERATED)})
    original = mutation._native_rename_noreplace
    injected = False

    def remove_then_recreate(
        source_fd: int, source: str, destination_fd: int, destination: str
    ) -> None:
        nonlocal injected
        if source == "obsolete.md" and not injected:
            (tmp_path / source).unlink()
            (tmp_path / source).write_bytes(AUTHORED)
            injected = True
        original(source_fd, source, destination_fd, destination)

    monkeypatch.setattr(mutation, "_native_rename_noreplace", remove_then_recreate)

    with pytest.raises(mutation.MutationSafetyError):
        _apply(tmp_path, {}, {"obsolete.md": _delete_spec(GENERATED)})

    assert injected
    assert (tmp_path / "obsolete.md").read_bytes() == AUTHORED


def test_lock_create_refuses_a_concurrent_creator(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    original = mutation._native_rename_noreplace
    injected = False

    def create_lock_competitor(
        source_fd: int, source: str, destination_fd: int, destination: str
    ) -> None:
        nonlocal injected
        if destination == ".agent-policy.lock" and not injected:
            (tmp_path / destination).write_bytes(AUTHORED)
            injected = True
        original(source_fd, source, destination_fd, destination)

    monkeypatch.setattr(mutation, "_native_rename_noreplace", create_lock_competitor)

    with pytest.raises(mutation.MutationSafetyError, match="created concurrently"):
        _apply(tmp_path, {"new.md": _write_spec(GENERATED)})

    assert injected
    assert (tmp_path / ".agent-policy.lock").read_bytes() == AUTHORED
    assert not (tmp_path / "new.md").exists()


@pytest.mark.parametrize("record_action", ["create", "replace"])
@pytest.mark.parametrize("takeover_mode", ["replace", "same-inode"])
def test_rollback_never_clobbers_a_concurrent_takeover(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    record_action: str,
    takeover_mode: str,
) -> None:
    if record_action == "replace":
        _apply(tmp_path, {"first.md": _write_spec(GENERATED)})
        first_before = GENERATED
        first_write = REPLACEMENT
    else:
        first_before = None
        first_write = GENERATED

    original_install = mutation._native_rename_noreplace
    install_failed = False

    def fail_second_install(
        source_fd: int, source: str, destination_fd: int, destination: str
    ) -> None:
        nonlocal install_failed
        if destination == "second.md" and not install_failed:
            (tmp_path / destination).write_bytes(AUTHORED)
            install_failed = True
        original_install(source_fd, source, destination_fd, destination)

    monkeypatch.setattr(mutation, "_native_rename_noreplace", fail_second_install)
    original_detach = mutation._Transaction._detach_owned_public
    takeover_injected = False

    def take_over_before_rollback(self: mutation._Transaction, record: mutation._Record) -> str:
        nonlocal takeover_injected
        if record.binding.relative == "first.md" and not takeover_injected:
            if takeover_mode == "same-inode":
                (tmp_path / "first.md").write_bytes(AUTHORED)
            else:
                replacement = tmp_path / "first.md.replacement"
                replacement.write_bytes(AUTHORED)
                replacement.replace(tmp_path / "first.md")
            takeover_injected = True
        return original_detach(self, record)

    monkeypatch.setattr(mutation._Transaction, "_detach_owned_public", take_over_before_rollback)

    with pytest.raises(mutation.MutationSafetyError):
        _apply(
            tmp_path,
            {"first.md": _write_spec(first_write), "second.md": _write_spec(GENERATED)},
        )

    assert install_failed and takeover_injected
    assert (tmp_path / "first.md").read_bytes() == AUTHORED
    if first_before is None:
        assert (tmp_path / "second.md").read_bytes() == AUTHORED


def test_symlink_target_is_not_accepted_without_an_explicit_alias(
    tmp_path: Path,
) -> None:
    target = tmp_path / "target.md"
    target.write_bytes(GENERATED)
    (tmp_path / "link.md").symlink_to(target)

    with pytest.raises(mutation.MutationSafetyError, match="symlinked"):
        _apply(tmp_path, {"link.md": _write_spec(REPLACEMENT)})


def test_lock_replacement_is_bound_and_rolls_back_prior_output(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _apply(tmp_path, {"target.md": _write_spec(GENERATED)}, lock=b"old-lock\n")
    original = mutation._native_rename_noreplace
    injected = False

    def replace_lock_before_detach(
        source_fd: int, source: str, destination_fd: int, destination: str
    ) -> None:
        nonlocal injected
        if source == ".agent-policy.lock" and not injected:
            (tmp_path / source).write_bytes(AUTHORED)
            injected = True
        original(source_fd, source, destination_fd, destination)

    monkeypatch.setattr(mutation, "_native_rename_noreplace", replace_lock_before_detach)

    with pytest.raises(mutation.MutationSafetyError, match="content or ownership"):
        _apply(tmp_path, {"target.md": _write_spec(REPLACEMENT)}, lock=b"new-lock\n")

    assert injected
    assert (tmp_path / ".agent-policy.lock").read_bytes() == AUTHORED
    assert (tmp_path / "target.md").read_bytes() == GENERATED
