from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORPUS = ROOT / "tests/fixtures/progressive-discovery"
SCRIPT = ROOT / "skills/maintain-progressive-discovery/scripts/maintain_progressive_discovery.py"


def _load_skill():
    spec = importlib.util.spec_from_file_location("maintain_progressive_discovery", SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _fixture(name: str) -> Path:
    return CORPUS / name


def test_evaluation_corpus_covers_representative_layouts() -> None:
    expected = {
        "simple-docs",
        "deep-nested",
        "meaningful-skipping",
        "generated-docs",
        "closed-inventory",
        "curated-shortcuts",
        "stale-missing-links",
        "provider-consumer",
        "no-publication-consumer",
        "consumer-unselected",
        "dirty-generated-target",
        "plan-apply-toctou",
        "orphan-nested-index",
        "authored-generated-target",
        "retired-generated-index",
        "expected-document-addition",
    }
    actual = {path.name for path in CORPUS.iterdir() if path.is_dir()}
    assert expected <= actual


def test_distributed_skill_keeps_agent_skill_frontmatter_first() -> None:
    text = (ROOT / "skills/maintain-progressive-discovery/SKILL.md").read_text(encoding="utf-8")

    assert text.startswith("---\n")
    assert "agent-policy-generated: true" in text


def test_distributed_skill_uses_the_repository_skill_contract_sections() -> None:
    text = (ROOT / "skills/maintain-progressive-discovery/SKILL.md").read_text(encoding="utf-8")
    for heading in (
        "## Purpose",
        "## Use when",
        "## Do not use when",
        "## Canonical authorities",
        "## Inputs",
        "## Stop conditions",
        "## Evidence to report",
    ):
        assert heading in text


def test_unselected_consumer_does_not_receive_progressive_discovery_rules() -> None:
    report = _load_skill().run(_fixture("consumer-unselected"))

    assert report["policy_selected"] is False
    assert report["policy"]["profile_selected"] is False
    assert report["policy"]["skill_selected"] is False
    assert report["plan"] == []
    assert report["validation"]["valid"] is True


def test_selected_consumer_detects_stale_and_missing_discovery() -> None:
    report = _load_skill().run(_fixture("stale-missing-links"))
    errors = "\n".join(report["validation"]["errors"])

    assert report["policy_selected"] is True
    assert "missing link target" in errors
    assert "expected-document coverage" in errors
    assert any(item["action"] == "update" for item in report["plan"])


def test_generated_index_apply_is_deterministic_and_idempotent(tmp_path: Path) -> None:
    source = _fixture("generated-docs")
    target = tmp_path / source.name
    shutil.copytree(source, target)
    _commit_generated_target(target)
    skill = _load_skill()

    before = skill.run(target)
    assert any(item["action"] == "create" for item in before["plan"])
    assert not (target / "generated/index.md").exists()

    applied = skill.run(target, apply=True)
    assert "create generated/index.md" in applied["applied"]
    generated = (target / "generated/index.md").read_text(encoding="utf-8")
    assert "generated by maintain-progressive-discovery" in generated
    assert applied["validation"]["valid"] is True
    assert applied["result"] == "NO_UPDATE_REQUIRED"

    second = skill.run(target, apply=True)
    assert second["applied"] == []
    assert second["validation"]["valid"] is True
    assert second["result"] == "NO_UPDATE_REQUIRED"
    assert (target / "generated/index.md").read_text(encoding="utf-8") == generated


def _commit_generated_target(target: Path) -> None:
    subprocess.run(["git", "init", "-q", str(target)], check=True)
    subprocess.run(
        ["git", "-C", str(target), "config", "user.email", "test@example.invalid"], check=True
    )
    subprocess.run(["git", "-C", str(target), "config", "user.name", "Test"], check=True)
    subprocess.run(["git", "-C", str(target), "add", "."], check=True)
    subprocess.run(["git", "-C", str(target), "commit", "-qm", "fixture"], check=True)


def test_dirty_generated_target_requires_authority_and_is_not_overwritten(tmp_path: Path) -> None:
    target = tmp_path / "generated-docs"
    shutil.copytree(_fixture("generated-docs"), target)
    _commit_generated_target(target)
    skill = _load_skill()
    skill.run(target, apply=True)
    _commit_generated_target(target)
    generated = target / "generated/index.md"
    generated.write_text(
        "<!-- generated by maintain-progressive-discovery -->\n# Human edit\n", encoding="utf-8"
    )

    report = skill.run(target, apply=True)

    assert report["result"] == "AUTHORITY_NEEDED"
    assert report["applied"] == []
    assert "Human edit" in generated.read_text(encoding="utf-8")


def test_apply_refuses_target_changed_after_plan(tmp_path: Path) -> None:
    target = tmp_path / "generated-docs"
    shutil.copytree(_fixture("generated-docs"), target)
    _commit_generated_target(target)
    skill = _load_skill()
    skill.run(target, apply=True)
    _commit_generated_target(target)
    catalog = target / "docs/catalog.json"
    (target / "docs/three.md").write_text("# Three\n", encoding="utf-8")
    catalog.write_text(
        json.dumps(
            {
                "documents": [
                    {"path": "docs/one.md"},
                    {"path": "docs/two.md"},
                    {"path": "docs/three.md"},
                ]
            }
        ),
        encoding="utf-8",
    )
    adapter, _ = skill._load_adapter(target, ".progressive-discovery.json")
    plan = skill._plan(
        target,
        adapter,
        skill._index_paths(target, adapter),
        skill._expected_documents(
            target, adapter, skill._discover_inventory_paths(target, adapter)
        )[0],
        skill._generated_specs(adapter),
        skill._policy_state(skill._yaml_policy(target, ".agent-policy.yml")[0]),
    )
    generated = target / "generated/index.md"
    generated.write_text(
        "<!-- generated by maintain-progressive-discovery -->\n# Changed after plan\n",
        encoding="utf-8",
    )

    applied, blockers = skill._apply(
        target, plan, skill._policy_state(skill._yaml_policy(target, ".agent-policy.yml")[0])
    )

    assert applied == []
    assert blockers and "changed since plan" in blockers[0]


def test_machine_result_distinguishes_selected_and_unselected_consumers() -> None:
    skill = _load_skill()
    assert skill.run(_fixture("simple-docs"))["result"] == "NO_UPDATE_REQUIRED"
    assert skill.run(_fixture("consumer-unselected"))["result"] == "NOT_APPLICABLE"


def test_closed_inventory_and_curated_shortcuts_are_preserved() -> None:
    skill = _load_skill()
    closed = skill.run(_fixture("closed-inventory"))
    curated = skill.run(_fixture("curated-shortcuts"))

    closed_dirs = {item["directory"]: item for item in closed["classification"]}
    assert "vendor/closed" not in closed_dirs
    assert closed["validation"]["valid"] is True
    shortcut = next(
        item for item in curated["classification"] if item["directory"] == "docs/reference"
    )
    assert shortcut["classification"] == "index-unnecessary"
    assert curated["validation"]["valid"] is True


def test_surface_separation_and_no_publication_are_reported_without_invention() -> None:
    skill = _load_skill()
    provider = skill.run(_fixture("provider-consumer"))
    consumer = skill.run(_fixture("no-publication-consumer"))

    assert provider["surface_boundaries"]["provider-maintenance"] == [
        "docs/provider-maintenance.md"
    ]
    assert provider["surface_boundaries"]["consumer-distributed"] == ["docs/consumer-guide.md"]
    assert provider["publication_system"] is True
    assert consumer["publication_system"] is False
    assert consumer["validation"]["valid"] is True
    assert any(
        "publication system not declared" in item for item in consumer["validation"]["warnings"]
    )


def test_report_is_json_serializable_and_records_revision() -> None:
    report = _load_skill().run(_fixture("simple-docs"))

    json.dumps(report)
    assert report["revision"]
    assert report["inventories"] == ["docs/catalog.json"]
    assert report["expected_documents"] == [
        "docs/getting-started.md",
        "docs/reference.md",
    ]


def test_rechecks_each_target_after_global_preflight(tmp_path, monkeypatch):
    skill = _load_skill()
    target = tmp_path / "repository"
    target.mkdir()
    first, second = target / "first.md", target / "second.md"
    original = skill.GENERATED_MARKER + "\n# Original\n"
    for path in (first, second):
        path.write_text(original)
    _commit_generated_target(target)
    policy = {"profile_selected": True, "skill_selected": True}
    for action in ("regenerate", "delete"):
        plan = [{"action": action, "kind": "generated", "path": path.name,
                 "content": original + "\n", "snapshot": skill._target_state(target, path.name)}
                for path in (first, second)]
        real_state = skill._target_state
        reads = []
        def changing_state(root, relative, real_state=real_state, reads=reads):
            state = real_state(root, relative)
            reads.append(relative)
            if len(reads) == 2:
                second.write_text("# Concurrent authored edit\n")
            return state
        with monkeypatch.context() as patch:
            patch.setattr(skill, "_target_state", changing_state)
            applied, errors = skill._apply(target, plan, policy)
        assert errors and "changed since plan" in errors[0]
        assert applied == [f"{action} first.md"]
        assert second.read_text() == "# Concurrent authored edit\n"
        subprocess.run(["git", "-C", str(target), "restore", "first.md", "second.md"], check=True)


def test_cli_apply_refusals_exit_nonzero(tmp_path):
    import sys

    for case in ("dirty", "changed-after-plan", "authored", "retired"):
        target = tmp_path / case
        shutil.copytree(_fixture("generated-docs"), target)
        _commit_generated_target(target)
        skill = _load_skill()
        skill.run(target, apply=True)
        _commit_generated_target(target)
        generated = target / "generated/index.md"
        command = [sys.executable, str(SCRIPT)]
        if case == "dirty":
            generated.write_text(skill.GENERATED_MARKER + "\n# Dirty human content\n")
        elif case == "authored":
            generated.write_text(generated.read_text().replace(skill.GENERATED_MARKER, ""))
        elif case == "retired":
            retired = target / "retired/index.md"
            retired.parent.mkdir()
            retired.write_text(skill.GENERATED_MARKER + "\n# Retired\n")
            adapter = target / ".progressive-discovery.json"
            data = json.loads(adapter.read_text())
            data["remove_generated_indexes"] = ["retired/index.md"]
            data.setdefault("excluded_paths", []).append("retired")
            adapter.write_text(json.dumps(data))
        else:
            generated.write_text(skill.GENERATED_MARKER + "\n# Stale\n")
            subprocess.run(["git", "-C", str(target), "add", "generated/index.md"], check=True)
            subprocess.run(["git", "-C", str(target), "commit", "-qm", "stale"], check=True)
            # Exercise main and its process exit after an actual post-plan change.
            harness = '''import importlib.util, sys
from pathlib import Path
spec = importlib.util.spec_from_file_location("skill", sys.argv.pop(1))
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
original = module._apply
def change_after_plan(root, plan, policy):
    item = next(item for item in plan if item["action"] == "regenerate")
    (root / item["path"]).write_text(item["content"])
    return original(root, plan, policy)
module._apply = change_after_plan
raise SystemExit(module.main())
'''
            command = [sys.executable, "-c", harness, str(SCRIPT)]
        result = subprocess.run(command + ["--root", str(target), "--apply", "--format", "json"],
                                capture_output=True, text=True)
        report = json.loads(result.stdout)
        assert report["result"] == "AUTHORITY_NEEDED", (case, report)
        assert report["applied"] == []
        assert result.returncode != 0, (case, report)


def test_unreadable_or_missing_declared_sources_fail_closed(tmp_path):
    for case in ('adapter', 'adapter-shape', 'inventory', 'document', 'orphan'):
        root = tmp_path / case
        shutil.copytree(_fixture('simple-docs'), root)
        adapter_path = root / '.progressive-discovery.json'
        adapter = json.loads(adapter_path.read_text())
        if case == 'adapter':
            adapter_path.write_text('{broken')
        elif case == 'adapter-shape':
            adapter['generated_indexes'] = {'generated/index.md': False}
            adapter_path.write_text(json.dumps(adapter))
        elif case == 'inventory':
            adapter['authoritative_inventories'] = ['missing.json']
            adapter_path.write_text(json.dumps(adapter))
        elif case == 'document':
            (root / 'declared.json').write_text(
                json.dumps({'documents': [{'source': 'missing.md'}]})
            )
            adapter['authoritative_inventories'] = ['declared.json']
            adapter_path.write_text(json.dumps(adapter))
        else:
            (root / 'orphan').mkdir()
            (root / 'orphan/index.md').write_text(
                '# Orphan\n\n- [Overview](../README.md) - Overview.\n'
            )
            (root / 'README.md').write_text('# Overview\n')
        report = _load_skill().run(root)
        assert not report['validation']['valid'], (case, report)
        assert report['result'] != 'NO_UPDATE_REQUIRED', (case, report)
        if case == 'document':
            assert 'missing.md' in report['expected_documents']


def test_generated_and_retired_targets_cannot_escape_root(tmp_path):
    for mode in ('generated_indexes', 'remove_generated_indexes'):
        for kind in ('absolute', 'parent', 'symlink-parent', 'symlink-target'):
            root = tmp_path / (mode + '-' + kind)
            shutil.copytree(_fixture('simple-docs'), root)
            outside = tmp_path / (mode + '-' + kind + '-outside')
            outside.mkdir()
            sentinel = outside / 'index.md'
            sentinel.write_text('<!-- generated by maintain-progressive-discovery -->\n# Outside\n')
            if kind == 'absolute':
                target = str(sentinel)
            elif kind == 'parent':
                target = '../' + outside.name + '/index.md'
            elif kind == 'symlink-parent':
                (root / 'escape').symlink_to(outside, target_is_directory=True)
                target = 'escape/index.md'
            else:
                (root / 'escaped.md').symlink_to(sentinel)
                target = 'escaped.md'
            adapter_path = root / '.progressive-discovery.json'
            adapter = json.loads(adapter_path.read_text())
            adapter[mode] = {target: {}} if mode == 'generated_indexes' else [target]
            adapter_path.write_text(json.dumps(adapter))
            if mode == 'generated_indexes':
                sentinel.unlink()
            report = _load_skill().run(root, apply=True)
            assert report['result'] == 'AUTHORITY_NEEDED', (mode, kind, report)
            assert report['applied'] == []
            if mode == 'generated_indexes':
                assert not sentinel.exists()
            else:
                assert sentinel.read_text().endswith('# Outside\n')


def test_external_inventory_paths_do_not_hide_missing_local_sources(tmp_path):
    shutil.copytree(_fixture('simple-docs'), tmp_path / 'repository')
    root = tmp_path / 'repository'
    adapter_path = root / '.progressive-discovery.json'
    adapter = json.loads(adapter_path.read_text())
    inventory = root / 'slots.json'
    inventory.write_text(json.dumps({'source': 'foreign.md', 'destination': 'public.md'}))
    adapter['authoritative_inventories'] = ['slots.json']
    adapter['inventory_path_namespaces'] = {'slots.json': 'external'}
    adapter_path.write_text(json.dumps(adapter))
    report = _load_skill().run(root)
    assert 'foreign.md' not in report['expected_documents']
    assert 'public.md' not in report['expected_documents']
    inventory.unlink()
    report = _load_skill().run(root, apply=True)
    assert report['result'] == 'AUTHORITY_NEEDED'
    assert not report['validation']['valid']
    assert not report['applied']


def test_metadata_configuration_and_link_paths_stay_inside_repository(tmp_path):
    skill = _load_skill()
    root = tmp_path / 'repository'
    shutil.copytree(_fixture('simple-docs'), root)
    outside = tmp_path / 'outside'
    outside.mkdir()
    (outside / 'adapter.json').write_text(
        json.dumps({'generated_indexes': {'generated/index.md': {}}})
    )
    (outside / 'policy.yml').write_bytes((root / '.agent-policy.yml').read_bytes())
    (outside / 'secret.md').write_text('# Secret\n')
    (root / 'escape').symlink_to(outside, target_is_directory=True)
    for option, name in [('adapter_path', 'adapter.json'), ('policy_path', 'policy.yml')]:
        for relative in (str(outside / name), '../outside/' + name, 'escape/' + name):
            report = skill.run(root, apply=True, **{option: relative})
            assert report['result'] == 'AUTHORITY_NEEDED', (option, relative, report)
            assert not report['validation']['valid']
            assert not report['applied']
            assert not (root / 'generated/index.md').exists()
    adapter = root / '.progressive-discovery.json'
    for key in ('generated_indexes', 'remove_generated_indexes'):
        (root / '.git').mkdir(exist_ok=True)
        sentinel = root / '.git/index.md'
        sentinel.write_text(skill.GENERATED_MARKER + '\n# Metadata\n')
        before = sentinel.read_bytes()
        metadata = {'.git/index.md': {}} if key == 'generated_indexes' else ['.git/index.md']
        adapter.write_text(json.dumps({key: metadata}))
        report = skill.run(root, apply=True)
        assert report['result'] == 'AUTHORITY_NEEDED'
        assert sentinel.read_bytes() == before
        assert not report['applied']
    adapter.write_text(json.dumps({'expected_documents': ['escape/secret.md']}))
    (root / 'index.md').write_text(
        '# Root\n\n- [Secret](escape/secret.md#secret) - External file.\n'
    )
    report = skill.run(root)
    assert not report['validation']['valid']
    assert 'escape/secret.md' not in report['validation']['reachable']



def test_declarations_reject_unsafe_nonindex_and_conflicting_paths(tmp_path):
    cases = [
        {"expected_documents": ["../outside.md"]},
        {"expected_documents": ["docs/../index.md"]},
        {"expected_documents": ["/outside.md"]},
        {"root_index": "other.md"},
        {"remove_generated_indexes": False},
        {"expected_documents": False},
        {"generated_indexes": False},
        {"generated_indexes": ["new/index.md", "new/index.md"]},
        {"generated_indexes": [{"path": []}]},
        {"remove_generated_indexes": ["retired/index.md/"]},
        {"generated_indexes": {"notes/not-an-index.md": {}}},
        {"remove_generated_indexes": ["notes/not-an-index.md"]},
        {"generated_indexes": {"new/index.md": {}}, "remove_generated_indexes": ["new/index.md"]},
    ]
    for number, declaration in enumerate(cases):
        root = tmp_path / str(number)
        shutil.copytree(_fixture('simple-docs'), root)
        (root / '.progressive-discovery.json').write_text(json.dumps(
            {'authoritative_inventories': [], **declaration}
        ))
        report = _load_skill().run(root, apply=True)
        assert report['result'] == 'AUTHORITY_NEEDED', (declaration, report)
        assert not report['applied']
        assert not report['validation']['valid']
        assert not (root / 'notes/not-an-index.md').exists()
        assert not (root / 'new/index.md').exists()


def test_regenerated_content_is_immediately_idempotent_without_commit(tmp_path):
    root = tmp_path / 'repository'
    shutil.copytree(_fixture('generated-docs'), root)
    _commit_generated_target(root)
    skill = _load_skill()
    skill.run(root, apply=True)
    _commit_generated_target(root)
    path = root / 'generated/index.md'
    path.write_text(skill.GENERATED_MARKER + '\n# Old generated output\n')
    subprocess.run(['git', '-C', str(root), 'add', 'generated/index.md'], check=True)
    subprocess.run(['git', '-C', str(root), 'commit', '-qm', 'old output'], check=True)
    first = skill.run(root, apply=True)
    assert first['applied'] == ['regenerate generated/index.md']
    second = skill.run(root, apply=True)
    assert second['result'] == 'NO_UPDATE_REQUIRED'
    assert not second['applied']
    assert skill.run(root)['result'] == 'NO_UPDATE_REQUIRED'



def test_duplicate_adapter_members_are_not_silently_discarded(tmp_path):
    root = tmp_path / 'repository'
    shutil.copytree(_fixture('simple-docs'), root)
    (root / '.progressive-discovery.json').write_text(
        '{"expected_documents": ["missing.md"], "expected_documents": []}'
    )
    report = _load_skill().run(root, apply=True)
    assert report['result'] == 'AUTHORITY_NEEDED'
    assert not report['applied']
    assert any('duplicate JSON member' in error for error in report['validation']['errors'])


def test_authored_scope_exclusion_preserves_global_inventory_coverage(tmp_path):
    root = tmp_path / 'repository'
    shutil.copytree(_fixture('simple-docs'), root)
    (root / 'docs/catalog.json').write_text('{}')
    adapter_path = root / '.progressive-discovery.json'
    adapter = json.loads(adapter_path.read_text())
    adapter['expected_documents'] = ['docs/catalog.json']
    adapter.pop('intentional_no_indexes', None)
    adapter['authored_boundaries'] = ['docs']
    (root / 'docs/index.md').write_text(
        '# Documentation\n\n- [Start](getting-started.md) - Start here.\n'
        '- [Reference](reference.md) - Reference.\n'
    )
    adapter['authored_index_exclusions'] = {
        'docs/index.md': {
            'docs/catalog.json': 'Source-only inventory is linked from authority root.'
        }
    }
    adapter_path.write_text(json.dumps(adapter))
    root_index = root / 'index.md'
    original = root_index.read_text() + '\n- [Docs](docs/index.md) - Reader navigation.\n'
    root_index.write_text(original + '\n- [Catalog](docs/catalog.json) - Source inventory.\n')
    report = _load_skill().run(root)
    assert report['result'] == 'NO_UPDATE_REQUIRED', report
    assert 'docs/catalog.json' in report['expected_documents']
    assert 'docs/catalog.json' in report['validation']['reachable']
    root_index.write_text(original)
    report = _load_skill().run(root)
    assert not report['validation']['valid']
    assert report['result'] != 'NO_UPDATE_REQUIRED'


def test_inventory_paths_fail_closed_instead_of_disappearing(tmp_path):
    for number, path in enumerate(['../outside.md', '/outside.md', 'docs/a#b.md',
                                  'docs/a?b.md', '.git/config', 'docs/%61.md']):
        root = tmp_path / str(number)
        shutil.copytree(_fixture('simple-docs'), root)
        (root / 'docs/catalog.json').write_text(json.dumps({'documents': [{'path': path}]}))
        report = _load_skill().run(root, apply=True)
        assert report['result'] == 'AUTHORITY_NEEDED', (path, report)
        assert not report['applied']
        assert not report['validation']['valid']


def test_duplicate_yaml_inventory_and_policy_keys_fail_closed(tmp_path):
    for kind in ('inventory', 'policy'):
        root = tmp_path / kind
        shutil.copytree(_fixture('simple-docs'), root)
        if kind == 'inventory':
            (root / 'inventory.yml').write_text(
                'documents:\n  - docs/hidden.md\ndocuments:\n  - docs/reference.md\n'
            )
            path = root / '.progressive-discovery.json'
            data = json.loads(path.read_text())
            data['authoritative_inventories'] = ['inventory.yml']
            path.write_text(json.dumps(data))
        else:
            path = root / '.agent-policy.yml'
            path.write_text(path.read_text() + '\nskills: {}\n')
        report = _load_skill().run(root, apply=True)
        assert report['result'] == 'AUTHORITY_NEEDED', (kind, report)
        assert not report['applied']
        assert any('duplicate YAML' in error for error in report['validation']['errors'])


def test_generated_markdown_handles_significant_filename_characters(tmp_path):
    root = tmp_path / 'repository'
    shutil.copytree(_fixture('generated-docs'), root)
    _commit_generated_target(root)
    name = 'docs/a)b[c]*<x>.md'
    (root / name).write_text('# Document\n')
    path = root / '.progressive-discovery.json'
    data = json.loads(path.read_text())
    data.setdefault('expected_documents', []).append(name)
    path.write_text(json.dumps(data))
    skill = _load_skill()
    report = skill.run(root, apply=True)
    assert report['validation']['valid'], report
    assert name in report['validation']['reachable']
    assert skill.run(root)['result'] == 'NO_UPDATE_REQUIRED'


def test_authored_marker_mentions_do_not_grant_generated_ownership(tmp_path):
    for action in ('regenerate', 'delete'):
        root = tmp_path / action
        shutil.copytree(_fixture('generated-docs'), root)
        _commit_generated_target(root)
        skill = _load_skill()
        skill.run(root, apply=True)
        target = root / 'generated/index.md'
        authored = '# Authored navigation\n\nExample: ' + skill.GENERATED_MARKER + '\n'
        target.write_text(authored)
        _commit_generated_target(root)
        if action == 'delete':
            adapter = root / '.progressive-discovery.json'
            data = json.loads(adapter.read_text())
            data.pop('generated_indexes')
            data['remove_generated_indexes'] = ['generated/index.md']
            adapter.write_text(json.dumps(data))
        report = skill.run(root, apply=True)
        assert report['result'] == 'AUTHORITY_NEEDED', report
        assert report['applied'] == []
        assert target.read_text() == authored


def test_generated_inventory_scope_rejects_malformed_declarations(tmp_path):
    for number, scope in enumerate(['private/', [1], ['../private'], ['/private'],
                                    ['docs//'], ['docs/a#fragment']]):
        root = tmp_path / str(number)
        shutil.copytree(_fixture('generated-docs'), root)
        _commit_generated_target(root)
        path = root / '.progressive-discovery.json'
        data = json.loads(path.read_text())
        data['generated_indexes']['generated/index.md']['inventory'] = scope
        path.write_text(json.dumps(data))
        report = _load_skill().run(root, apply=True)
        assert report['result'] == 'AUTHORITY_NEEDED', (scope, report)
        assert not report['applied']
        assert not (root / 'generated/index.md').exists()


def test_fragment_only_links_use_the_source_index(tmp_path):
    root = tmp_path / 'repository'
    shutil.copytree(_fixture('simple-docs'), root)
    (root / 'docs/index.md').write_text('# Nested\n\n## Section\n')
    skill = _load_skill()
    for source, fragment in [('index.md', 'start-here'), ('docs/index.md', 'section')]:
        assert skill._resolve_link(root, source, '#' + fragment) == (source, None)
        _, error = skill._resolve_link(root, source, '#absent')
        assert error and 'missing fragment' in error


def test_dirty_retired_target_is_authority_needed_in_dry_run(tmp_path):
    root = tmp_path / 'repository'
    shutil.copytree(_fixture('generated-docs'), root)
    _commit_generated_target(root)
    skill = _load_skill()
    skill.run(root, apply=True)
    _commit_generated_target(root)
    path = root / '.progressive-discovery.json'
    data = json.loads(path.read_text())
    data.pop('generated_indexes')
    data['remove_generated_indexes'] = ['generated/index.md']
    path.write_text(json.dumps(data))
    (root / 'generated/index.md').write_text(skill.GENERATED_MARKER + '\n# Human change\n')
    report = skill.run(root)
    assert report['result'] == 'AUTHORITY_NEEDED', report
    assert not any(item['action'] == 'delete' for item in report['plan'])


def test_apply_refreshes_authored_reachability_after_generated_repair(tmp_path):
    root = tmp_path / 'repository'
    shutil.copytree(_fixture('generated-docs'), root)
    _commit_generated_target(root)
    (root / 'docs/index.md').write_text(
        '# Documentation\n\n- [Generated](../generated/index.md) - Generated documents.\n'
        '- [Local](local.md) - Authored document.\n'
    )
    entry = root / 'index.md'
    entry.write_text(entry.read_text() + '\n- [Docs](docs/index.md) - Authored navigation.\n')
    path = root / '.progressive-discovery.json'
    data = json.loads(path.read_text())
    data['authored_boundaries'] = ['docs']
    path.write_text(json.dumps(data))
    (root / 'docs/local.md').write_text('# Local\n')
    data['expected_documents'] = ['docs/local.md']
    data['generated_indexes']['generated/index.md']['inventory'] = ['docs/one.md', 'docs/two.md']
    path.write_text(json.dumps(data))
    skill = _load_skill()
    report = skill.run(root, apply=True)
    assert report['result'] == 'NO_UPDATE_REQUIRED', report
    assert report['applied'] == ['create generated/index.md']
    assert skill.run(root)['result'] == 'NO_UPDATE_REQUIRED'


def test_target_tracking_uses_literal_git_paths(tmp_path):
    root = tmp_path / 'repository'
    root.mkdir()
    skill = _load_skill()
    (root / 'docs-real').mkdir()
    (root / 'docs-real/index.md').write_text(skill.GENERATED_MARKER + '\n# Tracked\n')
    _commit_generated_target(root)
    (root / '.gitignore').write_text('docs*/\n')
    (root / 'docs*').mkdir()
    target = root / 'docs*/index.md'
    target.write_text(skill.GENERATED_MARKER + '\n# Untracked local file\n')
    state = skill._target_state(root, 'docs*/index.md')
    assert not state['tracked'], state
    plan = [{'action': 'delete', 'kind': 'generated', 'path': 'docs*/index.md',
             'snapshot': state, 'content': None}]
    applied, errors = skill._apply(root, plan, {'profile_selected': True, 'skill_selected': True})
    assert not applied and errors
    assert target.exists()


def test_unavailable_git_dirty_state_refuses_existing_target(tmp_path, monkeypatch):
    root = tmp_path / 'repository'
    shutil.copytree(_fixture('generated-docs'), root)
    _commit_generated_target(root)
    skill = _load_skill()
    skill.run(root, apply=True)
    target = root / 'generated/index.md'
    target.write_text(skill.GENERATED_MARKER + '\n# Old generated output\n')
    _commit_generated_target(root)
    original = subprocess.run
    def failed_status(args, *a, **kwargs):
        if 'status' in args:
            return subprocess.CompletedProcess(args, 128, stdout='', stderr='status unavailable')
        return original(args, *a, **kwargs)
    monkeypatch.setattr(subprocess, 'run', failed_status)
    before = target.read_bytes()
    for apply in (False, True):
        report = skill.run(root, apply=apply)
        assert report['result'] == 'AUTHORITY_NEEDED', report
        assert not report['applied']
        assert target.read_bytes() == before


def test_unknown_git_state_cannot_create_a_generated_target(tmp_path, monkeypatch):
    root = tmp_path / 'repository'
    shutil.copytree(_fixture('generated-docs'), root)
    _commit_generated_target(root)
    skill = _load_skill()
    original = subprocess.run
    for command in ('status', 'ls-files'):
        def failed_query(args, *a, command=command, **kwargs):
            if command in args:
                return subprocess.CompletedProcess(args, 128, stdout='', stderr='Git unavailable')
            return original(args, *a, **kwargs)
        with monkeypatch.context() as patch:
            patch.setattr(subprocess, 'run', failed_query)
            for apply in (False, True):
                report = skill.run(root, apply=apply)
                assert report['result'] == 'AUTHORITY_NEEDED', report
                assert not report['applied']
                assert not (root / 'generated/index.md').exists()


def test_git_hidden_edits_cannot_be_overwritten_or_retired(tmp_path):
    for flag in ('--assume-unchanged', '--skip-worktree'):
        for action in ('regenerate', 'delete'):
            root = tmp_path / (flag + action)
            shutil.copytree(_fixture('generated-docs'), root)
            _commit_generated_target(root)
            skill = _load_skill()
            skill.run(root, apply=True)
            _commit_generated_target(root)
            target = root / 'generated/index.md'
            subprocess.run(['git', '-C', str(root), 'update-index', flag,
                            'generated/index.md'], check=True)
            content = skill.GENERATED_MARKER + '\n# Hidden human edit\n'
            target.write_text(content)
            if action == 'delete':
                path = root / '.progressive-discovery.json'
                data = json.loads(path.read_text())
                data.pop('generated_indexes')
                data['remove_generated_indexes'] = ['generated/index.md']
                path.write_text(json.dumps(data))
            for apply in (False, True):
                report = skill.run(root, apply=apply)
                assert report['result'] == 'AUTHORITY_NEEDED', (flag, action, report)
                assert not report['applied']
                assert target.read_text() == content


def test_boundary_and_exclusion_paths_are_repository_local(tmp_path):
    keys = ('authored_boundaries', 'explicit_exclusions', 'closed_inventories',
            'curated_shortcuts', 'intentional_no_indexes')
    for key in keys:
        root = tmp_path / key
        shutil.copytree(_fixture('simple-docs'), root)
        path = root / '.progressive-discovery.json'
        data = json.loads(path.read_text())
        data[key] = ['../outside']
        path.write_text(json.dumps(data))
        report = _load_skill().run(root)
        assert report['result'] == 'AUTHORITY_NEEDED', (key, report)
        assert not report['validation']['valid']
        assert report['plan'] == []


def test_non_utf8_generated_target_returns_cli_authority_report(tmp_path):
    import sys
    for number, content in enumerate([b'\xffbinary', 
            b'<!-- generated by maintain-progressive-discovery -->\n\xffbinary']):
        root = tmp_path / str(number)
        shutil.copytree(_fixture('generated-docs'), root)
        _commit_generated_target(root)
        target = root / 'generated/index.md'
        target.parent.mkdir()
        target.write_bytes(content)
        _commit_generated_target(root)
        result = subprocess.run([sys.executable, str(SCRIPT), '--root', str(root),
                                 '--apply', '--format', 'json'], capture_output=True, text=True)
        report = json.loads(result.stdout)
        assert result.returncode != 0
        assert report['result'] == 'AUTHORITY_NEEDED'
        assert not report['applied']
        assert target.read_bytes() == content


def test_malformed_link_does_not_hide_applied_generated_changes(tmp_path):
    root = tmp_path / 'repository'
    shutil.copytree(_fixture('generated-docs'), root)
    _commit_generated_target(root)
    path = root / 'index.md'
    path.write_text(path.read_text() + '\n- [Malformed](http://[) - Invalid authority URL.\n')
    report = _load_skill().run(root, apply=True)
    assert not report['validation']['valid']
    assert report['applied'] == ['create generated/index.md']
    assert report['result'] != 'NO_UPDATE_REQUIRED'


def test_missing_yaml_parser_cannot_authorize_apply(tmp_path, monkeypatch):
    import sys
    target = tmp_path / 'consumer'
    shutil.copytree(_fixture('generated-docs'), target)
    _commit_generated_target(target)
    (target / '.agent-policy.yml').write_text(
        'metadata:\n  profiles:\n    - progressive-discovery\n'
        '  skills:\n    - maintain-progressive-discovery\n'
    )
    monkeypatch.setitem(sys.modules, 'yaml', None)
    report = _load_skill().run(target, apply=True)
    assert report['result'] == 'AUTHORITY_NEEDED'
    assert report['applied'] == []
    assert not (target / 'generated/index.md').exists()


def test_nonrendered_links_do_not_prove_reachability(tmp_path):
    skill = _load_skill()
    for number, text in enumerate((
        '# Root\n\n    [Start](docs/start.md)\n',
        '# Root\n\n<!--\n- [Start](docs/start.md)\n-->\n',
        '# Root\n\n<!-- [Start](docs/start.md) -->\n',
        '# Root\n\n```md\n- [Start](docs/start.md)\n```\n',
        '# Root\n\n`[Start](docs/start.md)`\n',
    )):
        root = tmp_path / str(number)
        root.mkdir()
        (root / 'index.md').write_text(text)
        links, issues = skill._read_index_links(root, 'index.md')
        assert not links, (text, links, issues)


def test_blank_generated_title_is_refused_before_mutation(tmp_path):
    for number, title in enumerate(('', '  ', '\n\t')):
        target = tmp_path / str(number)
        shutil.copytree(_fixture('generated-docs'), target)
        adapter_path = target / '.progressive-discovery.json'
        adapter = json.loads(adapter_path.read_text())
        adapter['generated_indexes']['generated/index.md']['title'] = title
        adapter_path.write_text(json.dumps(adapter))
        _commit_generated_target(target)
        report = _load_skill().run(target, apply=True)
        assert report['result'] == 'AUTHORITY_NEEDED'
        assert report['applied'] == []
        assert not (target / 'generated/index.md').exists()


def test_visible_links_survive_non_navigation_comment_and_code_prose(tmp_path):
    (tmp_path / 'index.md').write_text(
        '# Root\n\n<!-- maintenance -->\n- [The `start` guide](docs/start.md) - `code`.\n'
    )
    links, _ = _load_skill()._read_index_links(tmp_path, 'index.md')
    assert [link['target'] for link in links] == ['docs/start.md']


def test_active_root_cannot_be_retired(tmp_path):
    target = tmp_path / 'consumer'
    shutil.copytree(_fixture('generated-docs'), target)
    root = target / 'index.md'
    root.write_text(_load_skill().GENERATED_MARKER + '\n# Root\n')
    adapter = target / '.progressive-discovery.json'
    data = json.loads(adapter.read_text())
    data['remove_generated_indexes'] = ['index.md']
    adapter.write_text(json.dumps(data))
    _commit_generated_target(target)
    before = root.read_bytes()
    report = _load_skill().run(target, apply=True)
    assert report['result'] == 'AUTHORITY_NEEDED'
    assert report['applied'] == []
    assert root.read_bytes() == before


def test_blank_generated_section_is_refused_before_mutation(tmp_path):
    for number, section in enumerate(('', '  ', '\n\t')):
        target = tmp_path / str(number)
        shutil.copytree(_fixture('generated-docs'), target)
        adapter = target / '.progressive-discovery.json'
        data = json.loads(adapter.read_text())
        data['generated_indexes']['generated/index.md']['section'] = section
        adapter.write_text(json.dumps(data))
        _commit_generated_target(target)
        report = _load_skill().run(target, apply=True)
        assert report['result'] == 'AUTHORITY_NEEDED'
        assert report['applied'] == []
        assert not (target / 'generated/index.md').exists()


def test_nonrendered_headings_and_anchors_cannot_satisfy_fragments(tmp_path):
    skill = _load_skill()
    for wrapper in ('<!--\n%s\n-->', '```markdown\n%s\n```', '~~~\n%s\n~~~',
                    '    %s', '  \t%s', '```\n```not-a-closing-fence\n%s\n```'):
        for fake in ('# Fake', '<a id="fake"></a>'):
            (tmp_path / 'doc.md').write_text('# Real\n\n' + wrapper % fake + '\n')
            _, error = skill._resolve_link(tmp_path, 'index.md', 'doc.md#fake')
            assert error and 'missing fragment' in error, (wrapper, fake)
    (tmp_path / 'doc.md').write_text('# Real `code`\n\n<a id="explicit"></a>\n')
    for fragment in ('real-code', 'explicit'):
        assert skill._resolve_link(tmp_path, 'index.md', 'doc.md#' + fragment)[1] is None
    (tmp_path / 'doc.md').write_text('# Real\n\n`<a id="fake"></a>`\n')
    assert skill._resolve_link(tmp_path, 'index.md', 'doc.md#fake')[1]


def test_fragment_requires_real_anchor_with_exact_identity(tmp_path):
    skill = _load_skill()
    (tmp_path / 'doc.md').write_text('# Visible\n\nprose id="fake"\n')
    for fragment in ('fake', 'Visible', 'visible!'):
        assert skill._resolve_link(tmp_path, 'index.md', 'doc.md#' + fragment)[1]
    assert skill._resolve_link(tmp_path, 'index.md', 'doc.md#visible')[1] is None


def test_schema_invalid_policy_cannot_authorize_generated_apply(tmp_path):
    import yaml
    for number, mutate in enumerate((
        lambda config: config.pop('schema_version'),
        lambda config: config.pop('outputs'),
        lambda config: config.update(profiles=['progressive-discovery']),
        lambda config: config['toolchain'].update(revision='policy'),
    )):
        target = tmp_path / str(number)
        shutil.copytree(_fixture('generated-docs'), target)
        path = target / '.agent-policy.yml'
        config = yaml.safe_load(path.read_text())
        mutate(config)
        path.write_text(yaml.safe_dump(config))
        _commit_generated_target(target)
        report = _load_skill().run(target, apply=True)
        assert report['result'] == 'AUTHORITY_NEEDED'
        assert report['applied'] == []
        assert not (target / 'generated/index.md').exists()


def test_hidden_blocks_do_not_invalidate_visible_index_grammar(tmp_path):
    (tmp_path / 'index.md').write_text(
        '# Root\n\n<!-- Maintenance note -->\n\n```md\n# Example\n'
        '- [Fake](missing.md)\n```\n\n- [Visible](doc.md)\n'
    )
    links, issues = _load_skill()._read_index_links(tmp_path, 'index.md')
    assert issues == []
    assert [link['target'] for link in links] == ['doc.md']


def test_git_execution_failure_reports_unknown_target_state(tmp_path, monkeypatch):
    target = tmp_path / 'consumer'
    shutil.copytree(_fixture('generated-docs'), target)
    _commit_generated_target(target)
    skill = _load_skill()
    real_run = subprocess.run
    def unavailable(command, *args, **kwargs):
        if command[0] == 'git':
            raise OSError('git cannot be executed')
        return real_run(command, *args, **kwargs)
    monkeypatch.setattr(subprocess, 'run', unavailable)
    for apply in (False, True):
        report = skill.run(target, apply=apply)
        assert report['result'] == 'AUTHORITY_NEEDED'
        assert report['applied'] == []
    assert not (target / 'generated/index.md').exists()


def test_setext_headings_are_valid_fragment_targets(tmp_path):
    skill = _load_skill()
    for underline in ('=====', '-----'):
        (tmp_path / 'doc.md').write_text('Title\n' + underline + '\n')
        assert skill._resolve_link(tmp_path, 'index.md', 'doc.md#title')[1] is None


def test_rendered_skill_embeds_the_canonical_schema_without_local_override(tmp_path):
    from agent_policy.renderer import render_skill
    generated = render_skill('maintain-progressive-discovery')
    path = tmp_path / 'standalone.py'
    path.write_text(generated['scripts/maintain_progressive_discovery.py'])
    spec = importlib.util.spec_from_file_location('rendered_discovery', path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    canonical = json.loads((ROOT / 'schemas/agent-policy.schema.json').read_text())
    assert module._policy_schema() == canonical
    (tmp_path / 'schemas').mkdir()
    (tmp_path / 'schemas/agent-policy.schema.json').write_text('{}')
    assert module._policy_schema() == canonical


def test_generated_targets_cannot_overlap_excluded_boundaries(tmp_path):
    for number, (key, boundary) in enumerate(
        (key, boundary) for key in ('explicit_exclusions', 'closed_inventories')
        for boundary in ('generated', 'generated/index.md')
    ):
        target = tmp_path / str(number)
        shutil.copytree(_fixture('generated-docs'), target)
        adapter_path = target / '.progressive-discovery.json'
        adapter = json.loads(adapter_path.read_text())
        adapter[key] = [boundary]
        adapter_path.write_text(json.dumps(adapter))
        _commit_generated_target(target)
        for apply in (False, True):
            report = _load_skill().run(target, apply=apply)
            assert report['result'] == 'AUTHORITY_NEEDED'
            assert report['applied'] == []
            assert not any(item['kind'] == 'generated' for item in report['plan'])
            assert not (target / 'generated/index.md').exists()


def test_authored_root_has_missing_and_stale_navigation_plans(tmp_path):
    for action in ('create', 'update'):
        target = tmp_path / action
        shutil.copytree(_fixture('simple-docs'), target)
        index = target / 'index.md'
        if action == 'create':
            index.unlink()
        else:
            index.write_text('# Navigation\n\n## Start\n\n'
                             '- [Start](docs/getting-started.md) - Begin.\n')
        report = _load_skill().run(target)
        assert any(item['index'] == 'index.md'
                   and item['classification'] == 'authored-index-needed'
                   for item in report['classification'])
        assert any(item['path'] == 'index.md' and item['action'] == action
                   and item['kind'] == 'authored' for item in report['plan'])


def test_generated_and_authored_ownership_are_disjoint_after_apply(tmp_path):
    shutil.copytree(_fixture('generated-docs'), tmp_path / 'repository')
    target = tmp_path / 'repository'
    _commit_generated_target(target)
    skill = _load_skill()
    for report in (skill.run(target, apply=True), skill.run(target)):
        ownership = report['source_ownership']
        assert report['result'] == 'NO_UPDATE_REQUIRED'
        assert 'generated/index.md' in ownership['generated_indexes']
        assert 'index.md' in ownership['authored_indexes']
        assert not set(ownership['authored_indexes']) & set(ownership['generated_indexes'])
