from __future__ import annotations

import json
from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class ProgressiveDiscoveryBoundaryTests(unittest.TestCase):
    def test_adapter_separates_records_from_generated_documentation(self) -> None:
        adapter = json.loads((ROOT / ".progressive-discovery.json").read_text(encoding="utf-8"))

        self.assertEqual(adapter["root_index"], "index.md")
        self.assertIn("catalog.json", adapter["authoritative_inventories"])
        self.assertIn("docs/publication-catalog.json", adapter["authoritative_inventories"])
        self.assertIn("records", adapter["closed_inventories"])
        self.assertEqual(
            adapter["generated_indexes"]["docs/resources/index.md"]["inventory"],
            ["docs/resources"],
        )
        self.assertEqual(adapter["surface_boundaries"]["consumer-distributed"], [])

    def test_root_routes_to_docs_and_generated_catalog_boundaries(self) -> None:
        root = (ROOT / "index.md").read_text(encoding="utf-8")
        docs = (ROOT / "docs/index.md").read_text(encoding="utf-8")
        self.assertIn("](docs/index.md)", root)
        self.assertIn("](resources/index.md)", docs)

    def test_generated_resource_index_has_owned_marker_and_all_records(self) -> None:
        index = (ROOT / "docs/resources/index.md").read_text(encoding="utf-8")
        self.assertIn("generated by maintain-progressive-discovery", index)
        records = json.loads((ROOT / "catalog.json").read_text(encoding="utf-8"))["records"]
        for record in records:
            self.assertIn(f"docs/resources/{record['id']}.md", index)


if __name__ == "__main__":
    unittest.main()
