import json
from pathlib import Path
import subprocess
import tempfile
import unittest

from publication_bundle.graph import (
    GRAPH_SCHEMA_VERSION,
    IndexNavigationViewerError,
    LEGACY_GRAPH_SCHEMA_VERSION,
    LEGACY_ROOT_INDEX,
    ROOT_INDEX,
    graph_diagnostics,
    load_graph,
    validate_provider_graph,
)
from integration.generate_index_navigation_base import (
    collect_provider_graph, parse_index, IndexNavigationError,
)


class ProgressiveDiscoveryGraphTests(unittest.TestCase):
    def _provider(self, root_index: str, object_id: str = 'f' * 40):
        return {
            'name': 'composition',
            'revision': 'b' * 40,
            'root_index': root_index,
            'indexes': [
                {
                    'path': root_index,
                    'title': 'Root',
                    'sections': [],
                    'depth': 0,
                    'object_id': object_id,
                }
            ],
            'edges': [],
            'diagnostics': {
                'index_count': 1,
                'edge_count': 0,
                'max_index_depth': 0,
                'cycle_edges': [],
                'multiple_parent_indexes': [],
            },
        }

    def test_current_graph_uses_authority_root_index_and_v2(self):
        provider = self._provider(ROOT_INDEX)
        validate_provider_graph(provider, provider_order=('composition',))
        self.assertEqual(GRAPH_SCHEMA_VERSION, 2)
        self.assertEqual(ROOT_INDEX, 'index.md')
        self.assertEqual(graph_diagnostics(provider['indexes'], provider['edges']), provider['diagnostics'])

    def test_legacy_graph_remains_readable_with_its_historical_root(self):
        provider = self._provider(LEGACY_ROOT_INDEX)
        validate_provider_graph(
            provider,
            provider_order=('composition',),
            root_index=LEGACY_ROOT_INDEX,
        )
        self.assertEqual(LEGACY_GRAPH_SCHEMA_VERSION, 1)

        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / 'guided-navigation.json'
            path.write_text(
                json.dumps({
                    'schema_version': LEGACY_GRAPH_SCHEMA_VERSION,
                    'repository': 'TakashiSasaki/templates',
                    'providers': [provider],
                }),
                encoding='utf-8',
            )
            self.assertEqual(
                load_graph(path, provider_order=('composition',))['schema_version'],
                LEGACY_GRAPH_SCHEMA_VERSION,
            )

    def test_generator_binds_the_new_root_and_git_blob_identity(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            subprocess.run(['git', 'init', '-q', str(root)], check=True)
            subprocess.run(
                ['git', '-C', str(root), 'config', 'user.email', 'test@example.invalid'],
                check=True,
            )
            subprocess.run(
                ['git', '-C', str(root), 'config', 'user.name', 'test'],
                check=True,
            )
            (root / 'index.md').write_text(
                '# Provider root\n\n## Start\n\n- [Documentation](docs/index.md) - Provider documents.\n',
                encoding='utf-8',
            )
            (root / 'docs').mkdir()
            (root / 'docs/index.md').write_text(
                '<!-- generated by maintain-progressive-discovery -->\n# Documentation\n',
                encoding='utf-8',
            )
            subprocess.run(['git', '-C', str(root), 'add', '.'], check=True)
            subprocess.run(['git', '-C', str(root), 'commit', '-qm', 'fixture'], check=True)

            graph = collect_provider_graph('composition', root)
            root_record = next(item for item in graph['indexes'] if item['path'] == ROOT_INDEX)
            blob = subprocess.check_output(
                ['git', '-C', str(root), 'rev-parse', 'HEAD:index.md'],
                text=True,
            ).strip()
            nested = next(item for item in graph['indexes'] if item['path'] == 'docs/index.md')
            self.assertEqual(nested['object_id'], subprocess.check_output(
                ['git', '-C', str(root), 'rev-parse', 'HEAD:docs/index.md'], text=True
            ).strip())
            self.assertEqual(graph['root_index'], ROOT_INDEX)
            self.assertEqual(root_record['object_id'], blob)
            self.assertEqual(graph['revision'], subprocess.check_output(
                ['git', '-C', str(root), 'rev-parse', 'HEAD'], text=True
            ).strip())

    def test_canonical_generated_index_marker_is_non_semantic_metadata(self):
        marker = '<!-- generated by maintain-progressive-discovery -->'
        text = '# Resources\n\n## Records\n\n- [Record](record.md) - Generated record.\n'
        marked = parse_index(marker + '\n' + text, 'index.md')
        plain = parse_index(text, 'index.md')
        self.assertEqual(marked.title, plain.title)
        self.assertEqual(marked.sections, plain.sections)
        self.assertEqual(marked.links[0].raw_target, plain.links[0].raw_target)
        self.assertEqual(marked.links[0].line, plain.links[0].line + 1)
        for malformed in ('<!-- arbitrary HTML -->\n' + text,
                          text + '\n' + marker,
                          marker + '<script>alert(1)</script>\n' + text):
            with self.subTest(text=malformed), self.assertRaises(IndexNavigationError):
                parse_index(malformed, 'index.md')

    def test_graph_schema_requires_an_exact_integer(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / 'graph.json'
            for version in (True, False, 1.0, 2.0, '1', None, [], {}):
                path.write_text(json.dumps({'schema_version': version,
                    'repository': 'TakashiSasaki/templates', 'providers': []}))
                with self.subTest(version=version), self.assertRaises(IndexNavigationViewerError):
                    load_graph(path, provider_order=())

    def test_schema_only_numeric_equality_requires_raw_graph_validation(self):
        import jsonschema
        schema = json.loads((Path(__file__).resolve().parents[1] /
                             'contracts/publication-bundle/guided-navigation.schema.json').read_text())
        graph = {'schema_version': 2, 'repository': 'TakashiSasaki/templates',
                 'providers': [self._provider(ROOT_INDEX)]}
        validator = jsonschema.Draft202012Validator(schema)
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / 'graph.json'
            for token in ('2.0', '2e0'):
                raw = json.dumps(graph).replace('"schema_version": 2', '"schema_version": ' + token)
                validator.validate(json.loads(raw))
                path.write_text(raw)
                with self.subTest(token=token), self.assertRaises(IndexNavigationViewerError):
                    load_graph(path, provider_order=('composition',))
            path.write_text(json.dumps(graph))
            self.assertEqual(load_graph(path, provider_order=('composition',))['schema_version'], 2)

    def test_declared_root_must_match_the_schema_selected_root(self):
        for wrong_root in ('docs/index.md', 'other/index.md'):
            with self.subTest(root=wrong_root), self.assertRaises(IndexNavigationViewerError):
                validate_provider_graph(self._provider(wrong_root), provider_order=('composition',), root_index=ROOT_INDEX)

    def test_published_schema_validates_provider_record_shapes(self):
        import copy
        import jsonschema
        schema = json.loads((Path(__file__).resolve().parents[1] /
                             'contracts/publication-bundle/guided-navigation.schema.json').read_text())
        validator = jsonschema.Draft202012Validator(schema)
        validator.check_schema(schema)
        graph = {'schema_version': 2, 'repository': 'TakashiSasaki/templates',
                 'providers': [self._provider(ROOT_INDEX)]}
        graph['providers'][0]['indexes'][0]['sections'] = [{'title': 'Start', 'level': 2}]
        graph['providers'][0]['edges'] = [{'source': ROOT_INDEX, 'kind': 'fragment',
            'label': 'Start', 'description': '', 'raw_target': '#start', 'target': ROOT_INDEX,
            'line': 3, 'section': 'Start', 'fragment': 'start'}]
        graph['providers'][0]['diagnostics'] = graph_diagnostics(
            graph['providers'][0]['indexes'], graph['providers'][0]['edges'])
        validate_provider_graph(graph['providers'][0], provider_order=('composition',))
        validator.validate(graph)
        cases = [('indexes', [None]), ('indexes', [{}]), ('edges', [None]),
                 ('edges', [{}]), ('diagnostics', {}),
                 ('diagnostics', dict(graph['providers'][0]['diagnostics'], cycle_edges=[None])),
                 ('diagnostics', dict(graph['providers'][0]['diagnostics'], multiple_parent_indexes=[None]))]
        for field, value in cases:
            candidate = copy.deepcopy(graph)
            candidate['providers'][0][field] = value
            with self.subTest(field=field, value=value), self.assertRaises(jsonschema.ValidationError):
                validator.validate(candidate)

    def test_v2_python_validator_enforces_schema_field_closure(self):
        import copy
        import jsonschema
        schema = json.loads((Path(__file__).resolve().parents[1] /
                             'contracts/publication-bundle/guided-navigation.schema.json').read_text())
        validator = jsonschema.Draft202012Validator(schema)
        graph = {'schema_version': 2, 'repository': 'TakashiSasaki/templates',
                 'providers': [self._provider(ROOT_INDEX)]}
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / 'graph.json'
            for location in ('graph', 'provider'):
                candidate = copy.deepcopy(graph)
                target = candidate if location == 'graph' else candidate['providers'][0]
                target['unexpected'] = True
                path.write_text(json.dumps(candidate))
                with self.subTest(location=location):
                    with self.assertRaises(jsonschema.ValidationError):
                        validator.validate(candidate)
                    with self.assertRaises(IndexNavigationViewerError):
                        loaded = load_graph(path, provider_order=('composition',))
                        validate_provider_graph(loaded['providers'][0], provider_order=('composition',))
