from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORPUS = ROOT / "tests/fixtures/progressive-discovery"
SCRIPT = ROOT / "skills/maintain-progressive-discovery/scripts/maintain_progressive_discovery.py"


def _load_skill():
    spec = importlib.util.spec_from_file_location("maintain_progressive_discovery", SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _fixture(name: str) -> Path:
    return CORPUS / name


def test_evaluation_corpus_covers_representative_layouts() -> None:
    expected = {
        "simple-docs",
        "deep-nested",
        "meaningful-skipping",
        "generated-docs",
        "closed-inventory",
        "curated-shortcuts",
        "stale-missing-links",
        "provider-consumer",
        "no-publication-consumer",
        "consumer-unselected",
        "dirty-generated-target",
        "plan-apply-toctou",
        "orphan-nested-index",
        "authored-generated-target",
        "retired-generated-index",
        "expected-document-addition",
    }
    actual = {path.name for path in CORPUS.iterdir() if path.is_dir()}
    assert expected <= actual


def test_distributed_skill_keeps_agent_skill_frontmatter_first() -> None:
    text = (ROOT / "skills/maintain-progressive-discovery/SKILL.md").read_text(encoding="utf-8")

    assert text.startswith("---\n")
    assert "agent-policy-generated: true" in text


def test_distributed_skill_uses_the_repository_skill_contract_sections() -> None:
    text = (ROOT / "skills/maintain-progressive-discovery/SKILL.md").read_text(encoding="utf-8")
    for heading in (
        "## Purpose",
        "## Use when",
        "## Do not use when",
        "## Canonical authorities",
        "## Inputs",
        "## Stop conditions",
        "## Evidence to report",
    ):
        assert heading in text


def test_unselected_consumer_does_not_receive_progressive_discovery_rules() -> None:
    report = _load_skill().run(_fixture("consumer-unselected"))

    assert report["policy_selected"] is False
    assert report["policy"]["profile_selected"] is False
    assert report["policy"]["skill_selected"] is False
    assert report["plan"] == []
    assert report["validation"]["valid"] is True


def test_selected_consumer_detects_stale_and_missing_discovery() -> None:
    report = _load_skill().run(_fixture("stale-missing-links"))
    errors = "\n".join(report["validation"]["errors"])

    assert report["policy_selected"] is True
    assert "missing link target" in errors
    assert "expected-document coverage" in errors
    assert any(item["action"] == "update" for item in report["plan"])


def test_generated_index_apply_is_deterministic_and_idempotent(tmp_path: Path) -> None:
    source = _fixture("generated-docs")
    target = tmp_path / source.name
    shutil.copytree(source, target)
    skill = _load_skill()

    before = skill.run(target)
    assert any(item["action"] == "create" for item in before["plan"])
    assert not (target / "generated/index.md").exists()

    applied = skill.run(target, apply=True)
    assert "create generated/index.md" in applied["applied"]
    generated = (target / "generated/index.md").read_text(encoding="utf-8")
    assert "generated by maintain-progressive-discovery" in generated
    assert applied["validation"]["valid"] is True
    assert applied["result"] == "NO_UPDATE_REQUIRED"

    second = skill.run(target, apply=True)
    assert second["applied"] == []
    assert second["validation"]["valid"] is True
    assert second["result"] == "NO_UPDATE_REQUIRED"
    assert (target / "generated/index.md").read_text(encoding="utf-8") == generated


def _commit_generated_target(target: Path) -> None:
    subprocess.run(["git", "init", "-q", str(target)], check=True)
    subprocess.run(
        ["git", "-C", str(target), "config", "user.email", "test@example.invalid"], check=True
    )
    subprocess.run(["git", "-C", str(target), "config", "user.name", "Test"], check=True)
    subprocess.run(["git", "-C", str(target), "add", "."], check=True)
    subprocess.run(["git", "-C", str(target), "commit", "-qm", "fixture"], check=True)


def test_dirty_generated_target_requires_authority_and_is_not_overwritten(tmp_path: Path) -> None:
    target = tmp_path / "generated-docs"
    shutil.copytree(_fixture("generated-docs"), target)
    skill = _load_skill()
    skill.run(target, apply=True)
    _commit_generated_target(target)
    generated = target / "generated/index.md"
    generated.write_text(
        "<!-- generated by maintain-progressive-discovery -->\n# Human edit\n", encoding="utf-8"
    )

    report = skill.run(target, apply=True)

    assert report["result"] == "AUTHORITY_NEEDED"
    assert report["applied"] == []
    assert "Human edit" in generated.read_text(encoding="utf-8")


def test_apply_refuses_target_changed_after_plan(tmp_path: Path) -> None:
    target = tmp_path / "generated-docs"
    shutil.copytree(_fixture("generated-docs"), target)
    skill = _load_skill()
    skill.run(target, apply=True)
    _commit_generated_target(target)
    catalog = target / "docs/catalog.json"
    (target / "docs/three.md").write_text("# Three\n", encoding="utf-8")
    catalog.write_text(
        json.dumps(
            {
                "documents": [
                    {"path": "docs/one.md"},
                    {"path": "docs/two.md"},
                    {"path": "docs/three.md"},
                ]
            }
        ),
        encoding="utf-8",
    )
    adapter, _ = skill._load_adapter(target, ".progressive-discovery.json")
    plan = skill._plan(
        target,
        adapter,
        skill._index_paths(target, adapter),
        skill._expected_documents(
            target, adapter, skill._discover_inventory_paths(target, adapter)
        )[0],
        skill._generated_specs(adapter),
        skill._policy_state(skill._yaml_policy(target, ".agent-policy.yml")[0]),
    )
    generated = target / "generated/index.md"
    generated.write_text(
        "<!-- generated by maintain-progressive-discovery -->\n# Changed after plan\n",
        encoding="utf-8",
    )

    applied, blockers = skill._apply(
        target, plan, skill._policy_state(skill._yaml_policy(target, ".agent-policy.yml")[0])
    )

    assert applied == []
    assert blockers and "changed since plan" in blockers[0]


def test_machine_result_distinguishes_selected_and_unselected_consumers() -> None:
    skill = _load_skill()
    assert skill.run(_fixture("simple-docs"))["result"] == "NO_UPDATE_REQUIRED"
    assert skill.run(_fixture("consumer-unselected"))["result"] == "NOT_APPLICABLE"


def test_closed_inventory_and_curated_shortcuts_are_preserved() -> None:
    skill = _load_skill()
    closed = skill.run(_fixture("closed-inventory"))
    curated = skill.run(_fixture("curated-shortcuts"))

    closed_dirs = {item["directory"]: item for item in closed["classification"]}
    assert "vendor/closed" not in closed_dirs
    assert closed["validation"]["valid"] is True
    shortcut = next(
        item for item in curated["classification"] if item["directory"] == "docs/reference"
    )
    assert shortcut["classification"] == "index-unnecessary"
    assert curated["validation"]["valid"] is True


def test_surface_separation_and_no_publication_are_reported_without_invention() -> None:
    skill = _load_skill()
    provider = skill.run(_fixture("provider-consumer"))
    consumer = skill.run(_fixture("no-publication-consumer"))

    assert provider["surface_boundaries"]["provider-maintenance"] == [
        "docs/provider-maintenance.md"
    ]
    assert provider["surface_boundaries"]["consumer-distributed"] == ["docs/consumer-guide.md"]
    assert provider["publication_system"] is True
    assert consumer["publication_system"] is False
    assert consumer["validation"]["valid"] is True
    assert any(
        "publication system not declared" in item for item in consumer["validation"]["warnings"]
    )


def test_report_is_json_serializable_and_records_revision() -> None:
    report = _load_skill().run(_fixture("simple-docs"))

    json.dumps(report)
    assert report["revision"]
    assert report["inventories"] == ["docs/catalog.json"]
    assert report["expected_documents"] == [
        "docs/getting-started.md",
        "docs/reference.md",
    ]


def test_rechecks_each_target_after_global_preflight(tmp_path, monkeypatch):
    skill = _load_skill()
    target = tmp_path / "repository"
    target.mkdir()
    first, second = target / "first.md", target / "second.md"
    original = skill.GENERATED_MARKER + "\n# Original\n"
    for path in (first, second):
        path.write_text(original)
    _commit_generated_target(target)
    policy = {"profile_selected": True, "skill_selected": True}
    for action in ("regenerate", "delete"):
        plan = [{"action": action, "kind": "generated", "path": path.name,
                 "content": original + "\n", "snapshot": skill._target_state(target, path.name)}
                for path in (first, second)]
        real_state = skill._target_state
        reads = []
        def changing_state(root, relative, real_state=real_state, reads=reads):
            state = real_state(root, relative)
            reads.append(relative)
            if len(reads) == 2:
                second.write_text("# Concurrent authored edit\n")
            return state
        with monkeypatch.context() as patch:
            patch.setattr(skill, "_target_state", changing_state)
            applied, errors = skill._apply(target, plan, policy)
        assert errors and "changed since plan" in errors[0]
        assert applied == [f"{action} first.md"]
        assert second.read_text() == "# Concurrent authored edit\n"
        subprocess.run(["git", "-C", str(target), "restore", "first.md", "second.md"], check=True)


def test_cli_apply_refusals_exit_nonzero(tmp_path):
    import sys

    for case in ("dirty", "changed-after-plan", "authored", "retired"):
        target = tmp_path / case
        shutil.copytree(_fixture("generated-docs"), target)
        skill = _load_skill()
        skill.run(target, apply=True)
        _commit_generated_target(target)
        generated = target / "generated/index.md"
        command = [sys.executable, str(SCRIPT)]
        if case == "dirty":
            generated.write_text(skill.GENERATED_MARKER + "\n# Dirty human content\n")
        elif case == "authored":
            generated.write_text(generated.read_text().replace(skill.GENERATED_MARKER, ""))
        elif case == "retired":
            retired = target / "retired/index.md"
            retired.parent.mkdir()
            retired.write_text(skill.GENERATED_MARKER + "\n# Retired\n")
            adapter = target / ".progressive-discovery.json"
            data = json.loads(adapter.read_text())
            data["remove_generated_indexes"] = ["retired/index.md"]
            data.setdefault("excluded_paths", []).append("retired")
            adapter.write_text(json.dumps(data))
        else:
            generated.write_text(skill.GENERATED_MARKER + "\n# Stale\n")
            subprocess.run(["git", "-C", str(target), "add", "generated/index.md"], check=True)
            subprocess.run(["git", "-C", str(target), "commit", "-qm", "stale"], check=True)
            # Exercise main and its process exit after an actual post-plan change.
            harness = '''import importlib.util, sys
from pathlib import Path
spec = importlib.util.spec_from_file_location("skill", sys.argv.pop(1))
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
original = module._apply
def change_after_plan(root, plan, policy):
    item = next(item for item in plan if item["action"] == "regenerate")
    (root / item["path"]).write_text(item["content"])
    return original(root, plan, policy)
module._apply = change_after_plan
raise SystemExit(module.main())
'''
            command = [sys.executable, "-c", harness, str(SCRIPT)]
        result = subprocess.run(command + ["--root", str(target), "--apply", "--format", "json"],
                                capture_output=True, text=True)
        report = json.loads(result.stdout)
        assert report["result"] == "AUTHORITY_NEEDED", (case, report)
        assert report["applied"] == []
        assert result.returncode != 0, (case, report)


def test_unreadable_or_missing_declared_sources_fail_closed(tmp_path):
    for case in ('adapter', 'adapter-shape', 'inventory', 'document', 'orphan'):
        root = tmp_path / case
        shutil.copytree(_fixture('simple-docs'), root)
        adapter_path = root / '.progressive-discovery.json'
        adapter = json.loads(adapter_path.read_text())
        if case == 'adapter':
            adapter_path.write_text('{broken')
        elif case == 'adapter-shape':
            adapter['generated_indexes'] = {'generated/index.md': False}
            adapter_path.write_text(json.dumps(adapter))
        elif case == 'inventory':
            adapter['authoritative_inventories'] = ['missing.json']
            adapter_path.write_text(json.dumps(adapter))
        elif case == 'document':
            (root / 'declared.json').write_text(
                json.dumps({'documents': [{'source': 'missing.md'}]})
            )
            adapter['authoritative_inventories'] = ['declared.json']
            adapter_path.write_text(json.dumps(adapter))
        else:
            (root / 'orphan').mkdir()
            (root / 'orphan/index.md').write_text(
                '# Orphan\n\n- [Overview](../README.md) - Overview.\n'
            )
            (root / 'README.md').write_text('# Overview\n')
        report = _load_skill().run(root)
        assert not report['validation']['valid'], (case, report)
        assert report['result'] != 'NO_UPDATE_REQUIRED', (case, report)
        if case == 'document':
            assert 'missing.md' in report['expected_documents']


def test_generated_and_retired_targets_cannot_escape_root(tmp_path):
    for mode in ('generated_indexes', 'remove_generated_indexes'):
        for kind in ('absolute', 'parent', 'symlink-parent', 'symlink-target'):
            root = tmp_path / (mode + '-' + kind)
            shutil.copytree(_fixture('simple-docs'), root)
            outside = tmp_path / (mode + '-' + kind + '-outside')
            outside.mkdir()
            sentinel = outside / 'index.md'
            sentinel.write_text('<!-- generated by maintain-progressive-discovery -->\n# Outside\n')
            if kind == 'absolute':
                target = str(sentinel)
            elif kind == 'parent':
                target = '../' + outside.name + '/index.md'
            elif kind == 'symlink-parent':
                (root / 'escape').symlink_to(outside, target_is_directory=True)
                target = 'escape/index.md'
            else:
                (root / 'escaped.md').symlink_to(sentinel)
                target = 'escaped.md'
            adapter_path = root / '.progressive-discovery.json'
            adapter = json.loads(adapter_path.read_text())
            adapter[mode] = {target: {}} if mode == 'generated_indexes' else [target]
            adapter_path.write_text(json.dumps(adapter))
            if mode == 'generated_indexes':
                sentinel.unlink()
            report = _load_skill().run(root, apply=True)
            assert report['result'] == 'AUTHORITY_NEEDED', (mode, kind, report)
            assert report['applied'] == []
            if mode == 'generated_indexes':
                assert not sentinel.exists()
            else:
                assert sentinel.read_text().endswith('# Outside\n')


def test_external_inventory_paths_do_not_hide_missing_local_sources(tmp_path):
    shutil.copytree(_fixture('simple-docs'), tmp_path / 'repository')
    root = tmp_path / 'repository'
    adapter_path = root / '.progressive-discovery.json'
    adapter = json.loads(adapter_path.read_text())
    inventory = root / 'slots.json'
    inventory.write_text(json.dumps({'source': 'foreign.md', 'destination': 'public.md'}))
    adapter['authoritative_inventories'] = ['slots.json']
    adapter['inventory_path_namespaces'] = {'slots.json': 'external'}
    adapter_path.write_text(json.dumps(adapter))
    report = _load_skill().run(root)
    assert 'foreign.md' not in report['expected_documents']
    assert 'public.md' not in report['expected_documents']
    inventory.unlink()
    report = _load_skill().run(root, apply=True)
    assert report['result'] == 'AUTHORITY_NEEDED'
    assert not report['validation']['valid']
    assert not report['applied']


def test_metadata_configuration_and_link_paths_stay_inside_repository(tmp_path):
    skill = _load_skill()
    root = tmp_path / 'repository'
    shutil.copytree(_fixture('simple-docs'), root)
    outside = tmp_path / 'outside'
    outside.mkdir()
    (outside / 'adapter.json').write_text(
        json.dumps({'generated_indexes': {'generated/index.md': {}}})
    )
    (outside / 'policy.yml').write_bytes((root / '.agent-policy.yml').read_bytes())
    (outside / 'secret.md').write_text('# Secret\n')
    (root / 'escape').symlink_to(outside, target_is_directory=True)
    for option, name in [('adapter_path', 'adapter.json'), ('policy_path', 'policy.yml')]:
        for relative in (str(outside / name), '../outside/' + name, 'escape/' + name):
            report = skill.run(root, apply=True, **{option: relative})
            assert report['result'] == 'AUTHORITY_NEEDED', (option, relative, report)
            assert not report['validation']['valid']
            assert not report['applied']
            assert not (root / 'generated/index.md').exists()
    adapter = root / '.progressive-discovery.json'
    for key in ('generated_indexes', 'remove_generated_indexes'):
        (root / '.git').mkdir(exist_ok=True)
        sentinel = root / '.git/index.md'
        sentinel.write_text(skill.GENERATED_MARKER + '\n# Metadata\n')
        before = sentinel.read_bytes()
        metadata = {'.git/index.md': {}} if key == 'generated_indexes' else ['.git/index.md']
        adapter.write_text(json.dumps({key: metadata}))
        report = skill.run(root, apply=True)
        assert report['result'] == 'AUTHORITY_NEEDED'
        assert sentinel.read_bytes() == before
        assert not report['applied']
    adapter.write_text(json.dumps({'expected_documents': ['escape/secret.md']}))
    (root / 'index.md').write_text(
        '# Root\n\n- [Secret](escape/secret.md#secret) - External file.\n'
    )
    report = skill.run(root)
    assert not report['validation']['valid']
    assert 'escape/secret.md' not in report['validation']['reachable']



def test_declarations_reject_unsafe_nonindex_and_conflicting_paths(tmp_path):
    cases = [
        {"expected_documents": ["../outside.md"]},
        {"expected_documents": ["docs/../index.md"]},
        {"expected_documents": ["/outside.md"]},
        {"root_index": "other.md"},
        {"remove_generated_indexes": False},
        {"expected_documents": False},
        {"generated_indexes": False},
        {"generated_indexes": ["new/index.md", "new/index.md"]},
        {"generated_indexes": [{"path": []}]},
        {"remove_generated_indexes": ["retired/index.md/"]},
        {"generated_indexes": {"notes/not-an-index.md": {}}},
        {"remove_generated_indexes": ["notes/not-an-index.md"]},
        {"generated_indexes": {"new/index.md": {}}, "remove_generated_indexes": ["new/index.md"]},
    ]
    for number, declaration in enumerate(cases):
        root = tmp_path / str(number)
        shutil.copytree(_fixture('simple-docs'), root)
        (root / '.progressive-discovery.json').write_text(json.dumps(
            {'authoritative_inventories': [], **declaration}
        ))
        report = _load_skill().run(root, apply=True)
        assert report['result'] == 'AUTHORITY_NEEDED', (declaration, report)
        assert not report['applied']
        assert not report['validation']['valid']
        assert not (root / 'notes/not-an-index.md').exists()
        assert not (root / 'new/index.md').exists()


def test_regenerated_content_is_immediately_idempotent_without_commit(tmp_path):
    root = tmp_path / 'repository'
    shutil.copytree(_fixture('generated-docs'), root)
    skill = _load_skill()
    skill.run(root, apply=True)
    _commit_generated_target(root)
    path = root / 'generated/index.md'
    path.write_text(skill.GENERATED_MARKER + '\n# Old generated output\n')
    subprocess.run(['git', '-C', str(root), 'add', 'generated/index.md'], check=True)
    subprocess.run(['git', '-C', str(root), 'commit', '-qm', 'old output'], check=True)
    first = skill.run(root, apply=True)
    assert first['applied'] == ['regenerate generated/index.md']
    second = skill.run(root, apply=True)
    assert second['result'] == 'NO_UPDATE_REQUIRED'
    assert not second['applied']
    assert skill.run(root)['result'] == 'NO_UPDATE_REQUIRED'



def test_duplicate_adapter_members_are_not_silently_discarded(tmp_path):
    root = tmp_path / 'repository'
    shutil.copytree(_fixture('simple-docs'), root)
    (root / '.progressive-discovery.json').write_text(
        '{"expected_documents": ["missing.md"], "expected_documents": []}'
    )
    report = _load_skill().run(root, apply=True)
    assert report['result'] == 'AUTHORITY_NEEDED'
    assert not report['applied']
    assert any('duplicate JSON member' in error for error in report['validation']['errors'])


def test_authored_scope_exclusion_preserves_global_inventory_coverage(tmp_path):
    root = tmp_path / 'repository'
    shutil.copytree(_fixture('simple-docs'), root)
    (root / 'docs/catalog.json').write_text('{}')
    adapter_path = root / '.progressive-discovery.json'
    adapter = json.loads(adapter_path.read_text())
    adapter['expected_documents'] = ['docs/catalog.json']
    adapter.pop('intentional_no_indexes', None)
    adapter['authored_boundaries'] = ['docs']
    (root / 'docs/index.md').write_text(
        '# Documentation\n\n- [Start](getting-started.md) - Start here.\n'
        '- [Reference](reference.md) - Reference.\n'
    )
    adapter['authored_index_exclusions'] = {
        'docs/index.md': {
            'docs/catalog.json': 'Source-only inventory is linked from authority root.'
        }
    }
    adapter_path.write_text(json.dumps(adapter))
    root_index = root / 'index.md'
    original = root_index.read_text() + '\n- [Docs](docs/index.md) - Reader navigation.\n'
    root_index.write_text(original + '\n- [Catalog](docs/catalog.json) - Source inventory.\n')
    report = _load_skill().run(root)
    assert report['result'] == 'NO_UPDATE_REQUIRED', report
    assert 'docs/catalog.json' in report['expected_documents']
    assert 'docs/catalog.json' in report['validation']['reachable']
    root_index.write_text(original)
    report = _load_skill().run(root)
    assert not report['validation']['valid']
    assert report['result'] != 'NO_UPDATE_REQUIRED'
