"""Render the Site-owned static Markdown progressive-discovery entry point."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

from publication_bundle.contract import BundleError, read_json, regular, safe_path
from publication_bundle.paths import public_path
from site_renderer.guided import index_page_url


GENERATED_MARKER = "<!-- generated by Site progressive discovery -->"
PUBLIC_PATH = re.compile(r"^/(?!/)(?!(?:[^/]+/)*\.{1,2}(?:/|$))[^%\\?#\x00-\x20]*$")


def _public_href(value: Any, field: str) -> str:
    if not isinstance(value, str) or not PUBLIC_PATH.fullmatch(value):
        raise BundleError(f"{field} must be a safe deployed absolute path")
    parsed = urlsplit(value)
    if parsed.scheme or parsed.netloc or parsed.query or parsed.fragment:
        raise BundleError(f"{field} must be a path without scheme, query, or fragment")
    return value


def _source_entries(source: dict[str, Any]) -> list[dict[str, Any]]:
    if (
        source.get("schema_version") != 1
        or not isinstance(source.get("title"), str)
        or not source["title"]
        or not isinstance(source.get("sections"), list)
        or not isinstance(source.get("provider_labels"), dict)
    ):
        raise BundleError("invalid Site progressive discovery source")
    entries: list[dict[str, Any]] = []
    for section_index, section in enumerate(source["sections"]):
        if (
            not isinstance(section, dict)
            or set(section) != {"title", "entries"}
            or not isinstance(section["title"], str)
            or not section["title"]
            or not isinstance(section["entries"], list)
        ):
            raise BundleError(f"invalid progressive discovery section {section_index}")
        for entry_index, entry in enumerate(section["entries"]):
            if (
                not isinstance(entry, dict)
                or not isinstance(entry.get("label"), str)
                or not entry["label"]
                or not isinstance(entry.get("description"), str)
                or not entry["description"]
                or ("href" not in entry and "document" not in entry)
                or ("href" in entry and "document" in entry)
            ):
                raise BundleError(
                    f"invalid progressive discovery entry {section_index}:{entry_index}"
                )
            entries.append({"section": section["title"], **entry})
    return entries


def _document_routes(documents: list[dict[str, Any]]) -> dict[tuple[str, str], str]:
    routes: dict[tuple[str, str], str] = {}
    for index, document in enumerate(documents):
        if (
            not isinstance(document, dict)
            or not isinstance(document.get("publication"), str)
            or not isinstance(document.get("document"), str)
            or not isinstance(document.get("destination"), str)
        ):
            raise BundleError(f"invalid Bundle document for progressive discovery: {index}")
        key = (document["publication"], document["document"])
        if key in routes:
            raise BundleError(f"duplicate Bundle document identity: {key[0]}:{key[1]}")
        routes[key] = public_path(document["destination"])
    return routes


def _site_documents(source: dict[str, Any], catalog: dict[str, Any]) -> list[dict[str, Any]]:
    """Resolve Site-owned routes from Site's own publication inventory."""
    routes = source.get("site_routes")
    inventory = catalog.get("documents")
    if not isinstance(routes, dict) or not routes or not isinstance(inventory, list):
        raise BundleError("missing or malformed Site route/catalog declaration")
    by_id = {}
    for record in inventory:
        if not isinstance(record, dict) or not isinstance(record.get("id"), str):
            raise BundleError("invalid Site publication catalog document")
        if record["id"] in by_id:
            raise BundleError("duplicate Site publication catalog identity")
        by_id[record["id"]] = record
    result = []
    seen = set()
    for identity, destination in routes.items():
        if identity not in by_id:
            raise BundleError(f"Site route is absent from Site catalog: {identity}")
        path = safe_path(destination)
        if (not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_./-]*\.md", str(path))
                or public_path(str(path)) in seen):
            raise BundleError(f"invalid or duplicate Site route: {destination}")
        seen.add(public_path(str(path)))
        record = by_id[identity]
        source_path = safe_path(record.get("source"))
        result.append({"publication": "site", "document": identity,
                       "source": str(source_path), "destination": str(path), "slot": True,
                       "title": identity, "primary_audience": "use" if record.get("home") else "maintain",
                       "additional_audiences": []})
    return result


def extend_site_documents(site_root: Path, documents: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Add Site-owned pages without modifying the selected immutable Bundle."""
    local = _site_documents(read_json(site_root / "progressive-discovery.json"),
                            read_json(site_root / "docs/publication-catalog.json"))
    result = list(documents)
    for record in local:
        regular(site_root, record["source"])
        for existing in result:
            if (existing["publication"], existing["document"]) == ("site", record["document"]):
                if (existing["source"], existing["destination"]) != (record["source"], record["destination"]):
                    raise BundleError("Site route conflicts with a selected slot")
            if public_path(existing["destination"]) == public_path(record["destination"]):
                if not (existing.get("slot") and existing["publication"] == "site"
                        and existing["source"] == record["source"]):
                    raise BundleError("Site route destination collision")
                break
        else:
            result.append(record)
    return result


def _resolve_entry(entry: dict[str, Any], routes: dict[tuple[str, str], str]) -> str:
    if "href" in entry:
        return _public_href(entry["href"], "progressive discovery href")
    document = entry["document"]
    if (
        not isinstance(document, dict)
        or set(document) != {"publication", "document"}
        or not isinstance(document["publication"], str)
        or not isinstance(document["document"], str)
    ):
        raise BundleError("progressive discovery document identity is invalid")
    try:
        return routes[(document["publication"], document["document"])]
    except KeyError as exc:
        raise BundleError(
            "progressive discovery document is absent from the selected Bundle: "
            f"{document['publication']}:{document['document']}"
        ) from exc


def _provider_entries(source: dict[str, Any], graph: dict[str, Any]) -> list[dict[str, str]]:
    providers = graph.get("providers") if isinstance(graph, dict) else None
    labels = source.get("provider_labels")
    if not isinstance(providers, list) or not isinstance(labels, dict):
        raise BundleError("progressive discovery requires the Bundle guided graph")
    result: list[dict[str, str]] = []
    for provider in providers:
        if (
            not isinstance(provider, dict)
            or not isinstance(provider.get("name"), str)
            or not isinstance(provider.get("root_index"), str)
        ):
            raise BundleError("invalid guided provider for progressive discovery")
        label = labels.get(provider["name"])
        if (
            not isinstance(label, dict)
            or not isinstance(label.get("label"), str)
            or not label["label"]
            or not isinstance(label.get("description"), str)
            or not label["description"]
        ):
            raise BundleError(
                f"Site progressive discovery source has no label for provider {provider['name']}"
            )
        result.append(
            {
                "label": label["label"],
                "href": index_page_url(provider["name"], provider["root_index"], root_index=provider["root_index"]),
                "description": label["description"],
            }
        )
    return result


def project(
    source: dict[str, Any],
    graph: dict[str, Any],
    documents: list[dict[str, Any]],
    *, site_catalog: dict[str, Any] | None = None,
) -> str:
    """Return deterministic Markdown from Site source plus the selected Bundle model."""
    entries = _source_entries(source)
    routes = _document_routes([d for d in documents if d.get("publication") != "site"])
    routes.update(_document_routes(_site_documents(source, site_catalog or {})))
    lines = [GENERATED_MARKER, f"# {source['title']}", ""]
    for section in source["sections"]:
        lines.extend([f"## {section['title']}", ""])
        for entry in entries:
            if entry["section"] != section["title"]:
                continue
            href = _resolve_entry(entry, routes)
            lines.append(f"- [{entry['label']}]({href}) - {entry['description']}")
            lines.append("")
    lines.extend(["## Provider navigation", ""])
    for entry in _provider_entries(source, graph):
        lines.append(f"- [{entry['label']}]({entry['href']}) - {entry['description']}")
        lines.append("")
    return "\n".join(lines)


def write(
    site_root: Path,
    output_root: Path,
    graph: dict[str, Any],
    documents: list[dict[str, Any]],
) -> Path:
    source = read_json(site_root / "progressive-discovery.json")
    output = output_root / "index.md"
    if output.exists() or output.is_symlink():
        raise BundleError("progressive discovery output already exists")
    output.write_text(project(source, graph, documents,
                              site_catalog=read_json(site_root / "docs/publication-catalog.json")),
                      encoding="utf-8")
    return output


def validate_generated(path: Path, *, expected: str | None = None) -> None:
    text = path.read_text(encoding="utf-8")
    if expected is not None and text != expected:
        raise BundleError("generated progressive discovery is stale")
    lines = text.splitlines()
    if not lines or lines[0] != GENERATED_MARKER or len(lines) < 2 or not lines[1].startswith("# "):
        raise BundleError("generated progressive discovery must begin with its marker and H1")
    if any(line.startswith("# ") for line in lines[2:]):
        raise BundleError("generated progressive discovery contains a second H1")
