#!/usr/bin/env python3
"""Check local index.md navigation against canonical catalogs and agent entrypoints.

--write refreshes one generated inventory index. No network, upstream toolchain,
source pins, repository mutation or publication build is needed for validation.
"""

from __future__ import annotations

import argparse
import html
import json
import posixpath
import re
import subprocess
import sys
from collections import deque
from pathlib import Path
from urllib.parse import quote, unquote, urlsplit


class DiscoveryError(ValueError):
    """The local discovery route is incomplete or refers to invalid material."""


def read_json(path):
    def unique(items):
        result = {}
        for key, value in items:
            if key in result:
                raise DiscoveryError(f"{path}: duplicate JSON key {key}")
            result[key] = value
        return result

    return json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=unique)


def local_path(root, value):
    if (
        not isinstance(value, str)
        or not value
        or "\\" in value
        or value.startswith("/")
        or any(ord(c) < 32 for c in value)
        or any(part in {"", ".", ".."} for part in value.split("/"))
    ):
        raise DiscoveryError(f"invalid repository path: {value!r}")
    path = root / value
    if any(item.is_symlink() for item in (path, *path.parents) if item != root.parent):
        raise DiscoveryError(f"symlink in discovery path: {value}")
    if not path.exists():
        raise DiscoveryError(f"missing discovery target: {value}")
    return value


def inventory(root):
    """Read existing source catalogs; never maintain discovery-only membership."""
    groups = {}

    def add(name, values):
        groups[name] = sorted(
            set(local_path(root, value.rstrip("/")) for value in values)
        )

    publication = "docs/publication-catalog.json"
    catalog = read_json(root / publication)
    documents = catalog["documents"]
    sources, ids = [], set()
    for item in documents:
        if item["id"] in ids or item["source"] in sources:
            raise DiscoveryError(f"{publication}: duplicate document ID or source")
        ids.add(item["id"])
        if item.get("optional") and not (root / item["source"]).exists():
            continue
        sources.append(item["source"])
    add("Published canonical documents", sources)
    assets = [
        item["source"]
        for item in catalog.get("assets", [])
        if not item.get("optional") or (root / item["source"]).exists()
    ]
    if catalog.get("glossary"):
        assets.append(catalog["glossary"]["source"])
    add("Publication catalog and supporting material", [publication, *assets])

    # The product catalogs already define these relationships. They are not
    # repeated in a discovery manifest or a hand-maintained expected-path list.
    if (root / "catalog/catalog.json").is_file():
        data = read_json(root / "catalog/catalog.json")
        add(
            "Composition product definitions",
            [
                "catalog/catalog.json",
                *(f"components/{name}/component.json" for name in data["components"]),
                *(f"recipes/{name}.json" for name in data["recipes"]),
            ],
        )
    if (root / "catalog.json").is_file():
        data = read_json(root / "catalog.json")
        add(
            "Modeling source records",
            [
                "catalog.json",
                *(item["source"] for item in data["records"]),
                *(f"collections/{item['id']}.json" for item in data.get("collections", [])),
            ],
        )
    if (root / "profiles").is_dir():
        import yaml

        for path in sorted((root / "profiles").glob("*.yml")):
            data = yaml.safe_load(path.read_text(encoding="utf-8"))
            if isinstance(data, dict) and "policy_files" in data:
                relative = path.relative_to(root).as_posix()
                add(relative, [relative, *data["policy_files"]])

    tracked = (
        subprocess.check_output(["git", "-C", str(root), "ls-files", "-z"])
        .decode()
        .split("\0")
    )
    # Directory links are terminal browsing entrypoints, never evidence that
    # individual canonical documents beneath them have index navigation.
    top = {
        path.split("/")[0]
        for path in tracked
        if path and not path.startswith("discovery/")
    }
    add("Agent implementation and maintenance entrypoints", top)
    return groups


def render(groups):
    lines = [
        "# Authority material index",
        "",
        "<!-- Generated by scripts/check_discovery.py --write. -->",
        "",
        "<!-- Catalogs own membership; public Site routes are independent. -->",
        "",
    ]
    for title, paths in groups.items():
        lines += [f"## {title}", ""]
        for path in paths:
            target = quote(posixpath.relpath(path, "discovery"), safe="/.-_")
            label = path.replace("[", r"\[").replace("]", r"\]")
            lines.append(
                f"- [{label}]({target}) - Declared source material or browsing entrypoint."
            )
        lines.append("")
    return "\n".join(lines)


def visible_markdown(text):
    text = re.sub(r"<!--.*?(?:-->|$)", "", text, flags=re.S)
    text = re.sub(
        r"<(pre|code|script|style)\b[^>]*>.*?</\1\s*>", "", text, flags=re.S | re.I
    )
    lines, fence = [], ""
    for line in text.splitlines():
        marker = re.match(r"^\s*(`{3,}|~{3,})(.*)$", line)
        if fence:
            if (
                marker
                and marker[1][0] == fence[0]
                and len(marker[1]) >= len(fence)
                and not marker[2].strip()
            ):
                fence = ""
            continue
        if marker:
            fence = marker[1]
            continue
        if not line.startswith(("    ", "\t")):
            lines.append(line)
    return re.sub(r"(`+).*?\1", "", "\n".join(lines), flags=re.S)


DEST = r"(?:<([^>\n]+)>|((?:\\.|[^\s()\\]|\([^()\n]*\))+))"
INLINE = re.compile(
    r"(?<!!)\[[^\]\n]*\]\(\s*" + DEST + r'(?:\s+["\'][^\n]*?["\'])?\s*\)'
)
REFERENCE = re.compile(r"^ {0,3}\[([^\]\n]+)\]:\s*" + DEST + r"(?:\s+.*)?$", re.M)


def links(text):
    text = visible_markdown(text)
    definitions = {
        m[1].strip().casefold(): m[2] or m[3] for m in REFERENCE.finditer(text)
    }
    text = REFERENCE.sub("", text)
    for match in INLINE.finditer(text):
        yield match[1] or match[2]
    text = INLINE.sub("", text)
    for match in re.finditer(r"(?<!!)\[([^\]\n]+)\](?:\[([^\]\n]*)\])?", text):
        key = (match[2] or match[1]).strip().casefold()
        if key in definitions:
            yield definitions[key]
    for match in re.finditer(r'<a\s+[^>]*href=["\']([^"\']+)["\']', text, re.I):
        yield match[1]


def graph(root, start):
    routes = {start: [start]}
    queue = deque([start])
    scanned, errors = set(), []
    while queue:
        source = queue.popleft()
        if source in scanned:
            continue
        scanned.add(source)
        try:
            local_path(root, source)
            text = (root / source).read_text(encoding="utf-8")
            for href in links(text):
                url = urlsplit(html.unescape(href))
                if url.scheme or url.netloc:
                    continue  # External/deployed links do not prove source discovery.
                if url.path.startswith("/"):
                    raise DiscoveryError(
                        f"absolute URL cannot navigate repository source: {href}"
                    )
                relative = unquote(url.path)
                target = (
                    posixpath.normpath(
                        posixpath.join(posixpath.dirname(source), relative)
                    )
                    if relative
                    else source
                )
                local_path(root, target)
                routes.setdefault(target, [*routes[source], target])
                if (root / target).is_dir() and (root / target / "index.md").exists():
                    child = target + "/index.md"
                    routes.setdefault(child, [*routes[target], child])
                    queue.append(child)
                elif Path(target).name == "index.md":
                    queue.append(target)
        except (ValueError, OSError) as exc:
            errors.append(f"{source}: {exc}")
    return routes, errors


def check(root, write=False):
    root = Path(root).resolve(strict=True)
    groups = inventory(root)
    expected = set().union(*map(set, groups.values()))
    destination = root / "discovery/index.md"
    projection = render(groups)
    if write:
        parent = destination.parent
        if parent.is_symlink() or destination.is_symlink():
            raise DiscoveryError("generated index path is a symlink")
        if (
            destination.exists()
            and "<!-- Generated by scripts/check_discovery.py --write. -->"
            not in destination.read_text()
        ):
            raise DiscoveryError("refusing to replace an authored index")
        parent.mkdir(exist_ok=True)
        destination.write_text(projection, encoding="utf-8")
    errors = []
    if (
        not destination.is_file()
        or destination.read_text(encoding="utf-8") != projection
    ):
        errors.append(
            "discovery/index.md differs from catalogs (missing/extra/stale entries); "
            "run python scripts/check_discovery.py --write"
        )
    routes, broken = graph(root, "index.md")
    errors.extend(broken)
    for path in sorted(expected | {"discovery/index.md"}):
        if path not in routes:
            errors.append(f"unreachable from root index.md: {path}")
    return {
        "valid": not errors,
        "inventory_groups": len(groups),
        "required_materials": len(expected),
        "visited_indexes": sum(Path(p).name == "index.md" for p in routes),
        "errors": errors,
        "routes": {p: routes[p] for p in sorted(expected) if p in routes},
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root", type=Path, default=Path(__file__).resolve().parents[1]
    )
    parser.add_argument(
        "--write", action="store_true", help="refresh the generated inventory index"
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="include the discovery route to every required material",
    )
    args = parser.parse_args()
    try:
        result = check(args.root, args.write)
    except (ValueError, OSError, KeyError, TypeError) as exc:
        result = {"valid": False, "errors": [str(exc)]}
    if args.json:
        print(json.dumps(result, indent=2, ensure_ascii=False))
    else:
        if result["valid"]:
            print(
                f"Discovery OK: {result['inventory_groups']} inventory groups, "
                f"{result['required_materials']} materials, {result['visited_indexes']} indexes"
            )
        for error in result["errors"]:
            print(error, file=sys.stderr)
    return 0 if result["valid"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
