#!/usr/bin/env python3
"""Render Site self-description from public consumer declarations; never manage state."""
from __future__ import annotations
import argparse
import json
from pathlib import Path
import yaml

START = "<!-- reference-consumer:start -->"
END = "<!-- reference-consumer:end -->"


def project(root: Path):
    def read(path):
        return json.loads((root / path).read_text())
    discovery = read("reference-consumer.json")
    relations = discovery["relationships"]
    # Composition's lock-v2 ownership inventory is a documented public contract.
    # Policy configuration is public; Policy lock/adoption internals stay opaque.
    composition = read(relations["product"]["state"])
    intent = read(relations["product"]["intent"])
    policy = yaml.safe_load((root / relations["maintenance"]["configuration"]).read_text())
    publication = read(relations["publication"]["selection"])
    return {"schema_version":1,"kind":"reference-consumer-description",
            "repository":discovery["repository"],"authority":"site",
            "composition":{"source":composition["source"],"intent":intent,
                           "ownership":composition["files"],"state":relations["product"]["state"]},
            "policy":{"toolchain":policy["toolchain"],"contexts":policy["contexts"],
                      "outputs":policy["outputs"],"configuration":relations["maintenance"]["configuration"],
                      "state":relations["maintenance"]["state"]},
            "publication":publication,
            "validation": {"composition":relations["product"]["validation"],
                           "policy_workflow":relations["maintenance"]["validation_workflow"],
                           "integration_workflow":".github/workflows/reference-consumer.yml"}}


def explanation(data):
    c = data["composition"]["source"]["revision"]
    p = data["policy"]["toolchain"]["revision"]
    published = data["publication"]["publications"]
    return f"""## Self-hosting reference consumer

This Site consumes the systems it provides. Its Website product uses the
Composition `website` recipe and `capability.pwa`; its maintenance uses Policy.
The relationships below are generated from their canonical declarations.

| Relationship | Immutable revision | Meaning |
| --- | --- | --- |
| Composition consumer | `{c}` | Governs the Site Website contracts and material ownership |
| Policy consumer | `{p}` | Governs Site maintenance and generated agent instructions |
| Composition publication | `{published['composition']['revision']}` | Provider material exposed to readers |
| Policy publication | `{published['policy']['revision']}` | Provider material exposed to readers |

```mermaid
flowchart TD
  C["Composition: immutable consumer revision"] -->|"Website and PWA contracts"|S["Site product"]
  P["Policy: immutable toolchain revision"] -->|"Maintenance rules"|M["Site maintenance"]
  M -->|"Changes and verifies"|S
  CP["Separately selected publication revisions"] -->|"Reader content"|S
```

This is a temporal bootstrap, not a runtime cycle: known provider revision N
governs a later consumer revision N+1. Semantic source, toolchain, generated
projection, and publication identities may differ. Advancing publication does
not update either consumer, and consuming a candidate does not publish it.

The public [machine-readable description](/reference-consumer.json) includes the
full Composition ownership inventory, independent Policy configuration, and
validation entrypoints. In the source tree, `reference-consumer.json` is the
discovery index. `.template-composition/lock.json` records Composition ownership;
`.agent-policy.yml` selects Policy and `.agent-policy.lock` remains Policy-owned.
There is no combined lock or shared transaction manager.

Composition-managed schemas, validators, and generated registry remain provider
material. Site owns its implementation and customized seed worksheets. Its
primary publication entrypoints are projected from `site-manifest.json` into
Website contracts. Generated source viewers, guided views, translations, and
other secondary surfaces continue to use their existing Site acceptance tests;
the primary Website inventory does not claim to enumerate those derived pages.

Site-local normative constraints live in `policy/project.md`; procedural Skills
remain under `.agents/skills/`. `AGENTS.md` and the review-authority document are
generated by the selected Policy toolchain. The original handwritten routing
instructions are retained as non-authoritative migration evidence.

Adoption exposed two reusable model gaps: directory-style URLs needed routes v5,
and contract inventory closure needed to follow Composition ownership rather
than reserve every file in shared directories. Both fixes belong to Composition.
The Site is an ordinary consumer of those semantics, not a privileged exception.

Validation is executable and separate: Composition checks its own state and
contracts, Policy checks its own outputs, and Site checks the real Pages artifact
in a browser. The recorded planning checkpoint is this adoption assessment; it
does not pretend to reconstruct the Website's original development history.
Contract validation is not proof of deployment or release readiness; deferred
browser evidence remains visible until the relevant proof actually runs.
"""


def outputs(root):
    data = project(root)
    doc = root / "docs/policy-composition-coexistence.md"
    text = doc.read_text()
    section = START + "\n\n" + explanation(data) + "\n" + END
    if START in text:
        before, rest = text.split(START, 1)
        _, after = rest.split(END, 1)
        text = before + section + after
    else:
        text = text.rstrip() + "\n\n" + section + "\n"
    return {"assets/reference-consumer.json":json.dumps(data,indent=2,ensure_ascii=False)+"\n",
            "docs/policy-composition-coexistence.md":text}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository",type=Path,default=Path(__file__).resolve().parents[1])
    parser.add_argument("--write",action="store_true")
    args = parser.parse_args()
    for relative, content in outputs(args.repository).items():
        path = args.repository / relative
        if args.write:
            path.write_text(content)
        elif not path.is_file() or path.read_text() != content:
            raise SystemExit(f"Stale reference-consumer projection: {relative}")
