#!/usr/bin/env python3
"""Render Site self-description from public consumer declarations; never manage state."""
from __future__ import annotations
import argparse
import json
from pathlib import Path
import yaml

START = "<!-- reference-consumer:start -->"
END = "<!-- reference-consumer:end -->"


def project(root: Path):
    def read(path):
        return json.loads((root / path).read_text())
    discovery = read("reference-consumer.json")
    relations = discovery["relationships"]
    # Composition's lock-v2 ownership inventory is a documented public contract.
    # Policy configuration is public; Policy lock/adoption internals stay opaque.
    composition = read(relations["product"]["state"])
    intent = read(relations["product"]["intent"])
    policy = yaml.safe_load((root / relations["maintenance"]["configuration"]).read_text())
    publication = read(relations["publication"]["selection"])
    return {"schema_version":1,"kind":"reference-consumer-description",
            "repository":discovery["repository"],"authority":"site",
            "composition":{"source":composition["source"],"intent":intent,
                           "ownership":composition["files"],"state":relations["product"]["state"]},
            "policy":{"toolchain":policy["toolchain"],"contexts":policy["contexts"],
                      "outputs":policy["outputs"],"configuration":relations["maintenance"]["configuration"],
                      "state":relations["maintenance"]["state"]},
            "publication":publication,
            "validation": {"composition":relations["product"]["validation"],
                           "policy_workflow":relations["maintenance"]["validation_workflow"],
                           "integration_workflow":".github/workflows/reference-consumer.yml"}}


def explanation(data):
    c = data["composition"]["source"]["revision"]
    p = data["policy"]["toolchain"]["revision"]
    published = data["publication"]["publications"]
    return f"""## Self-hosting reference consumer

This Site consumes the systems it provides. Its Website product uses the
Composition `website` recipe and `capability.pwa`; its maintenance uses Policy.
The relationships below are generated from their canonical declarations.

| Relationship | Immutable revision | Meaning |
| --- | --- | --- |
| Composition consumer | `{c}` | Governs the Site Website contracts and material ownership |
| Policy consumer | `{p}` | Governs Site maintenance and generated agent instructions |
| Composition publication | `{published['composition']['revision']}` | Provider material exposed to readers |
| Policy publication | `{published['policy']['revision']}` | Provider material exposed to readers |

```mermaid
flowchart TD
  C["Composition: immutable consumer revision"] -->|"Website and PWA contracts"|S["Site product"]
  P["Policy: immutable toolchain revision"] -->|"Maintenance rules"|M["Site maintenance"]
  M -->|"Changes and verifies"|S
  CP["Separately selected publication revisions"] -->|"Reader content"|S
```

This is a temporal bootstrap, not a runtime cycle: known provider revision N
governs a later consumer revision N+1. Semantic source, toolchain, generated
projection, and publication identities may differ. Advancing publication does
not update either consumer, and consuming a candidate does not publish it.

The public [machine-readable description](/reference-consumer.json) includes the
full Composition ownership inventory, independent Policy configuration, and
validation entrypoints. In the source tree, `reference-consumer.json` is the
discovery index. `.template-composition/lock.json` records Composition ownership;
`.agent-policy.yml` selects Policy and `.agent-policy.lock` remains Policy-owned.
There is no combined lock or shared transaction manager.

Composition-managed schemas, validators, and generated registry remain provider
material. Site owns its implementation and customized seed worksheets. Its
primary publication entrypoints are projected from `site-manifest.json` into
Website contracts. Generated source viewers, guided views, translations, and
other secondary surfaces continue to use their existing Site acceptance tests;
the primary Website inventory does not claim to enumerate those derived pages.

Site-local normative constraints live in `policy/project.md`; procedural Skills
remain under `.agents/skills/`. `AGENTS.md` and the review-authority document are
generated by the selected Policy toolchain. The original handwritten routing
instructions are retained as non-authoritative migration evidence.

Adoption exposed two reusable model gaps: directory-style URLs needed routes v5,
and contract inventory closure needed to follow Composition ownership rather
than reserve every file in shared directories. Both fixes belong to Composition.
The Site is an ordinary consumer of those semantics, not a privileged exception.

Validation is executable and separate: Composition checks its own state and
contracts, Policy checks its own outputs, and Site checks the real Pages artifact
in a browser. The recorded planning checkpoint is this adoption assessment; it
does not pretend to reconstruct the Website's original development history.
Contract validation is not proof of deployment or release readiness; deferred
browser evidence remains visible until the relevant proof actually runs.
"""


def explanation_ja(data):
    c = data["composition"]["source"]["revision"]
    p = data["policy"]["toolchain"]["revision"]
    published = data["publication"]["publications"]
    return f"""## 自己ホスティングの参照 consumer

この Site は、自ら提供する Composition と Policy を実際に採用しています。
Website 製品は `website` recipe と `capability.pwa` を、保守作業は Policy を使います。
以下は正規の宣言から生成した関係です。

| 関係 | 不変 revision | 意味 |
| --- | --- | --- |
| Composition consumer | `{c}` | Website 契約と material の所有関係 |
| Policy consumer | `{p}` | 保守規範と生成された agent 指示 |
| Composition publication | `{published['composition']['revision']}` | 読者に公開する provider の内容 |
| Policy publication | `{published['policy']['revision']}` | 読者に公開する provider の内容 |

既知の provider revision N が後続の consumer revision N+1 を規定します。
これは時間順序を持つ bootstrap であり、実行時の循環依存ではありません。
意味、toolchain、projection、publication の identity は異なって構いません。
公開 revision の更新は consumer の更新ではなく、候補 revision の採用も公開を意味しません。

[機械可読の説明](/reference-consumer.json) は Composition の公開 ownership inventory、
独立した Policy 設定、検証入口を示します。ソースの `reference-consumer.json` が
discovery index です。Composition の state は `.template-composition/lock.json`、
Policy の選択は `.agent-policy.yml`、Policy 所有の state は `.agent-policy.lock` にあります。
共通 lock や共通 transaction manager はありません。

管理対象の schema、validator、生成 registry は Composition の所有物です。
Site の実装と具体化した seed worksheet は consumer 所有です。
主要な公開入口は `site-manifest.json` から Website 契約へ投影します。
生成 source viewer、guided view、翻訳などの派生ページは既存の Site 検証が担当し、
主要ページ inventory がそれらを全件列挙するとは主張しません。

Site 固有の規範は `policy/project.md`、手順は `.agents/skills/` に置きます。
`AGENTS.md` と review-authority は選択した Policy toolchain が生成します。
元の手書き指示は移行の履歴証拠として保存し、現行の規範とは扱いません。

実採用から、末尾スラッシュ付き URL を扱う routes v5 と、ディレクトリ全体ではなく
Composition の所有範囲に従う契約 inventory 検証が必要になりました。
両方を Composition 側で一般的に修正し、Site 固有の例外は設けていません。

Composition と Policy はそれぞれ自分の state を検証し、Site は実際の Pages artifact を
ブラウザで検証します。planning checkpoint は今回の採用評価を記録するものであり、
既存 Website の開発履歴を後から作るものではありません。契約検証だけで公開済みや
release-ready とは判断せず、未実施のブラウザ証拠は deferred として明示します。
"""


def insert_section(text, explanation):
    section = START + "\n\n" + explanation + "\n" + END
    if START in text:
        before, rest = text.split(START, 1)
        _, after = rest.split(END, 1)
        return before + section + after
    return text.rstrip() + "\n\n" + section + "\n"


def outputs(root):
    data = project(root)
    doc = root / "docs/policy-composition-coexistence.md"
    text = insert_section(doc.read_text(), explanation(data))
    translated_path = "translations/ja/docs/policy-composition-coexistence.md"
    translated = insert_section((root / translated_path).read_text(), explanation_ja(data))
    return {"assets/reference-consumer.json":json.dumps(data,indent=2,ensure_ascii=False)+"\n",
            "docs/policy-composition-coexistence.md":text,
            translated_path:translated}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository",type=Path,default=Path(__file__).resolve().parents[1])
    parser.add_argument("--write",action="store_true")
    args = parser.parse_args()
    for relative, content in outputs(args.repository).items():
        path = args.repository / relative
        if args.write:
            path.write_text(content)
        elif not path.is_file() or path.read_text() != content:
            raise SystemExit(f"Stale reference-consumer projection: {relative}")
