#!/usr/bin/env python3
"""Compare a candidate Bundle with a Bundle generated by trusted code.

The candidate qualification job may execute provider-owned generation code in
its read-only sandbox.  Adoption must not trust that code's success declaration,
so the reconciliation workflow also runs this command from the trusted
Integration checkout and uses the result as the transport input.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import sys

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from publication_bundle.contract import BundleError, validate


class BundleEquivalenceError(BundleError):
    """The candidate and trusted Bundle are not the same immutable output."""


def _files(root: Path) -> list[str]:
    entries: list[str] = []
    for path in sorted(root.rglob("*")):
        if path.is_symlink():
            raise BundleEquivalenceError(f"Bundle contains a symlink: {path}")
        if path.is_file():
            entries.append(path.relative_to(root).as_posix())
    return entries


def verify(candidate: Path, trusted: Path) -> dict:
    try:
        candidate_manifest = validate(candidate)
        trusted_manifest = validate(trusted)
    except BundleError as exc:
        raise BundleEquivalenceError(str(exc)) from exc
    if candidate_manifest != trusted_manifest:
        raise BundleEquivalenceError(
            "candidate Bundle manifest differs from trusted regeneration"
        )
    candidate_files = _files(candidate)
    trusted_files = _files(trusted)
    if candidate_files != trusted_files:
        raise BundleEquivalenceError("candidate Bundle inventory differs from trusted regeneration")
    for relative in candidate_files:
        candidate_bytes = (candidate / relative).read_bytes()
        trusted_bytes = (trusted / relative).read_bytes()
        if candidate_bytes != trusted_bytes:
            raise BundleEquivalenceError(
                f"candidate Bundle payload differs from trusted regeneration: {relative}"
            )
    return {
        "schema_version": 1,
        "classification": "TRUSTED_EQUIVALENT",
        "bundle_identity": candidate_manifest["identity"],
        "bundle_content_digest": candidate_manifest["content_digest"],
        "file_count": len(candidate_files),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--candidate", type=Path, required=True)
    parser.add_argument("--trusted", type=Path, required=True)
    args = parser.parse_args()
    try:
        print(verify(args.candidate, args.trusted))
    except (BundleError, OSError, ValueError) as exc:
        parser.error(str(exc))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
